/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "key.h"
#include "stdio.h"
#include "stdlib.h" 
#include "led.h"
#include "24L01.h"
#include "FramewinDLG.h"

extern GUI_CONST_STORAGE GUI_BITMAP bmwireless;
extern GUI_CONST_STORAGE GUI_BITMAP bmappstore;
extern GUI_CONST_STORAGE GUI_BITMAP bmset;
extern GUI_CONST_STORAGE GUI_BITMAP bmnotebook;
extern GUI_CONST_STORAGE GUI_BITMAP bmebook;
extern GUI_CONST_STORAGE GUI_BITMAP bmpaint;
extern GUI_CONST_STORAGE GUI_BITMAP bmbackground;
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontfont12;
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontfont14;
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontfont16;
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontfont24;


#define MAIN_BKCOLOR              0xD0D0D0
#define MAIN_TEXTCOLOR            0x000000
#define MAIN_FONT                 (&GUI_Fontfont16)
#define MAIN_BORDER               10
#define MAIN_TITLE_HEIGHT         30
#define MAIN_LOGO_BITMAP          (&bmset)
#define MAIN_LOGO_OFFSET_X        0
#define MAIN_LOGO_OFFSET_Y        5

#define FRAME_BKCOLOR             0xB0B0B0
#define FRAME_TEXTCOLOR           0x000000
#define FRAME_FONT                (&GUI_Fontfont12)
#define FRAME_EFFECT              (&WIDGET_Effect_3D2L)
#define FRAME_BORDER              FRAME_EFFECT->EffectSize
#define FRAME_WIDTH               (LCD_GetXSize() - (FRAME_BORDER * 2) - (MAIN_BORDER * 2))
#define FRAME_HEIGHT              (LCD_GetYSize() - (FRAME_BORDER * 2) - (MAIN_BORDER + MAIN_TITLE_HEIGHT))


#define FRAME_BUTTON_BKCOLOR0     0xB8B8B8              /* Unpressed */
#define FRAME_BUTTON_BKCOLOR1     0xE0E0E0              /* Pressed   */
#define FRAME_BUTTON_BKCOLOR2     0xC0C0C0              /* Disabled  */
#define FRAME_BUTTON_COLOR0       0x000000              /* Unpressed */
#define FRAME_BUTTON_COLOR1       0x000000              /* Pressed   */
#define FRAME_BUTTON_FONT         (&GUI_Fontfont12)
#define FRAME_BUTTON_EFFECT       (&WIDGET_Effect_3D2L)
#define DEFAULT_WIDGET_EFFECT     (&WIDGET_Effect_3D2L)

#define MSG_UPDATE_DATA (WM_USER + 5)
#define ID_FRAMEWIN_0 (GUI_ID_USER + 0x00)
#define ID_DROPDOWN_0 (GUI_ID_USER + 0x01)
#define ID_BUTTON_0 (GUI_ID_USER + 0x02)
#define ID_TEXT_0 (GUI_ID_USER + 0x03)
#define ID_BUTTON_1 (GUI_ID_USER + 0x04)
#define ID_TEXT_1 (GUI_ID_USER + 0x05)
#define ID_EDIT_0 (GUI_ID_USER + 0x06)
#define ID_TEXT_2 (GUI_ID_USER + 0x07)
#define ID_TEXT_3 (GUI_ID_USER + 0x08)
#define ID_TEXT_4 (GUI_ID_USER + 0x09)
#define ID_TEXT_5 (GUI_ID_USER + 0x0A)
#define ID_EDIT_1 (GUI_ID_USER + 0x0B)
#define ID_EDIT_2 (GUI_ID_USER + 0x0C)
#define ID_EDIT_3 (GUI_ID_USER + 0x0D)
#define ID_BUTTON_2 (GUI_ID_USER + 0x12)
#define ID_BUTTON_3 (GUI_ID_USER + 0x13)
#define ID_BUTTON_4 (GUI_ID_USER + 0x14)
#define ID_BUTTON_5 (GUI_ID_USER + 0x15)

static void _cbSelect(WM_MESSAGE* pMsg) ;
static void _cbInputParameter(WM_MESSAGE* pMsg) ;
static void _cbwireless(WM_MESSAGE* pMsg) ;
static void _cbSingledrill(WM_MESSAGE* pMsg) ;
static void _cbrundrill(WM_MESSAGE* pMsg) ;
static void _cbringmold(WM_MESSAGE* pMsg) ;
void Welcome_page(void);
void Wait_page(void);

static WM_HWIN    _hCurrentFrame;
u8 buf[32];


/* ICONVIEW控件图标使用 */

typedef struct {
  const GUI_BITMAP * pBitmap;  
  const char       * pText;
} BITMAP_ITEM;


char model_Item[][10]={
    "定位",
    "扩孔",
    "钻孔"
};

char drill_Item[][10]={
    "大钻头",
    "小钻头"
};
char OddEven_Item[][10]={
    "奇数排",
    "偶数排"
};

static const BITMAP_ITEM _aBitmapItem[] = {
    {&bmset,        "inputpara"       },
    {&bmappstore,   "singledrill"     },
    {&bmwireless,   "wireless"        },
	{&bmnotebook,   "rundirll"        },
    {&bmebook,      "ringmold"        },
    {&bmpaint,      "expect"          }
};
/* 图标对应的应用程序 */
static void (* _apModules[])(WM_MESSAGE* pMsg) = 
{
	_cbInputParameter,
    _cbSingledrill,
    _cbwireless,
    _cbrundrill,
    _cbringmold,
    _cbringmold,
};


/*
*********************************************************************************************************
*	函 数 名: _DeleteFrame
*	功能说明: 删除创建的框架窗口
*	形    参：无
*	返 回 值: 无
*********************************************************************************************************
*/
static void _DeleteFrame(void) 
{
	WM_DeleteWindow(_hCurrentFrame);
	_hCurrentFrame = 0;
}


/*
*********************************************************************************************************
*	函 数 名: _CreateFrame
*	功能说明: 创建框架窗口
*	形    参：cb  回调函数地址
*	返 回 值: 无
*********************************************************************************************************
*/
static WM_HWIN _CreateFrame(WM_CALLBACK* cb) 
{
	int x = 0;
	int y = 0;
	x = FRAME_BORDER + MAIN_BORDER;
	y = FRAME_BORDER + MAIN_TITLE_HEIGHT;
	_hCurrentFrame = WM_CreateWindowAsChild(x, y, FRAME_WIDTH, FRAME_HEIGHT, WM_HBKWIN, WM_CF_SHOW, cb, 0);
	return _hCurrentFrame;
}


/*
*********************************************************************************************************
*	函 数 名: _PaintFrame
*	功能说明: 框架窗口的重绘函数
*	形    参：无
*	返 回 值: 无
*********************************************************************************************************
*/
static void _PaintFrame(void) 
{
	GUI_RECT r;
	WM_GetClientRect(&r);
	GUI_SetBkColor(FRAME_BKCOLOR);
	GUI_SetColor(FRAME_TEXTCOLOR);
	GUI_SetFont(FRAME_FONT);
	//GUI_BMP_Draw(&bmbackground,0,0);
	GUI_SetTextMode(GUI_TM_TRANS);
	GUI_ClearRectEx(&r);
}

void _SendMsg(void)
{
    WM_MESSAGE Message;
    Message.MsgId =  MSG_UPDATE_DATA;
    WM_SendMessage(WM_GetClientWindow(_hCurrentFrame),&Message); 
}


static void Set_text_value(GUI_HWIN hWin,int id,u8 value,const char pText[][10])
{
    WM_HWIN hItem;
    WM_CALLBACK *pCb;
    hItem = WM_GetDialogItem(hWin, id);
    pCb = WM_GetCallback(hItem);
    if(pCb == TEXT_Callback)
    {
        TEXT_SetText(hItem,pText[value]);
    }
    
}

static void Set_widget_value(GUI_HWIN hWin,int id,u8 value)
{
    char tmp[10];
    WM_HWIN hItem;
    WM_CALLBACK *pCb;
    hItem = WM_GetDialogItem(hWin, id);
    pCb = WM_GetCallback(hItem);
    if(pCb == DROPDOWN_Callback)
    {    
         DROPDOWN_SetSel(hItem,value);
    }
    else if(pCb == EDIT_Callback)
    {
        sprintf(tmp,"%u",value);
        EDIT_SetText(hItem,tmp);
    }
    else if(pCb == RADIO_Callback)
    {
        RADIO_SetValue(hItem,value);
    }
}

static u8 Get_widget_value(GUI_HWIN hWin,int id)
{
    char tmp[10];
    WM_HWIN hItem;
    WM_CALLBACK *pCb;
    hItem = WM_GetDialogItem(hWin, id);
    pCb = WM_GetCallback(hItem);
    if(pCb == RADIO_Callback)
    {    
        return RADIO_GetValue(hItem);
    }
    else if(pCb == DROPDOWN_Callback)
    {
        return DROPDOWN_GetSel(hItem);
    }
    else if(pCb == EDIT_Callback)
    {
        EDIT_GetText(hItem,tmp,10);
        return (u8)atoi(tmp);
    }

}

void Get_User_Data(GUI_HWIN hWin)
{
    buf[1] = Get_widget_value(hWin,GUI_ID_RADIO0);//模式
    buf[4] = Get_widget_value(hWin,GUI_ID_EDIT0);
    buf[5] = Get_widget_value(hWin,GUI_ID_EDIT1);
    buf[6] = Get_widget_value(hWin,GUI_ID_EDIT2);
    buf[7] = Get_widget_value(hWin,GUI_ID_EDIT3);
}

void Set_User_Data(GUI_HWIN hWin)
{
    Set_widget_value(hWin,GUI_ID_RADIO0,buf[1]);
    Set_widget_value(hWin,GUI_ID_EDIT0,buf[4]);
    Set_widget_value(hWin,GUI_ID_EDIT1,buf[5]);
    Set_widget_value(hWin,GUI_ID_EDIT2,buf[6]);
    Set_widget_value(hWin,GUI_ID_EDIT3,buf[7]);
}

void Get_Drill_Data(GUI_HWIN hWin)
{
    buf[8] = Get_widget_value(hWin,GUI_ID_EDIT0);
    buf[9] = Get_widget_value(hWin,GUI_ID_RADIO0);
    if(buf[1]==1)
    {
        buf[10] = Get_widget_value(hWin,GUI_ID_EDIT1);  
    }
    else if(buf[1]==2)
    {
        buf[10] = Get_widget_value(hWin,GUI_ID_EDIT1);  
        buf[11] = Get_widget_value(hWin,GUI_ID_EDIT2);
        buf[12] = Get_widget_value(hWin,GUI_ID_RADIO1);
    }
}

void Set_Drill_Data(GUI_HWIN hWin)
{
    Set_widget_value(hWin,GUI_ID_EDIT0,buf[8]);
    Set_widget_value(hWin,GUI_ID_RADIO0,buf[9]);
    if(buf[1]==1)
    {
        Set_widget_value(hWin,GUI_ID_EDIT1,buf[10]);  
    }
    else if(buf[1]==2)
    {
        Set_widget_value(hWin,GUI_ID_EDIT1 ,buf[10]);  
        Set_widget_value(hWin,GUI_ID_EDIT2 ,buf[11]);
        Set_widget_value(hWin,GUI_ID_RADIO1,buf[12]);
    }
}

void Set_Data(GUI_HWIN hWin)
{
    Set_text_value(hWin,GUI_ID_TEXT7,buf[1],model_Item); //模式
    Set_widget_value(hWin,GUI_ID_EDIT0,buf[4]);
    Set_widget_value(hWin,GUI_ID_EDIT1,buf[5]);
    Set_widget_value(hWin,GUI_ID_EDIT2,buf[6]);
    Set_widget_value(hWin,GUI_ID_EDIT3,buf[7]);

    Set_widget_value(hWin,GUI_ID_EDIT4,buf[8]);
    Set_text_value(hWin,GUI_ID_TEXT8,buf[9],OddEven_Item);  //奇偶数排
    Set_widget_value(hWin,GUI_ID_EDIT5,buf[10]);
    Set_widget_value(hWin,GUI_ID_EDIT6,buf[11]);
    Set_text_value(hWin,GUI_ID_TEXT9,buf[12],drill_Item); //大小钻头
}
/*
*********************************************************************************************************
*	函 数 名: _DrawDownRectEx
*	功能说明: 显示凹陷的矩形框
*	形    参：pEffect  控件显示效果
*             pRect    GUI_RECT类型变量地址
*	返 回 值: 无
*********************************************************************************************************
*/
static void _DrawDownRectEx(const WIDGET_EFFECT* pEffect, const GUI_RECT* pRect) 
{
	WM_LOCK();
	pEffect->pfDrawDownRect(pRect);
	WM_UNLOCK();
}

/*
*********************************************************************************************************
*	函 数 名: _DrawDownRect
*	功能说明: 显示凹陷的矩形框
*	形    参：pEffect  控件显示效果
*             x0       起始x轴坐标
*             y0       起始y轴坐标
*             x1       结束x轴坐标
*             y1       结束y轴坐标
*	返 回 值: 无
*********************************************************************************************************
*/
static void _DrawDownRect(const WIDGET_EFFECT* pEffect, int x0, int y0, int x1, int y1) 
{
	GUI_RECT r;
	r.x0 = x0;
	r.y0 = y0;
	r.x1 = x1;
	r.y1 = y1;
	_DrawDownRectEx(pEffect, &r);
}

/*
*********************************************************************************************************
*	函 数 名: _CreateButton
*	功能说明: 创建按钮
*	形    参：
*             x        x轴坐标
*             y        y轴坐标
*             w        按钮宽
*             h        按钮高
*             hParent  父窗口     
*             Id       按钮Id   
*             pText    按键上显示的文本
*             bmp      图片
*             type     文字或图片
*	返 回 值: 无
*********************************************************************************************************
*/
static WM_HWIN _CreateButton(int x, int y, int w, int h, WM_HWIN hParent, int Id, const char* pText,const GUI_BITMAP* bmp,int type) 
{
	WM_HWIN hButton;
	hButton = BUTTON_CreateEx(x, y, w, h, hParent, WM_CF_SHOW, 0, Id);
    if(type==0)
    {
        BUTTON_SetText(hButton,pText);
    }
    else
    {
        BUTTON_SetBitmapEx(hButton,0,bmp,10,10);
    }
	BUTTON_SetFont      (hButton,    FRAME_BUTTON_FONT);
	BUTTON_SetBkColor   (hButton, 0, FRAME_BUTTON_BKCOLOR0);
	BUTTON_SetBkColor   (hButton, 1, FRAME_BUTTON_BKCOLOR1);
	BUTTON_SetBkColor   (hButton, 2, FRAME_BUTTON_BKCOLOR2);
	BUTTON_SetTextColor (hButton, 0, FRAME_BUTTON_COLOR0);
	BUTTON_SetTextColor (hButton, 1, FRAME_BUTTON_COLOR1);
	BUTTON_SetTextColor (hButton, 2, FRAME_BUTTON_COLOR0);
	WIDGET_SetEffect    (hButton,    FRAME_BUTTON_EFFECT);
	
	/* 设置接收输入焦点的能力 */
	BUTTON_SetFocussable(hButton,    1);
	return hButton;
}


/*
*********************************************************************************************************
*	函 数 名: _CreateIcon
*	功能说明: 创建图标
*	形    参：      
*             x        x轴坐标
*             y        y轴坐标
*             w        按钮宽
*             h        按钮高   
*             hParent  父窗口
*             Id       按钮Id   
*********************************************************************************************************
*/
static WM_HWIN _CreateIcon( int x, int y, int w, int h,WM_HWIN hParent,int Id) 
{
    int i;
    WM_HWIN hIcon;
	/* 创建ICON控件 */
	hIcon = ICONVIEW_CreateEx(x, y, w, h, hParent, WM_CF_SHOW | WM_CF_HASTRANS, ICONVIEW_CF_AUTOSCROLLBAR_V ,
							  Id, 80, 80);
	ICONVIEW_SetFont(hIcon, &GUI_Font13B_ASCII);
	ICONVIEW_SetBkColor(hIcon, ICONVIEW_CI_SEL, 0x941000 | 0x80404040);
	ICONVIEW_SetSpace(hIcon, GUI_COORD_Y, 10);
	ICONVIEW_SetFrame(hIcon, GUI_COORD_Y, 10);
	for (i = 0; i < GUI_COUNTOF(_aBitmapItem); i++)
	{
        
		ICONVIEW_AddBitmapItem(hIcon,_aBitmapItem[i].pBitmap, _aBitmapItem[i].pText);
	}
	WM_SetFocus(hIcon);
    return hIcon;
}

/*
*********************************************************************************************************
*	函 数 名: _CreateText
*	功能说明: 创建文本
*	形    参：      
*             x        x轴坐标
*             y        y轴坐标
*             w        按钮宽
*             h        按钮高   
*             hParent  父窗口
*             Id       Id   
*             pText    字符串
*********************************************************************************************************
*/
static void _CreateText( int x, int y, int w, int h,WM_HWIN hParent,int Text_Id,const char* pText) 
{
    WM_HWIN hText;
    hText = TEXT_CreateEx(x, y, w, h, hParent, WM_CF_SHOW, 0, Text_Id, pText);
    TEXT_SetFont(hText,FRAME_FONT);
} 
/*
*********************************************************************************************************
*	函 数 名: _CreateEdit
*	功能说明: 创建编辑框
*	形    参：      
*             x        x轴坐标
*             y        y轴坐标
*             w        按钮宽
*             h        按钮高   
*             hParent  父窗口
*             Id       Id   
*             maxlen   最大字符数
*             focus    输入焦点
*********************************************************************************************************
*/
static WM_HWIN _CreateEdit( int x, int y, int w, int h,WM_HWIN hParent,int Edit_Id,int maxLen,int focus) 
{
	WM_HWIN hEdit;
    hEdit = EDIT_CreateEx( x, y, w, h, hParent, WM_CF_SHOW, 0, Edit_Id, maxLen);
    EDIT_SetFont(hEdit,GUI_FONT_20B_ASCII);
    EDIT_SetTextAlign(hEdit, GUI_TA_CENTER);
    WIDGET_SetEffect(hEdit, DEFAULT_WIDGET_EFFECT);
    
	/* 设置接收输入焦点的能力 */
	EDIT_SetFocussable(hEdit,focus);
	return hEdit;
}


/*
*********************************************************************************************************
*	函 数 名: _Createradio
*	功能说明: 创建单选框
*	形    参：      
*             x        x轴坐标
*             y        y轴坐标
*             w        按钮宽
*             h        按钮高   
*             hParent  父窗口
*             Id       Id   
*             pText    字符串
*             num      字符个数
*********************************************************************************************************
*/
static WM_HWIN _Createradio( int x, int y, int w, int h,WM_HWIN hParent,int Id, const char pText[2][10],int num) 
{
	WM_HWIN hRadio;
    int i=0;
    hRadio = RADIO_CreateEx(x,y,w,h,hParent,WM_CF_SHOW,0,Id,num,30);
    RADIO_SetFont(hRadio,FRAME_FONT);
    for(i=0;i<num;i++)
    {
        RADIO_SetText(hRadio,*(pText+i),i);
    }
	return hRadio;
}

/*
*********************************************************************************************************
*	函 数 名: _cbBkWindow
*	功能说明: 桌面窗口回调函数
*	形    参：pMsg  参数指针
*	返 回 值: 无
*********************************************************************************************************
*/
static void _cbBkWindow(WM_MESSAGE* pMsg) 
{
	switch (pMsg->MsgId) 
	{
		case WM_PAINT: 
			{
				int x, y, w, h;
				GUI_SetBkColor(MAIN_BKCOLOR);
				GUI_SetColor(MAIN_TEXTCOLOR);
				GUI_SetFont(MAIN_FONT);
				GUI_Clear();
                GUI_DispStringAt("手持钻床控制器",0, 0);
				x = MAIN_LOGO_OFFSET_X + MAIN_BORDER;
				y = MAIN_LOGO_OFFSET_Y + ((MAIN_TITLE_HEIGHT - MAIN_LOGO_BITMAP->YSize) >> 1);
				x = MAIN_BORDER;
				y = MAIN_TITLE_HEIGHT;
				w = LCD_GetXSize() - (MAIN_BORDER * 2);
				h = LCD_GetYSize()  - (MAIN_BORDER + MAIN_TITLE_HEIGHT);
				_DrawDownRect(FRAME_EFFECT, x, y, x + w - 1, y + h - 1);

			} 
			break;
		default:
			WM_DefaultProc(pMsg);
	}
}


/*
*********************************************************************************************************
*	函 数 名: _cbwait
*	功能说明: 第六个界面，等待工作结束
*	形    参：pMsg  参数指针
*	返 回 值: 无
*********************************************************************************************************
*/
static void _cbwait(WM_MESSAGE* pMsg) 
{
	WM_HWIN  hWin = pMsg->hWin;
	switch (pMsg->MsgId) 
	{
		case WM_CREATE:
			/* 设置聚焦 */
			WM_SetFocus(hWin);
            WM_CreateTimer(hWin,0,2000,0);
			break;
		 case WM_KEY:
            break;
         case WM_TIMER:
            NRF24L01_RX_Mode();
            NRF24L01_RxPacket(buf);
            if(buf[0] == 1)
            {
                //执行完成
            }
			 _DeleteFrame();
			//WM_RestartTimer(pMsg->Data.v,1000);
			break;

		case WM_PAINT:
			_PaintFrame();

            break;
		default:
		WM_DefaultProc(pMsg);
	}
}

/*
*********************************************************************************************************
*	函 数 名: _cbringmold
*	功能说明: 第五个界面，环模电机控制
*	形    参：pMsg  参数指针
*	返 回 值: 无
*********************************************************************************************************
*/
static void _cbringmold(WM_MESSAGE* pMsg) 
{
	WM_HWIN  hWin = pMsg->hWin;
	switch (pMsg->MsgId) 
	{
		case WM_CREATE:
			/* 设置聚焦 */
			WM_SetFocus(hWin);
            _CreateButton((FRAME_WIDTH >> 1)-90, 230, 80,  40,hWin, GUI_ID_BUTTON0, "确认",0,0);
            _CreateButton((FRAME_WIDTH >> 1),    230, 80,  40, hWin, GUI_ID_BUTTON1,"取消",0,0);
            _CreateButton((FRAME_WIDTH >> 1)-90, 30, 70,  40,hWin,GUI_ID_BUTTON2,"工件左转",0,0);
            _CreateButton((FRAME_WIDTH >> 1),    30, 70,  40,hWin,GUI_ID_BUTTON3, "工件右转",0,0);
            _CreateButton((FRAME_WIDTH >> 1)-90, 80, 70,  40,hWin, GUI_ID_BUTTON4,"右转细调",0,0);
            _CreateButton((FRAME_WIDTH >> 1),    80, 70,  40,hWin, GUI_ID_BUTTON5,"右转粗调",0,0);
            _CreateButton((FRAME_WIDTH >> 1)-90, 130, 70,  40,hWin, GUI_ID_BUTTON6,"转速减少",0,0);
            _CreateButton((FRAME_WIDTH >> 1),    130, 70,  40,hWin, GUI_ID_BUTTON7,"转速增加",0,0);
			buf[0] = 4;
			break;
		 case WM_KEY:
			switch (((WM_KEY_INFO*)(pMsg->Data.p))->Key) 
			{ 
                   case GUI_KEY_TAB:
					WM_SetFocusOnNextChild(hWin);
					break;
			}
            break;
		case WM_PAINT:
			_PaintFrame();
			break;
        case WM_NOTIFY_PARENT:
			if (pMsg->Data.v == WM_NOTIFICATION_RELEASED) 
			{
				int Id = WM_GetId(pMsg->hWinSrc);
				switch (Id) 
				{
					case GUI_ID_BUTTON0:
                        _DeleteFrame();
						break;
					case GUI_ID_BUTTON1:
                        _DeleteFrame();
						break;
					case GUI_ID_BUTTON2:
						buf[13] = 1;
						break;
					case GUI_ID_BUTTON3:
						buf[13] = 2;
						break;
					case GUI_ID_BUTTON4:
						buf[14] = 1;
						break;
					case GUI_ID_BUTTON5:
						buf[14] = 2;
						break;  
					case GUI_ID_BUTTON6:
						buf[15] = 1;
						break;
					case GUI_ID_BUTTON7:
						buf[15] = 2;
						break;
				}
				NRF24L01_TX_Mode();
				NRF24L01_TxPacket(buf);
			}
			break;
		default:
		WM_DefaultProc(pMsg);
	}
}

/*
*********************************************************************************************************
*	函 数 名: _cbrundrill
*	功能说明: 第四个界面，执行界面和完整数据界面
*	形    参：pMsg  参数指针
*	返 回 值: 无
*********************************************************************************************************
*/
static void _cbrundrill(WM_MESSAGE* pMsg) 
{
	WM_HWIN hWin = pMsg->hWin;
	switch (pMsg->MsgId) 
	{
		case WM_CREATE:
			/* 设置聚焦 */
			WM_SetFocus(hWin);
            WM_CreateTimer(hWin,0,500,0);
            _CreateText((FRAME_WIDTH >> 1)-100 , 10,  65, 20, hWin, GUI_ID_TEXT0,"转动速度");
            _CreateText((FRAME_WIDTH >> 1)     , 10, 65, 20, hWin, GUI_ID_TEXT1,"钻孔速度");
            _CreateText((FRAME_WIDTH >> 1)-100 , 60, 65, 20, hWin, GUI_ID_TEXT2,"打孔次数");
            _CreateText((FRAME_WIDTH >> 1)     , 60, 65, 20, hWin, GUI_ID_TEXT3,"钻孔深度");
            _CreateText((FRAME_WIDTH >> 1)-100 , 110,  65, 20, hWin, GUI_ID_TEXT4,"孔数");
            _CreateText((FRAME_WIDTH >> 1)     , 110,  65, 20, hWin, GUI_ID_TEXT5,"扩孔深度");
            _CreateText((FRAME_WIDTH >> 1)-100 , 160,  65, 20, hWin, GUI_ID_TEXT6,"钻孔深度");
            _CreateText((FRAME_WIDTH >> 1)     , 160, 65, 20, hWin, GUI_ID_TEXT7,"模式");
            _CreateText((FRAME_WIDTH >> 1)-100 , 210, 65, 20, hWin, GUI_ID_TEXT8,"奇偶数排");
            _CreateText((FRAME_WIDTH >> 1)     , 210, 65, 20, hWin, GUI_ID_TEXT9,"大小钻头");
        
            _CreateEdit((FRAME_WIDTH >> 1)-100, 30, 65, 20, hWin, GUI_ID_EDIT0, 3,0);
            _CreateEdit((FRAME_WIDTH >> 1) ,    30, 65, 20, hWin, GUI_ID_EDIT1, 3,0);
            _CreateEdit((FRAME_WIDTH >> 1)-100, 80,65, 20, hWin, GUI_ID_EDIT2, 3,0);
            _CreateEdit((FRAME_WIDTH >> 1) ,    80, 65, 20, hWin, GUI_ID_EDIT3, 3,0);
            _CreateEdit((FRAME_WIDTH >> 1)-100, 130, 65, 20, hWin, GUI_ID_EDIT4, 3,0);
            _CreateEdit((FRAME_WIDTH >> 1) ,    130,65, 20, hWin, GUI_ID_EDIT5, 3,0);
            _CreateEdit((FRAME_WIDTH >> 1)-100, 180,65, 20, hWin, GUI_ID_EDIT6, 3,0);
        
            _CreateButton((FRAME_WIDTH >> 1)-90, 250, 80,  20,hWin, GUI_ID_BUTTON0, "确认",0,0);
            _CreateButton((FRAME_WIDTH >> 1), 250, 80,  20, hWin, GUI_ID_BUTTON1,"取消",0,0);
			break;
		 case WM_KEY:
			switch (((WM_KEY_INFO*)(pMsg->Data.p))->Key) 
			{ 
                   case GUI_KEY_TAB:
					WM_SetFocusOnNextChild(hWin);
					break;
			}
            break;
		case WM_PAINT:
			_PaintFrame();
			break;
        case WM_TIMER:
            NRF24L01_RX_Mode();
            NRF24L01_RxPacket(buf);
            Set_Data(hWin);
            WM_RestartTimer(pMsg->Data.v,500);
            break;
        case WM_NOTIFY_PARENT:
			if (pMsg->Data.v == WM_NOTIFICATION_RELEASED) 
			{
				int Id = WM_GetId(pMsg->hWinSrc);
				switch (Id) 
				{
					case GUI_ID_BUTTON0:
                        _DeleteFrame();
						break;
					case GUI_ID_BUTTON1:
                         _DeleteFrame();
						break;
				}
			}
			break;
		default:
		WM_DefaultProc(pMsg);
	}
}
/*
*********************************************************************************************************
*	函 数 名: _cbwireless
*	功能说明: 第三个界面，无线测试
*	形    参：pMsg  参数指针
*	返 回 值: 无
*********************************************************************************************************
*/
static void _cbwireless(WM_MESSAGE* pMsg) 
{
	WM_HWIN hWin = pMsg->hWin;
	switch (pMsg->MsgId) 
	{
		case WM_CREATE:
			/* 设置聚焦 */
			WM_SetFocus(hWin);
            _CreateButton((FRAME_WIDTH >> 1)-90, 230, 80,  40,hWin, GUI_ID_BUTTON0, "确认",0,0);
            _CreateButton((FRAME_WIDTH >> 1), 230, 80,  40, hWin, GUI_ID_BUTTON1,"取消",0,0);
            _CreateButton((FRAME_WIDTH >> 1)-90, 30, 120,  40, hWin, GUI_ID_BUTTON2, "模块检测",0,0);
            _CreateButton((FRAME_WIDTH >> 1)-90, 80, 120,  40, hWin, GUI_ID_BUTTON3,"数据传输检测",0,0);
		    buf[0] = 2;              //用于测试
			break;
		 case WM_KEY:
			switch (((WM_KEY_INFO*)(pMsg->Data.p))->Key) 
			{ 
                   case GUI_KEY_TAB:
					WM_SetFocusOnNextChild(hWin);
					break;
			}
            break;
		case WM_PAINT:
			_PaintFrame();
			break;
        case WM_NOTIFY_PARENT:
			if (pMsg->Data.v == WM_NOTIFICATION_RELEASED) 
			{
				int Id = WM_GetId(pMsg->hWinSrc);
				switch (Id) 
				{
					case GUI_ID_BUTTON0:
                        _DeleteFrame();
						break;
					case GUI_ID_BUTTON1:
                        _DeleteFrame();
						break;
                    case GUI_ID_BUTTON2:
                        while(NRF24L01_Check())
                        {
                            GUI_MessageBox("NRF24L01 error!","Error",0);
                        }
                        GUI_MessageBox("NRF24L01 Normal!","Normal",0);
						break;
                    case GUI_ID_BUTTON3:
                        NRF24L01_TX_Mode();
                        if(NRF24L01_TxPacket(buf)==TX_OK)
                        {
                            GUI_MessageBox("Send Data Successful","Normol",GUI_MESSAGEBOX_CF_MODAL);
                        }
                        else
                        {
                            GUI_MessageBox("Send Data failed","Error",GUI_MESSAGEBOX_CF_MODAL);
                        }
						break;
				}
			}
			break;
		default:
		WM_DefaultProc(pMsg);
	}
}

/*
*********************************************************************************************************
*	函 数 名: _cbSingledrill
*	功能说明: 第二个界面，单孔操作
*	形    参：pMsg  参数指针
*	返 回 值: 无
*********************************************************************************************************
*/
static void _cbSingledrill(WM_MESSAGE* pMsg) 
{
	WM_HWIN  hItem,hWin = pMsg->hWin;
	switch (pMsg->MsgId) 
	{
		case WM_CREATE:
			/* 设置聚焦 */
			WM_SetFocus(hWin);
			/* 创建两个按钮，用于选择中文和英文 */
            hItem = DROPDOWN_CreateEx((FRAME_WIDTH >> 1) - 90, 0, 80,  80, hWin, WM_CF_SHOW, 0, GUI_ID_DROPDOWN0);
            DROPDOWN_AddString(hItem,"M1");
            DROPDOWN_AddString(hItem,"M2");
            DROPDOWN_AddString(hItem,"M3");
            DROPDOWN_SetFont(hItem,&GUI_Font24B_ASCII);
			_CreateButton((FRAME_WIDTH >> 1)-90,90,  80,  40, hWin, GUI_ID_BUTTON2,"定位",0,0);
			_CreateButton((FRAME_WIDTH >> 1) ,  90,  80,  40, hWin, GUI_ID_BUTTON3,"扩孔",0,0);
            _CreateButton((FRAME_WIDTH >> 1)-90,160, 80,  40, hWin, GUI_ID_BUTTON4,"上升",0,0);
            _CreateButton((FRAME_WIDTH >> 1),   160, 80,  40, hWin, GUI_ID_BUTTON5,"下降",0,0);
        
            _CreateButton((FRAME_WIDTH >> 1)-90, 230, 80,  40,hWin, GUI_ID_BUTTON0, "确认",0,0);
            _CreateButton((FRAME_WIDTH >> 1),    230, 80,  40, hWin, GUI_ID_BUTTON1,"取消",0,0);
			buf[0] = 3;
			Set_widget_value(hWin,GUI_ID_DROPDOWN0,buf[2]);
			break;
		 case WM_KEY:
			switch (((WM_KEY_INFO*)(pMsg->Data.p))->Key) 
			{ 
                    case GUI_KEY_TAB:
                        WM_SetFocusOnNextChild(hWin);
					break;
			}
            break;
		case WM_PAINT:
			_PaintFrame();
			break;
        case WM_NOTIFY_PARENT:
			if (pMsg->Data.v == WM_NOTIFICATION_RELEASED) 
			{
				int Id = WM_GetId(pMsg->hWinSrc);
				switch (Id) 
				{
					case GUI_ID_BUTTON0:
						break;
					case GUI_ID_BUTTON1:
                         _DeleteFrame();
						break;
					
					case GUI_ID_BUTTON2:
						buf[16] = 1;
						break;
					case GUI_ID_BUTTON3:
						buf[16] = 2;
						break;
					case GUI_ID_BUTTON4:
						buf[17] = 1;
						break;
					case GUI_ID_BUTTON5:
						buf[17] = 2;
						break;  
				}
				NRF24L01_TX_Mode();
				NRF24L01_TxPacket(buf);
			}
			else if(pMsg->Data.v == WM_NOTIFICATION_SEL_CHANGED)
			{
				int Id = WM_GetId(pMsg->hWinSrc);
				switch (Id) 
				{
					case GUI_ID_DROPDOWN0:
                        buf[2] = Get_widget_value(hWin,GUI_ID_DROPDOWN0);
						break;
				}
			}
			break;
		default:
		WM_DefaultProc(pMsg);
	}
}


/*
*********************************************************************************************************
*	函 数 名: Input_Drill_Depth()
*	功能说明: 输入钻孔深度
*	返 回 值: 无
*********************************************************************************************************
*/
static void Input_Drill_Depth(WM_HWIN hWin)
{
    _Createradio((FRAME_WIDTH >> 1), 100, 80,70, hWin, GUI_ID_RADIO1,drill_Item,GUI_COUNTOF(drill_Item));      
    _CreateText((FRAME_WIDTH >> 1)-100 , 130, 80, 20, hWin,GUI_ID_TEXT2,"钻孔深度");
    _CreateEdit((FRAME_WIDTH >> 1)-100, 160, 80, 25, hWin, GUI_ID_EDIT2, 3,1);
}

/*
*********************************************************************************************************
*	函 数 名: Input_Enarge_Depth()
*	功能说明: 输入扩孔深度
*	返 回 值: 无
*********************************************************************************************************
*/
static void Input_Enarge_Depth(WM_HWIN hWin)
{
    _CreateText((FRAME_WIDTH >> 1)-100 , 70, 80, 20, hWin, GUI_ID_TEXT1,"扩孔深度");
    _CreateEdit((FRAME_WIDTH >> 1)-100, 100, 80, 25, hWin, GUI_ID_EDIT1, 3,1);
}
/*
*********************************************************************************************************
*	函 数 名: Input_Basice_Data()
*	功能说明: 输入孔数，奇偶数排
*	返 回 值: 无
*********************************************************************************************************
*/
static void Input_Basice_Data(WM_HWIN hWin)
{
    _CreateText((FRAME_WIDTH >> 1)-100 , 10, 80, 20, hWin,GUI_ID_TEXT0,"孔数");
    _CreateEdit((FRAME_WIDTH >> 1)-100 , 40, 80, 25, hWin, GUI_ID_EDIT0, 3,1);
    _Createradio((FRAME_WIDTH >> 1), 20, 80, 70, hWin, GUI_ID_RADIO0,   OddEven_Item,GUI_COUNTOF(OddEven_Item));
}
/*
*********************************************************************************************************
*	函 数 名: _cbInputdrillParameter
*	功能说明: 第一个界面，用于大小钻头、奇偶数排等参数的设定
*	形    参：pMsg  参数指针
*	返 回 值: 无
*********************************************************************************************************
*/
static void _cbInputdrillParameter(WM_MESSAGE* pMsg) 
{
	WM_HWIN  hItem,hWin = pMsg->hWin;
	switch (pMsg->MsgId) 
	{
		case WM_CREATE:
			/* 设置聚焦 */
			WM_SetFocus(hWin);
            _CreateButton((FRAME_WIDTH >> 1)-90, 230, 80,  40,hWin, GUI_ID_BUTTON0,"执行",0,0);
            _CreateButton((FRAME_WIDTH >> 1), 230, 80,  40, hWin, GUI_ID_BUTTON1,"取消",0,0);
            Input_Basice_Data(hWin);
            if(buf[1]==1)
            {
                Input_Enarge_Depth(hWin);
            }
            else if(buf[1]==2)
            {
                Input_Enarge_Depth(hWin);
                Input_Drill_Depth(hWin);
            }
            Set_Drill_Data(hWin);
			buf[0] = 0;              //用发送数据
			break;
		 case WM_KEY:
			switch (((WM_KEY_INFO*)(pMsg->Data.p))->Key) 
			{
                   case GUI_KEY_TAB:
					WM_SetFocusOnNextChild(hWin);
					break;
			}
            break;
		case WM_PAINT:
			_PaintFrame();
			break;
        case WM_NOTIFY_PARENT:
			if (pMsg->Data.v == WM_NOTIFICATION_RELEASED) 
			{
				int Id = WM_GetId(pMsg->hWinSrc);
				switch (Id) 
				{
					case GUI_ID_BUTTON0:
                        Get_Drill_Data(hWin);
                        NRF24L01_TX_Mode();
                        if(NRF24L01_TxPacket(buf)==TX_OK)
                        {
							_DeleteFrame();
							_CreateFrame(&_cbwait);
                        }
                        else
                        {
							_DeleteFrame();
                            GUI_MessageBox("Send Data failed","Error",GUI_MESSAGEBOX_CF_MODAL);
                        }   
						break;
					case GUI_ID_BUTTON1:
                        _DeleteFrame();
                        _CreateFrame(&_cbInputParameter);
						break;
				}
			}
			break;
		default:
		WM_DefaultProc(pMsg);
	}
}

/*
*********************************************************************************************************
*	函 数 名: _cbInputParameter
*	功能说明: 第一个界面，用于转速、深度等参数的设定
*	形    参：pMsg  参数指针
*	返 回 值: 无
*********************************************************************************************************
*/
static void _cbInputParameter(WM_MESSAGE* pMsg) 
{
	WM_HWIN  hWin = pMsg->hWin;
	switch (pMsg->MsgId) 
	{
		case WM_CREATE:
			/* 设置聚焦 */
			WM_SetFocus(hWin);
            _CreateText((FRAME_WIDTH >> 1)-100 , 10, 80, 20, hWin, GUI_ID_TEXT0,"转动速度");
            _CreateText((FRAME_WIDTH >> 1)-100, 70,  80, 20, hWin, GUI_ID_TEXT1,"钻孔速度");
            _CreateText((FRAME_WIDTH >> 1)-100, 130,  80, 20, hWin, GUI_ID_TEXT2,"打孔次数");
            _CreateText((FRAME_WIDTH >> 1)-100, 190, 80, 20, hWin, GUI_ID_TEXT3,"钻孔深度");
            _CreateText((FRAME_WIDTH >> 1), 10, 80, 20, hWin, GUI_ID_TEXT4,"模式选择");


            _CreateEdit((FRAME_WIDTH >> 1)-100, 40,  80, 25, hWin, GUI_ID_EDIT0, 3,1);
            _CreateEdit((FRAME_WIDTH >> 1)-100, 100,  80, 25, hWin, GUI_ID_EDIT1, 3,1);
            _CreateEdit((FRAME_WIDTH >> 1)-100, 160,  80, 25, hWin, GUI_ID_EDIT2, 3,1);
            _CreateEdit((FRAME_WIDTH >> 1)-100, 220, 80, 25, hWin, GUI_ID_EDIT3, 3,1);
            _Createradio((FRAME_WIDTH >> 1), 50, 80,80, hWin, GUI_ID_RADIO0,model_Item,GUI_COUNTOF(model_Item));
           
            Set_User_Data(hWin);
            _CreateButton((FRAME_WIDTH >> 1), 160, 80,  40,hWin, GUI_ID_BUTTON0, "设置",0,0);
            _CreateButton((FRAME_WIDTH >> 1), 210, 80,  40, hWin, GUI_ID_BUTTON1,"取消",0,0);
			break;
		 case WM_KEY:
			switch (((WM_KEY_INFO*)(pMsg->Data.p))->Key) 
			{ 
                   case GUI_KEY_TAB:
                        WM_SetFocusOnNextChild(hWin);
                    break;
			}
            break;
		case WM_PAINT:
			_PaintFrame();
			break;
         case WM_NOTIFY_PARENT:
			if (pMsg->Data.v == WM_NOTIFICATION_RELEASED) 
			{
				int Id = WM_GetId(pMsg->hWinSrc);
				switch (Id) 
				{
					case GUI_ID_BUTTON0:
                        Get_User_Data(hWin);
                        _DeleteFrame();
                        _CreateFrame(&_cbInputdrillParameter);
						break;
					case GUI_ID_BUTTON1:
                        _DeleteFrame();
						break;
				}
			}
			break;
		default:
		WM_DefaultProc(pMsg);
	}
}

/*
*********************************************************************************************************
*	函 数 名: _cbSelect
*	功能说明: 主界面用作功能的选择
*	形    参：pMsg  参数指针
*	返 回 值: 无
*********************************************************************************************************
*/
static void _cbSelect(WM_MESSAGE* pMsg) 
{
	WM_HWIN hWin = pMsg->hWin;
    int sel;
	switch (pMsg->MsgId) 
	{
		case WM_CREATE:
			/* 设置聚焦 */
			WM_SetFocus(hWin);
            _CreateIcon(20,0,FRAME_WIDTH,FRAME_HEIGHT,hWin,GUI_ID_ICONVIEW0); 
			break;
		 case WM_KEY:
			switch (((WM_KEY_INFO*)(pMsg->Data.p))->Key) 
			{ 
                case GUI_KEY_TAB:
					WM_SetFocusOnNextChild(hWin);
					break;
			}
            break;
		case WM_PAINT:
			_PaintFrame();
			break;
        case WM_NOTIFY_PARENT:
			if (pMsg->Data.v == WM_NOTIFICATION_RELEASED) 
			{
				int Id = WM_GetId(pMsg->hWinSrc);
				switch (Id) 
				{
                    case GUI_ID_ICONVIEW0:
                        sel = ICONVIEW_GetSel(pMsg->hWinSrc);
                        if(sel < GUI_COUNTOF(_aBitmapItem))
						{
                            /* 进入相应的应用程序 */
                            _CreateFrame(_apModules[sel]);
						}
                        break;
				}
			}
			break;
		default:
		WM_DefaultProc(pMsg);
	}
}

void CreateFramewin(void) {
    
	/* 使能窗口使用内存设备 */
	WM_SetCreateFlags(WM_CF_MEMDEV);
    
	/* 使能控件的皮肤色 */
	PROGBAR_SetDefaultSkin(PROGBAR_SKIN_FLEX);
	FRAMEWIN_SetDefaultSkin(FRAMEWIN_SKIN_FLEX);
	PROGBAR_SetDefaultSkin(PROGBAR_SKIN_FLEX);
	BUTTON_SetDefaultSkin(BUTTON_SKIN_FLEX);
	CHECKBOX_SetDefaultSkin(CHECKBOX_SKIN_FLEX);
	DROPDOWN_SetDefaultSkin(DROPDOWN_SKIN_FLEX);
	SCROLLBAR_SetDefaultSkin(SCROLLBAR_SKIN_FLEX);
	SLIDER_SetDefaultSkin(SLIDER_SKIN_FLEX);
	HEADER_SetDefaultSkin(HEADER_SKIN_FLEX);
	RADIO_SetDefaultSkin(RADIO_SKIN_FLEX);
	
	Welcome_page();
	
	/*设置桌面窗口回调*/
	WM_SetCallback(WM_HBKWIN,&_cbBkWindow);
	_CreateFrame(&_cbSelect);
	
	GUI_UC_SetEncodeUTF8();
}


/*************************** End of file ****************************/
