/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "key.h"
#include "stdio.h"
#include "stdlib.h" 
#include "led.h"
#include "string.h"
#include "24L01.h"
#include "touch.h"
#include "FramewinDLG.h"

extern GUI_CONST_STORAGE GUI_BITMAP bmwireless;
extern GUI_CONST_STORAGE GUI_BITMAP bmsinglemotion;
extern GUI_CONST_STORAGE GUI_BITMAP bminput;
extern GUI_CONST_STORAGE GUI_BITMAP bmCheck;
extern GUI_CONST_STORAGE GUI_BITMAP bmringmold;

extern GUI_CONST_STORAGE GUI_BITMAP bmsetup;

extern GUI_CONST_STORAGE GUI_BITMAP bmcolthes;
extern GUI_CONST_STORAGE GUI_BITMAP bmbattry;
extern GUI_CONST_STORAGE GUI_BITMAP bmreturn;
extern GUI_CONST_STORAGE GUI_BITMAP bmwifi;
extern GUI_CONST_STORAGE GUI_BITMAP bmyes;
extern GUI_CONST_STORAGE GUI_BITMAP bmdel;

extern GUI_CONST_STORAGE GUI_FONT GUI_Fontfont12;
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontfont14;
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontfont16;
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontfont24;



#define MAIN_BKCOLOR              0xD0D0D0
#define MAIN_TEXTCOLOR            GUI_DARKGRAY
#define MAIN_FONT                 (&GUI_Fontfont16)

#define FRAME_FONT                (&GUI_Fontfont12)
#define FRAME_EFFECT              (&WIDGET_Effect_None)
#define FRAME_BORDER              FRAME_EFFECT->EffectSize
#define FRAME_WIDTH               (LCD_GetXSize() - (FRAME_BORDER * 2))
#define FRAME_HEIGHT              (LCD_GetYSize() - (FRAME_BORDER * 2))


#define DEFAULT_WIDGET_EFFECT     (&WIDGET_Effect_None)

#define MSG_SEND_DATA (WM_USER + 5)
#define GUI_ID_BUTTON_YES (GUI_ID_USER + 0x00)
#define GUI_ID_BUTTON_DEL (GUI_ID_USER + 0X01)
#define GUI_ID_BUTTON_RETURN (GUI_ID_USER + 0X02)


#define MAX_HOLE 50 //最大孔数
#define MAX_REAMING 20 //最大扩孔深度
#define MAX_DRILLING 20//最大钻孔深度


static void _cbSelect(WM_MESSAGE* pMsg) ;
static void _cbInputParameter(WM_MESSAGE* pMsg) ;
static void _cbwireless(WM_MESSAGE* pMsg) ;
static void _cbSingledrill(WM_MESSAGE* pMsg) ;
static void _cbrundrill(WM_MESSAGE* pMsg) ;
static void _cbringmold(WM_MESSAGE* pMsg) ;
static void _cbSetup(WM_MESSAGE* pMsg) ;
static void _cbkeypad(WM_MESSAGE* pMsg) ;
void Welcome_page(void);
void Wait_page(void);

static WM_HWIN    _hCurrentFrame;
static WM_HWIN    _hKeypadFrame;

u8 buf[32];
int PROGBAR_Value = 1;
int edit_id = 0;
int parameter_flag = 0;
u8 flex_index = 0 ; 
u8 PROGBAR_Max  = 0;
extern volatile u8 RT_flag;
BUTTON_SKINFLEX_PROPS BUTTON_FLAT_FLEX;
DROPDOWN_SKINFLEX_PROPS DROPDOWN_FLAT_FLEX;
PROGBAR_SKINFLEX_PROPS PROGBAR_FLAT_FLEX;
RADIO_SKINFLEX_PROPS RADIO_FLAT_FLEX;
U32 FRAME_TEXTCOLOR = GUI_BLACK;

/* ICONVIEW控件图标使用 */

typedef struct {
  const GUI_BITMAP * pBitmap;  
  const char       * pText;
} BITMAP_ITEM;


char model_Item[][10]={
    "定位",
    "扩孔",
    "钻孔"
};

char drill_Item[][10]={
    "大钻头",
    "小钻头"
};
char OddEven_Item[][10]={
    "奇数排",
    "偶数排"
};

static const BITMAP_ITEM _aBitmapItem[] = {
    {&bminput,          "输入参数"       },
    {&bmsinglemotion,   "电机操作"     },
    {&bmwireless,       "无线测试"        },
	{&bmCheck   ,   "检测"        },
    {&bmringmold,      "环模操作"        },
    {&bmsetup,  	 "设置"          }
};
/* 图标对应的应用程序 */
static void (* _apModules[6])(WM_MESSAGE* pMsg) = 
{
	_cbInputParameter,
    _cbSingledrill,
    _cbwireless,
    _cbrundrill,
    _cbringmold,
    _cbSetup,
};


/*
*********************************************************************************************************
*	函 数 名: _DeleteFrame
*	功能说明: 删除创建的框架窗口
*	形    参：无
*	返 回 值: 无
*********************************************************************************************************
*/
static void _DeleteFrame(void) 
{
	WM_DeleteWindow(_hCurrentFrame);
	_hCurrentFrame = 0;
}


/*
*********************************************************************************************************
*	函 数 名: _CreateFrame
*	功能说明: 创建框架窗口
*	形    参：cb  回调函数地址
*	返 回 值: 无
*********************************************************************************************************
*/
static WM_HWIN _CreateFrame(WM_CALLBACK* cb) 
{
	int x = 0;
	int y = 0;
	x = FRAME_BORDER ;
	y = FRAME_BORDER ;
	_hCurrentFrame = WM_CreateWindowAsChild(x, y, FRAME_WIDTH, FRAME_HEIGHT, WM_HBKWIN, WM_CF_SHOW, cb, 0);
	return _hCurrentFrame;
}


static void _SendKeyvalue(WM_HWIN hWin, char *pStr)
{
    WM_MESSAGE Message;
    Message.MsgId =  MSG_SEND_DATA;
    Message.Data.p = pStr;
    WM_SendMessage(hWin,&Message);
}


static void Set_text_value(GUI_HWIN hWin,int id,u8 value,const char pText[][10])
{
    WM_HWIN hItem;
    WM_CALLBACK *pCb;
    hItem = WM_GetDialogItem(hWin, id);
    pCb = WM_GetCallback(hItem);
    if(pCb == TEXT_Callback)
    {
        TEXT_SetText(hItem,pText[value]);
    }
    
}

static void Set_widget_value(GUI_HWIN hWin,int id,u8 value)
{
    char tmp[10];
    WM_HWIN hItem;
    WM_CALLBACK *pCb;
    hItem = WM_GetDialogItem(hWin, id);
    pCb = WM_GetCallback(hItem);
    if(pCb == DROPDOWN_Callback)
    {    
         DROPDOWN_SetSel(hItem,value);
    }
    else if(pCb == EDIT_Callback&&value != 0)
    {
        sprintf(tmp,"%u",value);
        EDIT_SetText(hItem,tmp);
    }
    else if(pCb == RADIO_Callback)
    {
        RADIO_SetValue(hItem,value);
    }
}

static u8 Get_widget_value(GUI_HWIN hWin,int id)
{
    char tmp[4];
    WM_HWIN hItem;
    WM_CALLBACK *pCb;
    hItem = WM_GetDialogItem(hWin, id);
    pCb = WM_GetCallback(hItem);
    if(pCb == RADIO_Callback)
    {    
        return RADIO_GetValue(hItem);
    }
    else if(pCb == DROPDOWN_Callback)
    {
        return DROPDOWN_GetSel(hItem);
    }
    else if(pCb == EDIT_Callback)
    {
        EDIT_GetText(hItem,tmp,4);
		return (u8)atoi(tmp);
    }

}

void Get_User_Data(GUI_HWIN hWin)
{
    buf[1] = Get_widget_value(hWin,GUI_ID_RADIO0);//模式
}

void Set_User_Data(GUI_HWIN hWin)
{
    Set_widget_value(hWin,GUI_ID_RADIO0,buf[1]);
}

void Get_Drill_Data(GUI_HWIN hWin)
{
    buf[4] = Get_widget_value(hWin,GUI_ID_EDIT0);
    buf[5] = Get_widget_value(hWin,GUI_ID_RADIO0);
	buf[6] = 0;
	buf[7] = 0;
	buf[8] = 0;
    if(buf[1]==1)
    {
        buf[6] = Get_widget_value(hWin,GUI_ID_EDIT1);  
		buf[7] = 0;
		buf[8] = 0;
    }
    else if(buf[1]==2)
    {
        buf[6] = Get_widget_value(hWin,GUI_ID_EDIT1);  
        buf[7] = Get_widget_value(hWin,GUI_ID_EDIT2);
        buf[8] = Get_widget_value(hWin,GUI_ID_RADIO1);
    }
}

void Set_Drill_Data(GUI_HWIN hWin)
{
	
    Set_widget_value(hWin,GUI_ID_EDIT0,buf[4]);
    Set_widget_value(hWin,GUI_ID_RADIO0,buf[5]);
    if(buf[1]==1)
    {
        Set_widget_value(hWin,GUI_ID_EDIT1,buf[6]);  
    }
    else if(buf[1]==2)
    {
        Set_widget_value(hWin,GUI_ID_EDIT1 ,buf[6]);  
        Set_widget_value(hWin,GUI_ID_EDIT2 ,buf[7]);
        Set_widget_value(hWin,GUI_ID_RADIO1,buf[8]);
    }
}

void Set_Data(GUI_HWIN hWin)
{
    Set_text_value(hWin,GUI_ID_TEXT5,buf[1],model_Item); //模式
	
    Set_widget_value(hWin,GUI_ID_EDIT2,buf[4]);//孔数
    Set_text_value(hWin,GUI_ID_TEXT6,buf[5],OddEven_Item);  //奇偶数排
    Set_widget_value(hWin,GUI_ID_EDIT3,buf[6]);//扩孔深度
	Set_widget_value(hWin,GUI_ID_EDIT4,buf[7]);//钻孔深度
    Set_text_value(hWin,GUI_ID_TEXT7,buf[8],drill_Item); //大小钻头
	Set_widget_value(hWin,GUI_ID_EDIT0,buf[9]);//转动速度
	Set_widget_value(hWin,GUI_ID_EDIT1,buf[10]);//钻孔速度
	
}
static void Input_Check(GUI_HWIN hWin,int id)
{
	WM_HWIN hItem;
	char tmp[4];
	hItem = WM_GetDialogItem(hWin, id);
	edit_id = id;
	EDIT_GetText(hItem,tmp,4);
	if(!strcmp(tmp,"err"))
	{
		EDIT_SetText(hItem,"");
	}
	_hKeypadFrame = WM_CreateWindowAsChild((FRAME_WIDTH>>1)-125, 170, 40*6, 30*2+10, hWin, WM_CF_SHOW, _cbkeypad, 0);
	WM_MakeModal(_hKeypadFrame);
}
static void Parameter_Check(GUI_HWIN hWin,int id)
{
	WM_HWIN hItem;
	Get_Drill_Data(hWin);
	hItem = WM_GetDialogItem(hWin, id);
	parameter_flag = 0;
	switch(buf[1])
	{
		//钻孔
		case 2:
			if(buf[7]<=0||buf[7]>MAX_DRILLING)
			{
				EDIT_SetText(hItem,"err");
				parameter_flag = 1;
			}
		//扩孔
		case 1:
			if(buf[6]<=0||buf[6]>MAX_REAMING)
			{
				EDIT_SetText(hItem,"err");
				parameter_flag = 1;
			}
		//定位
		case 0:    
			if(buf[4]<=0||buf[4]>MAX_HOLE)
			{
				EDIT_SetText(hItem,"err");
				parameter_flag = 1;
			}
			break;
	}
	
}

static void Button_Set_flat(U32 color1, U32 color2)
{
	BUTTON_GetSkinFlexProps(&BUTTON_FLAT_FLEX,BUTTON_SKINFLEX_PI_ENABLED);
	BUTTON_FLAT_FLEX.aColorFrame[0]	= color1;
	BUTTON_FLAT_FLEX.aColorFrame[1]	= color1;
	BUTTON_FLAT_FLEX.aColorFrame[2]	= color1;
	BUTTON_FLAT_FLEX.aColorLower[0]	= color1;
	BUTTON_FLAT_FLEX.aColorLower[1]	= color1;
	BUTTON_FLAT_FLEX.aColorUpper[0]	= color1;
	BUTTON_FLAT_FLEX.aColorUpper[1]	= color1;
	BUTTON_SetSkinFlexProps(&BUTTON_FLAT_FLEX,BUTTON_SKINFLEX_PI_ENABLED);
	BUTTON_SetSkinFlexProps(&BUTTON_FLAT_FLEX,BUTTON_SKINFLEX_PI_FOCUSSED);
	BUTTON_FLAT_FLEX.aColorFrame[0]	= color2;
	BUTTON_FLAT_FLEX.aColorFrame[1]	= color2;
	BUTTON_FLAT_FLEX.aColorFrame[2]	= color2;
	BUTTON_FLAT_FLEX.aColorLower[0]	= color2;
	BUTTON_FLAT_FLEX.aColorLower[1]	= color2;
	BUTTON_FLAT_FLEX.aColorUpper[0]	= color2;
	BUTTON_FLAT_FLEX.aColorUpper[1]	= color2;
	BUTTON_SetSkinFlexProps(&BUTTON_FLAT_FLEX,BUTTON_SKINFLEX_PI_PRESSED);
}

static void Dropdwon_Set_flat(U32 color1, U32 color2)
{
	DROPDOWN_GetSkinFlexProps(&DROPDOWN_FLAT_FLEX,DROPDOWN_SKINFLEX_PI_ENABLED);
	DROPDOWN_FLAT_FLEX.aColorFrame[0]	= color1;
	DROPDOWN_FLAT_FLEX.aColorFrame[1]	= color1;
	DROPDOWN_FLAT_FLEX.aColorFrame[2]	= color1;
	DROPDOWN_FLAT_FLEX.aColorLower[0]	= color1;
	DROPDOWN_FLAT_FLEX.aColorLower[1]	= color1;
	DROPDOWN_FLAT_FLEX.aColorUpper[0]	= color1;
	DROPDOWN_FLAT_FLEX.aColorUpper[1]	= color1;
	DROPDOWN_SetSkinFlexProps(&DROPDOWN_FLAT_FLEX,DROPDOWN_SKINFLEX_PI_ENABLED);
	DROPDOWN_SetSkinFlexProps(&DROPDOWN_FLAT_FLEX,DROPDOWN_SKINFLEX_PI_FOCUSSED);
	DROPDOWN_FLAT_FLEX.aColorFrame[0]	= color2;
	DROPDOWN_FLAT_FLEX.aColorFrame[1]	= color2;
	DROPDOWN_FLAT_FLEX.aColorFrame[2]	= color2;
	DROPDOWN_FLAT_FLEX.aColorLower[0]	= color2;
	DROPDOWN_FLAT_FLEX.aColorLower[1]	= color2;
	DROPDOWN_FLAT_FLEX.aColorUpper[0]	= color2;
	DROPDOWN_FLAT_FLEX.aColorUpper[1]	= color2;
	DROPDOWN_SetSkinFlexProps(&DROPDOWN_FLAT_FLEX,DROPDOWN_SKINFLEX_PI_EXPANDED);
}


static void Progbar_Set_flat(U32 color1, U32 color2)
{
	PROGBAR_GetSkinFlexProps(&PROGBAR_FLAT_FLEX,0);
	PROGBAR_FLAT_FLEX.aColorLowerL[0]	= color1;
	PROGBAR_FLAT_FLEX.aColorLowerL[1]	= color1;
	PROGBAR_FLAT_FLEX.aColorUpperL[0]	= color1;
	PROGBAR_FLAT_FLEX.aColorUpperL[1]	= color1;
	PROGBAR_FLAT_FLEX.aColorLowerR[0]	= color2;
	PROGBAR_FLAT_FLEX.aColorLowerR[1]	= color2;
	PROGBAR_FLAT_FLEX.aColorUpperR[0]	= color2;
	PROGBAR_FLAT_FLEX.aColorUpperR[1]	= color2;
	PROGBAR_SetSkinFlexProps(&PROGBAR_FLAT_FLEX,0);
}

static void Radio_Set_flat(U32 color1, U32 color2, U32 color3)
{
	RADIO_GetSkinFlexProps(&RADIO_FLAT_FLEX,RADIO_SKINFLEX_PI_PRESSED);
	RADIO_FLAT_FLEX.aColorButton[0]	= color1;
	RADIO_FLAT_FLEX.aColorButton[1]	= color1;
	RADIO_FLAT_FLEX.aColorButton[2]	= color1;
	RADIO_FLAT_FLEX.aColorButton[3]	= color2;
	RADIO_FLAT_FLEX.ButtonSize = 12;
	RADIO_SetSkinFlexProps(&RADIO_FLAT_FLEX,RADIO_SKINFLEX_PI_PRESSED);
	RADIO_FLAT_FLEX.aColorButton[0]	= color1;
	RADIO_FLAT_FLEX.aColorButton[1]	= color1;
	RADIO_FLAT_FLEX.aColorButton[2]	= color1;
	RADIO_FLAT_FLEX.aColorButton[3]	= color3;
	RADIO_FLAT_FLEX.ButtonSize = 12;
	RADIO_SetSkinFlexProps(&RADIO_FLAT_FLEX,RADIO_SKINFLEX_PI_UNPRESSED);
}

/*
*********************************************************************************************************
*	函 数 名: _cbButtonText
*	功能说明: 按钮回调函数
*	形    参: pMsg  消息指针
*	返 回 值: 无
*********************************************************************************************************
*/
static void _cbButtonText(WM_MESSAGE * pMsg) 
{
	char str[4];
	WM_HWIN  hWin;
	GUI_RECT Rect;
	hWin  = pMsg->hWin;

	switch (pMsg->MsgId) 
	{
		case WM_PAINT:
			WM_GetClientRect(&Rect);
			BUTTON_GetUserData(hWin,str,sizeof(str));
			if (BUTTON_IsPressed(hWin)) 
			{
				GUI_SetColor(GUI_DARKGRAY);
				GUI_FillRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, 5);
				GUI_SetBkColor(GUI_DARKGRAY);
				GUI_SetColor(GUI_WHITE); 
			} 
			else 
			{
				GUI_SetColor(GUI_LIGHTBLUE);
				GUI_FillRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, 5);
				GUI_SetBkColor(GUI_LIGHTBLUE);
				GUI_SetColor(GUI_WHITE);   
			}
			GUI_SetFont(&GUI_Font16_ASCII);
			GUI_DispStringInRect(str, &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
			break;
			
		default:
			BUTTON_Callback(pMsg);
	}
}

/*
*********************************************************************************************************
*	函 数 名: _cbButtonPic
*	功能说明: 按钮回调函数
*	形    参: pMsg  消息指针
*	返 回 值: 无
*********************************************************************************************************
*/
static void _cbButtonPic(WM_MESSAGE * pMsg) 
{
	WM_HWIN  hWin;
	GUI_BITMAP bmstr;
	hWin  = pMsg->hWin;
	switch (pMsg->MsgId) 
	{
		
		case WM_PAINT:
			BUTTON_GetUserData(hWin,&bmstr,sizeof(GUI_BITMAP));
			if (BUTTON_IsPressed(hWin)) 
			{
				GUI_SetBkColor(GUI_WHITE);
				GUI_SetAlpha(0xb0);
				GUI_DrawBitmap(&bmstr, 0, 0);
				GUI_SetAlpha(0);		
			} 
			else 
			{
				GUI_DrawBitmap(&bmstr, 0, 0);		
			}
			break;
			
		default:
			BUTTON_Callback(pMsg);
	}
}

/*
*********************************************************************************************************
*	函 数 名: _DrawDownRectEx
*	功能说明: 显示凹陷的矩形框
*	形    参：pEffect  控件显示效果
*             pRect    GUI_RECT类型变量地址
*	返 回 值: 无
*********************************************************************************************************
*/
static void _DrawDownRectEx(const WIDGET_EFFECT* pEffect, const GUI_RECT* pRect) 
{
	WM_LOCK();
	pEffect->pfDrawDownRect(pRect);
	WM_UNLOCK();
}

/*
*********************************************************************************************************
*	函 数 名: _DrawDownRect
*	功能说明: 显示凹陷的矩形框
*	形    参：pEffect  控件显示效果
*             x0       起始x轴坐标
*             y0       起始y轴坐标
*             x1       结束x轴坐标
*             y1       结束y轴坐标
*	返 回 值: 无
*********************************************************************************************************
*/
static void _DrawDownRect(const WIDGET_EFFECT* pEffect, int x0, int y0, int x1, int y1) 
{
	GUI_RECT r;
	r.x0 = x0;
	r.y0 = y0;
	r.x1 = x1;
	r.y1 = y1;
	_DrawDownRectEx(pEffect, &r);
}

/*
*********************************************************************************************************
*	函 数 名: _CreateUserButton
*	功能说明: 创建按钮
*	形    参：
*             x        x轴坐标
*             y        y轴坐标
*             w        按钮宽
*             h        按钮高
*             hParent  父窗口     
*             Id       按钮Id   
*             pDest    缓冲区指针
*			  NumByte  字节数
*             _cbButton 回调函数
*	返 回 值: 无
*********************************************************************************************************
*/
static WM_HWIN _CreateUserButton(int x, int y, int w, int h, WM_HWIN hParent, int Id, const void *pDest,int NumBytes, WM_CALLBACK *_cbButton) 
{
	WM_HWIN hButton;
	hButton = BUTTON_CreateUser(x, y, w, h, hParent, WM_CF_SHOW, 0, Id, NumBytes);
	BUTTON_SetUserData(hButton,pDest,NumBytes);
	WM_SetHasTrans(hButton);
	WM_SetCallback(hButton, _cbButton);
	BUTTON_SetFocussable(hButton,    0);
	return hButton;
}

/*
*********************************************************************************************************
*	函 数 名: _CreateButton
*	功能说明: 创建按钮
*	形    参：
*             x        x轴坐标
*             y        y轴坐标
*             w        按钮宽
*             h        按钮高
*             hParent  父窗口     
*             Id       按钮Id   
*             pText    按键上显示的文本
*	返 回 值: 无
*********************************************************************************************************
*/
static WM_HWIN _CreateButton(int x, int y, int w, int h, WM_HWIN hParent, int Id, const char* pText) 
{
	WM_HWIN hButton;
	hButton = BUTTON_CreateEx(x, y, w, h, hParent, WM_CF_SHOW, 0, Id);

	BUTTON_SetFont      (hButton,    &GUI_Fontfont12);
	BUTTON_SetText(hButton,pText);
	BUTTON_SetTextColor(hButton,0,FRAME_TEXTCOLOR);
	
	/* 设置接收输入焦点的能力 */
	BUTTON_SetFocussable(hButton,    0);
	return hButton;
}


/*
*********************************************************************************************************
*	函 数 名: _CreateIcon
*	功能说明: 创建图标
*	形    参：      
*             x        x轴坐标
*             y        y轴坐标
*             w        按钮宽
*             h        按钮高   
*             hParent  父窗口
*             Id       按钮Id   
*********************************************************************************************************
*/
static WM_HWIN _CreateIcon( int x, int y, int w, int h,WM_HWIN hParent,int Id) 
{
    int i;
    WM_HWIN hIcon;
	/* 创建ICON控件 */
	hIcon = ICONVIEW_CreateEx(x, y, w, h, hParent, WM_CF_SHOW | WM_CF_HASTRANS,ICONVIEW_CF_AUTOSCROLLBAR_V ,
							  Id, 65, 80);
	ICONVIEW_SetFont(hIcon, &GUI_Fontfont12);
	ICONVIEW_SetBkColor(hIcon, ICONVIEW_CI_SEL, 0x941000 | 0xA0404040);
	ICONVIEW_SetIconAlign(hIcon,ICONVIEW_IA_TOP);
	ICONVIEW_SetSpace(hIcon, GUI_COORD_Y, 20);
	ICONVIEW_SetSpace(hIcon, GUI_COORD_X, 30);
	for (i = 0; i < GUI_COUNTOF(_aBitmapItem); i++)
	{
        
		ICONVIEW_AddBitmapItem(hIcon,_aBitmapItem[i].pBitmap, _aBitmapItem[i].pText);
	}
	WM_SetFocus(hIcon);
    return hIcon;
}

/*
*********************************************************************************************************
*	函 数 名: _CreateText
*	功能说明: 创建文本
*	形    参：      
*             x        x轴坐标
*             y        y轴坐标
*             w        按钮宽
*             h        按钮高   
*             hParent  父窗口
*             Id       Id   
*             pText    字符串
*********************************************************************************************************
*/
static void _CreateText( int x, int y, int w, int h,WM_HWIN hParent,int Text_Id,const char* pText) 
{
    WM_HWIN hText;
    hText = TEXT_CreateEx(x, y, w, h, hParent, WM_CF_SHOW, 0, Text_Id, pText);
    TEXT_SetFont(hText,FRAME_FONT);
	TEXT_SetTextColor(hText,FRAME_TEXTCOLOR);
} 
/*
*********************************************************************************************************
*	函 数 名: _CreateEdit
*	功能说明: 创建编辑框
*	形    参：      
*             x        x轴坐标
*             y        y轴坐标
*             w        按钮宽
*             h        按钮高   
*             hParent  父窗口
*             Id       Id   
*             maxlen   最大字符数
*             focus    输入焦点
*********************************************************************************************************
*/
static WM_HWIN _CreateEdit( int x, int y, int w, int h,WM_HWIN hParent,int Edit_Id,int maxLen,int focus) 
{
	WM_HWIN hEdit;
    hEdit = EDIT_CreateEx( x, y, w, h, hParent, WM_CF_SHOW, 0, Edit_Id, maxLen);
    EDIT_SetFont(hEdit,GUI_FONT_20B_ASCII);
    EDIT_SetTextAlign(hEdit, GUI_TA_CENTER);
    WIDGET_SetEffect(hEdit, DEFAULT_WIDGET_EFFECT);
    
	/* 设置接收输入焦点的能力 */
	EDIT_SetFocussable(hEdit,focus);
	return hEdit;
}


/*
*********************************************************************************************************
*	函 数 名: _Createradio
*	功能说明: 创建单选框
*	形    参：      
*             x        x轴坐标
*             y        y轴坐标
*             w        按钮宽
*             h        按钮高   
*             hParent  父窗口
*             Id       Id   
*             pText    字符串
*             num      字符个数
*********************************************************************************************************
*/
static WM_HWIN _Createradio( int x, int y, int w, int h,WM_HWIN hParent,int Id, const char pText[2][10],int num) 
{
	WM_HWIN hRadio;
    int i=0;
    hRadio = RADIO_CreateEx(x,y,w,h,hParent,WM_CF_SHOW,0,Id,num,30);
    RADIO_SetFont(hRadio,FRAME_FONT);
	RADIO_SetTextColor(hRadio,FRAME_TEXTCOLOR);
    for(i=0;i<num;i++)
    {
        RADIO_SetText(hRadio,*(pText+i),i);
    }
	return hRadio;
}

/*
*********************************************************************************************************
*	函 数 名: _cbBkWindow
*	功能说明: 桌面窗口回调函数
*	形    参：pMsg  参数指针
*	返 回 值: 无
*********************************************************************************************************
*/
static void _cbBkWindow(WM_MESSAGE* pMsg) 
{
	switch (pMsg->MsgId) 
	{
		case WM_PAINT: 
			{
			} 
			break;
		default:
			WM_DefaultProc(pMsg);
	}
}
/*
*********************************************************************************************************
*	函 数 名: _Paintkeypad
*	功能说明: keypad框架窗口的重绘函数
*	形    参：无
*	返 回 值: 无
*********************************************************************************************************
*/
static void _Paintkeypad(void) 
{
	GUI_SetBkColor(GUI_LIGHTGRAY);
	GUI_Clear();
}
/*
*********************************************************************************************************
*	函 数 名: _PaintFrame
*	功能说明: 框架窗口的重绘函数
*	形    参：无
*	返 回 值: 无
*********************************************************************************************************
*/
static void _PaintFrame(void) 
{

	switch(flex_index)
	{
		case 0: 
			GUI_DrawGradientH(0, 0, LCD_GetXSize()-1, LCD_GetYSize(), 0xbebab7, 0x635548);
			Button_Set_flat(GUI_LIGHTGRAY,GUI_LIGHTBLUE);
			Dropdwon_Set_flat(GUI_LIGHTGRAY,GUI_LIGHTBLUE);
			Progbar_Set_flat(GUI_GREEN,GUI_LIGHTGRAY);
			Radio_Set_flat(GUI_LIGHTGRAY,GUI_BLACK,GUI_WHITE);
		break;
		case 1:
			GUI_DrawGradientH(0, 0, LCD_GetXSize()-1, LCD_GetYSize(), 0xf7b691, 0xf79191);
			Button_Set_flat(GUI_LIGHTGRAY,GUI_LIGHTBLUE);
			Dropdwon_Set_flat(GUI_LIGHTGRAY,GUI_LIGHTBLUE);
			Progbar_Set_flat(GUI_GREEN,GUI_LIGHTGRAY);
			Radio_Set_flat(GUI_LIGHTGRAY,GUI_BLACK,GUI_WHITE);
			break;
		case 2:
			GUI_DrawGradientH(0, 0, LCD_GetXSize()-1, LCD_GetYSize(), 0xdda0dd, 0xe14159);
			Button_Set_flat(GUI_LIGHTGRAY,GUI_LIGHTBLUE);
			Dropdwon_Set_flat(GUI_LIGHTGRAY,GUI_LIGHTBLUE);
			Progbar_Set_flat(GUI_GREEN,GUI_LIGHTGRAY);
			Radio_Set_flat(GUI_LIGHTGRAY,GUI_BLACK,GUI_WHITE);
			break;
		default:
			GUI_DrawGradientH(0, 0, LCD_GetXSize()-1, LCD_GetYSize(), 0xbebab7, 0x635548);
			Button_Set_flat(GUI_LIGHTGRAY,GUI_LIGHTBLUE);
			Dropdwon_Set_flat(GUI_LIGHTGRAY,GUI_LIGHTBLUE);
			Progbar_Set_flat(GUI_GREEN,GUI_LIGHTGRAY);
			Radio_Set_flat(GUI_LIGHTGRAY,GUI_BLACK,GUI_WHITE);
		break;			
	}
	GUI_SetColor(GUI_LIGHTGRAY);
	GUI_FillRoundedRect(0,0,320,30,5);
	
	GUI_SetColor(MAIN_TEXTCOLOR);
	GUI_SetFont(MAIN_FONT);
	GUI_SetTextMode(GUI_TM_TRANS);
	GUI_DispStringAt("手持钻床控制器",0, 7);
	GUI_DrawBitmap(&bmwifi, 270, 7);
	GUI_DrawBitmap(&bmbattry, 290, 7);

}
/*
*********************************************************************************************************
*	函 数 名: _cbwait
*	功能说明: 第六个界面，等待工作结束
*	形    参：pMsg  参数指针
*	返 回 值: 无
*********************************************************************************************************
*/
static void _cbwait(WM_MESSAGE* pMsg) 
{
	WM_HWIN  hItem,hWin = pMsg->hWin;
	switch (pMsg->MsgId) 
	{
		case WM_CREATE:
			/* 设置聚焦 */
			WM_SetFocus(hWin);
			hItem = TEXT_CreateEx((FRAME_WIDTH >> 1)-70 , 120, 200, 20, hWin, WM_CF_SHOW, 0, GUI_ID_TEXT0,"Drilling...");
			TEXT_SetFont(hItem,&GUI_Font20B_ASCII);
			hItem = PROGBAR_CreateEx((FRAME_WIDTH >> 1) - 70, 150, 130,  40, hWin, WM_CF_SHOW, 0, GUI_ID_PROGBAR0);
            WM_CreateTimer(hWin,0,1000,0);
			PROGBAR_Max = buf[4];
			PROGBAR_SetMinMax(hItem ,0,PROGBAR_Max);
			break;
		 case WM_KEY:
			 switch (((WM_KEY_INFO*)(pMsg->Data.p))->Key) 
			{ 
			}
            break;
         case WM_TIMER:
			hItem = WM_GetDialogItem(pMsg->hWin, GUI_ID_PROGBAR0);
			if(RT_flag == 0xff)
			{
				GUI_MessageBox("Send error!","error",0);
				RT_flag = 0;
			}
			else if(RT_flag == MAX_TX)
			{
				GUI_MessageBox("Send error Max resend!","error",0);
				RT_flag = 0;
			}
			NRF24L01_RX_Mode();
			if(PROGBAR_Max!=0)
			{
				PROGBAR_Max--;
				PROGBAR_SetValue(hItem,PROGBAR_Value++);
				WM_RestartTimer(pMsg->Data.v,1000);
			}
			else
			{
				_DeleteFrame();
				PROGBAR_Value = 1;
			}
			break;
		case WM_PAINT:
			_PaintFrame();
            break;
		default:
		WM_DefaultProc(pMsg);
	}
}
/*
*********************************************************************************************************
*	函 数 名: _cbSetup
*	功能说明: 第六个界面，设置
*	形    参：pMsg  参数指针
*	返 回 值: 无
*********************************************************************************************************
*/
static void _cbSetup(WM_MESSAGE* pMsg) 
{
	WM_HWIN hItem,hWin = pMsg->hWin;
	switch (pMsg->MsgId) 
	{
		case WM_CREATE:
			/* 设置聚焦 */
			WM_SetFocus(hWin);
            _CreateUserButton((FRAME_WIDTH >> 1)+120, 200, 30,  30,hWin, GUI_ID_BUTTON0, &bmreturn, sizeof(bmreturn), _cbButtonPic);
		    _CreateButton((FRAME_WIDTH >> 1)-90, 60, 70,  40,hWin,GUI_ID_BUTTON2, "背光调整");
            _CreateButton((FRAME_WIDTH >> 1),    60, 70,  40,hWin,GUI_ID_BUTTON3, "更换风格");
		    _CreateButton((FRAME_WIDTH >> 1)-90, 110, 70,  40,hWin,GUI_ID_BUTTON4, "屏幕校准");
			_CreateButton((FRAME_WIDTH >> 1),    110, 70,  40,hWin,GUI_ID_BUTTON5, "敬请期待");
			break;
		 case WM_KEY:
			switch (((WM_KEY_INFO*)(pMsg->Data.p))->Key) 
			{ 
				   	case GUI_KEY_HOME:
						_DeleteFrame();
					break;
			}
            break;
		case WM_PAINT:
			_PaintFrame();
			break;
        case WM_NOTIFY_PARENT:
			if (pMsg->Data.v == WM_NOTIFICATION_RELEASED) 
			{
				int Id = WM_GetId(pMsg->hWinSrc);
				switch (Id) 
				{
					case GUI_ID_BUTTON0:
                        _DeleteFrame();
						break;
					case GUI_ID_BUTTON3:
						flex_index++;
						if(flex_index > 2) flex_index = 0;
						switch(flex_index)
						{
							case 0:FRAME_TEXTCOLOR = GUI_BLACK;break;
							case 1:FRAME_TEXTCOLOR = GUI_BLACK;break;
							case 2:FRAME_TEXTCOLOR = GUI_WHITE;break;
							default:FRAME_TEXTCOLOR = GUI_BLACK;break;
						}
						_DeleteFrame();
						_CreateFrame(&_cbSetup);
						break;
					case GUI_ID_BUTTON4:
						GUI_SetBkColor(GUI_WHITE);
						GUI_Clear();
                        TP_Adjust();  //屏幕校准 
						TP_Save_Adjdata();
						WM_InvalidateWindow(_hCurrentFrame);
						break;
				}
			}
			break;
		default:
		WM_DefaultProc(pMsg);
	}
}
	


/*
*********************************************************************************************************
*	函 数 名: _cbringmold
*	功能说明: 第五个界面，环模电机控制
*	形    参：pMsg  参数指针
*	返 回 值: 无
*********************************************************************************************************
*/
static void _cbringmold(WM_MESSAGE* pMsg) 
{
	WM_HWIN  hItem,hWin = pMsg->hWin;
	switch (pMsg->MsgId) 
	{
		case WM_CREATE:
			/* 设置聚焦 */
			WM_SetFocus(hWin);
            _CreateUserButton((FRAME_WIDTH >> 1)+120, 200, 30,  30,hWin, GUI_ID_BUTTON0, &bmreturn, sizeof(bmreturn), _cbButtonPic);
            _CreateButton((FRAME_WIDTH >> 1)-130,60, 70,  40,hWin,GUI_ID_BUTTON2,"工件左转");
            _CreateButton((FRAME_WIDTH >> 1)-130,110, 70,  40,hWin,GUI_ID_BUTTON3, "工件右转");
            _CreateButton((FRAME_WIDTH >> 1)-40, 60, 70,  40,hWin, GUI_ID_BUTTON4,"右转细调");
            _CreateButton((FRAME_WIDTH >> 1)-40, 110, 70,  40,hWin, GUI_ID_BUTTON5,"右转粗调");
            _CreateButton((FRAME_WIDTH >> 1)+50, 60, 70,  40,hWin, GUI_ID_BUTTON6,"转速减少");
            _CreateButton((FRAME_WIDTH >> 1)+50, 110, 70,  40,hWin, GUI_ID_BUTTON7,"转速增加");
			buf[0] = 4;
			break;
		 case WM_KEY:
			switch (((WM_KEY_INFO*)(pMsg->Data.p))->Key) 
			{ 
				   	case GUI_KEY_HOME:
						_DeleteFrame();
					break;
			}
            break;
		case WM_PAINT:
			_PaintFrame();
			break;
        case WM_NOTIFY_PARENT:
			if (pMsg->Data.v == WM_NOTIFICATION_RELEASED) 
			{
				int Id = WM_GetId(pMsg->hWinSrc);
				switch (Id) 
				{
					case GUI_ID_BUTTON0:
                        _DeleteFrame();
						break;
					case GUI_ID_BUTTON2:
						buf[13] = 1;
						break;
					case GUI_ID_BUTTON3:
						buf[13] = 2;
						break;
					case GUI_ID_BUTTON4:
						buf[13] = 3;
						break;
					case GUI_ID_BUTTON5:
						buf[13] = 4;
						break;  
					case GUI_ID_BUTTON6:
						buf[13] = 5;
						break;
					case GUI_ID_BUTTON7:
						buf[13] = 6;
						break;
				}
				NRF24L01_TX_Mode();
				NRF24L01_TxPacket(buf);
			}
			buf[13] = 0;
			break;
		default:
		WM_DefaultProc(pMsg);

	}
}

/*
*********************************************************************************************************
*	函 数 名: _cbrundrill
*	功能说明: 第四个界面，执行界面和完整数据界面
*	形    参：pMsg  参数指针
*	返 回 值: 无
*********************************************************************************************************
*/
static void _cbrundrill(WM_MESSAGE* pMsg) 
{
	WM_HWIN hItem,hTimer,hWin = pMsg->hWin;
	switch (pMsg->MsgId) 
	{
		case WM_CREATE:
			/* 设置聚焦 */
			WM_SetFocus(hWin);
            WM_CreateTimer(hWin,0,500,0);
            _CreateText((FRAME_WIDTH >> 1)-140 , 40,  65, 20, hWin, GUI_ID_TEXT0,"转动速度");
            _CreateText((FRAME_WIDTH >> 1)-40     , 40, 65, 20, hWin, GUI_ID_TEXT1,"钻孔速度");
		    _CreateText((FRAME_WIDTH >> 1)-140 , 90,  65, 20, hWin, GUI_ID_TEXT2,"孔数");
		    _CreateText((FRAME_WIDTH >> 1)-40     , 90,  65, 20, hWin, GUI_ID_TEXT3,"扩孔深度");
            _CreateText((FRAME_WIDTH >> 1)+60 , 40, 65, 20, hWin, GUI_ID_TEXT4,"钻孔深度");
		
            _CreateText((FRAME_WIDTH >> 1)-120     , 210, 65, 20, hWin, GUI_ID_TEXT5,"模式");
            _CreateText((FRAME_WIDTH >> 1)-70 , 210, 65, 20, hWin, GUI_ID_TEXT6,"奇偶数排");
            _CreateText((FRAME_WIDTH >> 1)+10    , 210, 65, 20, hWin, GUI_ID_TEXT7,"大小钻头");
        
            _CreateEdit((FRAME_WIDTH >> 1)-140, 60, 65, 20, hWin, GUI_ID_EDIT0, 3,0);
            _CreateEdit((FRAME_WIDTH >> 1)-40,    60, 65, 20, hWin, GUI_ID_EDIT1, 3,0);
            _CreateEdit((FRAME_WIDTH >> 1)-140, 110,65, 20, hWin, GUI_ID_EDIT2, 3,0);
            _CreateEdit((FRAME_WIDTH >> 1)-40,    110, 65, 20, hWin, GUI_ID_EDIT3, 3,0);
            _CreateEdit((FRAME_WIDTH >> 1)+60, 60, 65, 20, hWin, GUI_ID_EDIT4, 3,0);
		
            _CreateButton((FRAME_WIDTH >> 1)+60, 90, 65,  40, hWin, GUI_ID_BUTTON1, "检测");
			_CreateUserButton((FRAME_WIDTH >> 1)+120, 200, 30,  30,hWin, GUI_ID_BUTTON0, &bmreturn, sizeof(bmreturn), _cbButtonPic);
		    buf[0] = 5;
//			NRF24L01_TX_Mode();
//			NRF24L01_TxPacket(buf);
			break;
		 case WM_KEY:
			switch (((WM_KEY_INFO*)(pMsg->Data.p))->Key) 
			{ 
				   	case GUI_KEY_HOME:
						_DeleteFrame();
					break;
			}
            break;
		case WM_PAINT:
			_PaintFrame();
			GUI_SetColor(GUI_WHITE);
			GUI_DrawRoundedRect((FRAME_WIDTH >> 1)-140,210,(FRAME_WIDTH >> 1)+80,230,5);
			break;
        case WM_TIMER:
			if(RT_flag == TX_OK || RT_flag == RX_OK)
			{
				NRF24L01_RX_Mode();
				Set_Data(hWin);
				RT_flag = 0;
			}
            WM_RestartTimer(pMsg->Data.v,500);
            break;
        case WM_NOTIFY_PARENT:
			if (pMsg->Data.v == WM_NOTIFICATION_RELEASED) 
			{
				int Id = WM_GetId(pMsg->hWinSrc);
				switch (Id) 
				{
					case GUI_ID_BUTTON0:
						NRF24L01_TX_Mode();
                        _DeleteFrame();
						break;
					case GUI_ID_BUTTON1:
						NRF24L01_TX_Mode();
						NRF24L01_TxPacket(buf);
						break;
				}
			}
			break;
		default:
		WM_DefaultProc(pMsg);
	}
}
/*
*********************************************************************************************************
*	函 数 名: _cbwireless
*	功能说明: 第三个界面，无线测试
*	形    参：pMsg  参数指针
*	返 回 值: 无
*********************************************************************************************************
*/
static void _cbwireless(WM_MESSAGE* pMsg) 
{
	WM_HWIN hItem,hWin = pMsg->hWin;
	switch (pMsg->MsgId) 
	{
		case WM_CREATE:
			/* 设置聚焦 */
			WM_SetFocus(hWin);
			_CreateUserButton((FRAME_WIDTH >> 1)+120, 200, 30,  30,hWin, GUI_ID_BUTTON0, &bmreturn, sizeof(bmreturn), _cbButtonPic);
            _CreateButton((FRAME_WIDTH >> 1)-90, 60, 120,  40, hWin, GUI_ID_BUTTON2, "模块检测");
            _CreateButton((FRAME_WIDTH >> 1)-90, 110, 120,  40, hWin, GUI_ID_BUTTON3,"数据传输检测");
		    buf[0] = 2;              //用于测试
			break;
		 case WM_KEY:
			switch (((WM_KEY_INFO*)(pMsg->Data.p))->Key) 
			{ 
				  	case GUI_KEY_HOME:
						_DeleteFrame();
					break;
			}
            break;
		case WM_PAINT:
			_PaintFrame();
			break;
        case WM_NOTIFY_PARENT:
			if (pMsg->Data.v == WM_NOTIFICATION_RELEASED) 
			{
				int Id = WM_GetId(pMsg->hWinSrc);
				switch (Id) 
				{
					case GUI_ID_BUTTON0:
                        _DeleteFrame();
						break;
                    case GUI_ID_BUTTON2:
                        if(NRF24L01_Check())
                        {
                            GUI_MessageBox("Clinet NRF24L01 error!","Error",0);
                        }
						else
						{
							GUI_MessageBox("Client NRF24L01 Normal!","Normal",0);
						}
						break;
                    case GUI_ID_BUTTON3:
                        NRF24L01_TX_Mode();
						NRF24L01_TxPacket(buf);
						if(RT_flag == TX_OK)
						{
							GUI_MessageBox("Send success!","Normal",0);
							RT_flag = 0;
						}
						else if(RT_flag == MAX_TX)
						{
							GUI_MessageBox("Send error Max resend!","error",0);
							RT_flag = 0;
						}
						else
						{
							GUI_MessageBox("other error!","error",0);
							RT_flag = 0;
						}
					break;
				}
			}
			break;
		default:
		WM_DefaultProc(pMsg);
	}
}

/*
*********************************************************************************************************
*	函 数 名: _cbSingledrill
*	功能说明: 第二个界面，单孔操作
*	形    参：pMsg  参数指针
*	返 回 值: 无
*********************************************************************************************************
*/
static void _cbSingledrill(WM_MESSAGE* pMsg) 
{
	WM_HWIN  hItem,hWin = pMsg->hWin;
	switch (pMsg->MsgId) 
	{
		case WM_CREATE:
			/* 设置聚焦 */
			WM_SetFocus(hWin);
			/* 创建两个按钮，用于选择中文和英文 */
            hItem = DROPDOWN_CreateEx((FRAME_WIDTH >> 1) - 130, 60, 80,  80, hWin, WM_CF_SHOW, 0, GUI_ID_DROPDOWN0);
            DROPDOWN_AddString(hItem,"M1");
            DROPDOWN_AddString(hItem,"M2");
            DROPDOWN_AddString(hItem,"M3");
            DROPDOWN_SetFont(hItem,&GUI_Font24B_ASCII);
			_CreateButton((FRAME_WIDTH >> 1)-40,60,  80,  40, hWin, GUI_ID_BUTTON2,"定位");
			_CreateButton((FRAME_WIDTH >> 1)-40,120,  80,  40, hWin, GUI_ID_BUTTON3,"扩孔");
            _CreateButton((FRAME_WIDTH >> 1)+50,60, 80,  40, hWin, GUI_ID_BUTTON4,"上升");
            _CreateButton((FRAME_WIDTH >> 1)+50,120, 80,  40, hWin, GUI_ID_BUTTON5,"下降");
			_CreateUserButton((FRAME_WIDTH >> 1)+120, 200, 30,  30,hWin, GUI_ID_BUTTON0, &bmreturn, sizeof(bmreturn), _cbButtonPic);
			buf[0] = 3;
			Set_widget_value(hWin,GUI_ID_DROPDOWN0,buf[2]);
			break;
		 case WM_KEY:
			switch (((WM_KEY_INFO*)(pMsg->Data.p))->Key) 
			{ 

					case GUI_KEY_HOME:
						_DeleteFrame();
					break;
			}
            break;
		case WM_PAINT:
			_PaintFrame();
			break;
        case WM_NOTIFY_PARENT:
			if (pMsg->Data.v == WM_NOTIFICATION_RELEASED) 
			{
				int Id = WM_GetId(pMsg->hWinSrc);
				switch (Id) 
				{
					case GUI_ID_BUTTON0:
						_DeleteFrame();
						break;
					case GUI_ID_BUTTON2:
						buf[16] = 1;
						break;
					case GUI_ID_BUTTON3:
						buf[16] = 2;
						break;
					case GUI_ID_BUTTON4:
						buf[16] = 3;
						break;
					case GUI_ID_BUTTON5:
						buf[16] = 4;
						break; 
				}
				NRF24L01_TX_Mode();
				NRF24L01_TxPacket(buf);
			}
			else if(pMsg->Data.v == WM_NOTIFICATION_SEL_CHANGED)
			{
				int Id = WM_GetId(pMsg->hWinSrc);
				switch (Id) 
				{
					case GUI_ID_DROPDOWN0:
                        buf[2] = Get_widget_value(hWin,GUI_ID_DROPDOWN0);
						break;
				}
				NRF24L01_TX_Mode();
				NRF24L01_TxPacket(buf);
			}
			buf[16] = 0;
			break;
		default:
		WM_DefaultProc(pMsg);
	}
}



/*
*********************************************************************************************************
*	函 数 名: _cbkeypad
*	功能说明: 第七个界面，小键盘
*	形    参：pMsg  参数指针
*	返 回 值: 无
*********************************************************************************************************
*/
static void _cbkeypad(WM_MESSAGE* pMsg) 
{
	WM_HWIN hItem,hWin = pMsg->hWin;
	switch (pMsg->MsgId) 
	{
		case WM_CREATE:
			_CreateUserButton(0,    5, 40,  30,hWin, GUI_ID_BUTTON0, "0",2, _cbButtonText);
			_CreateUserButton(40,   5, 40,  30,hWin, GUI_ID_BUTTON1, "1",2, _cbButtonText);
			_CreateUserButton(80,   5, 40,  30,hWin, GUI_ID_BUTTON2, "2",2, _cbButtonText);
			_CreateUserButton(120,  5, 40,  30,hWin, GUI_ID_BUTTON3, "3",2, _cbButtonText);
			_CreateUserButton(160,  5, 40,  30,hWin, GUI_ID_BUTTON4, "4",2, _cbButtonText);
			_CreateUserButton(200,  5, 40,  30,hWin, GUI_ID_BUTTON_YES, "Yes",4, _cbButtonText);
			_CreateUserButton(0,    40, 40,  30,hWin, GUI_ID_BUTTON5, "5",2, _cbButtonText);
			_CreateUserButton(40,   40, 40,  30,hWin, GUI_ID_BUTTON6, "6",2, _cbButtonText);
			_CreateUserButton(80,   40, 40,  30,hWin, GUI_ID_BUTTON7, "7",2, _cbButtonText);
			_CreateUserButton(120,  40, 40,  30,hWin, GUI_ID_BUTTON8, "8",2, _cbButtonText);
			_CreateUserButton(160,  40, 40,  30,hWin, GUI_ID_BUTTON9, "9",2, _cbButtonText);
			_CreateUserButton(200,  40, 40,  30,hWin, GUI_ID_BUTTON_DEL, "Del",4, _cbButtonText);
			break;
		 case WM_KEY:
			switch (((WM_KEY_INFO*)(pMsg->Data.p))->Key) 
			{ 

				   	case GUI_KEY_HOME:
						_DeleteFrame();
					    _hKeypadFrame = 0;
					break;
			}
            break;
		case WM_PAINT:
			_Paintkeypad();
			break;
        case WM_NOTIFY_PARENT:	
			if (pMsg->Data.v == WM_NOTIFICATION_RELEASED) 
			{
				int Id = WM_GetId(pMsg->hWinSrc);
				switch (Id) 
				{
					case GUI_ID_BUTTON0:
						GUI_SendKeyMsg('0',1);
						break;
					case GUI_ID_BUTTON1:
						GUI_SendKeyMsg('1',1);
						break;
					case GUI_ID_BUTTON2:
						GUI_SendKeyMsg('2',1);
						break;
					case GUI_ID_BUTTON3:
						GUI_SendKeyMsg('3',1);
						break;
					case GUI_ID_BUTTON4:
						GUI_SendKeyMsg('4',1);
						break;
					case GUI_ID_BUTTON5:
						GUI_SendKeyMsg('5',1);
						break;
					case GUI_ID_BUTTON6:
						GUI_SendKeyMsg('6',1);
						break;
					case GUI_ID_BUTTON7:
						GUI_SendKeyMsg('7',1);
						break;
					case GUI_ID_BUTTON8:
						GUI_SendKeyMsg('8',1);
						break;
					case GUI_ID_BUTTON9:
						GUI_SendKeyMsg('9',1);
						break;
					case GUI_ID_BUTTON_YES:
						Parameter_Check(_hCurrentFrame,edit_id);
						WM_DeleteWindow(_hKeypadFrame);				
						_hKeypadFrame = 0;
						break;
					case GUI_ID_BUTTON_DEL:
						GUI_SendKeyMsg(GUI_KEY_BACKSPACE,1);
						break;
				}
			}
			break;
		default:
		WM_DefaultProc(pMsg);
	}
}
	
/*
*********************************************************************************************************
*	函 数 名: Input_Drill_Depth()
*	功能说明: 输入钻孔深度
*	返 回 值: 无
*********************************************************************************************************
*/
static void Input_Drill_Depth(WM_HWIN hWin)
{
    _Createradio((FRAME_WIDTH >> 1)+50, 50, 80,70, hWin, GUI_ID_RADIO1,drill_Item,GUI_COUNTOF(drill_Item));      
    _CreateText((FRAME_WIDTH >> 1) , 110, 80, 20, hWin,GUI_ID_TEXT2,"钻孔深度");
    _CreateEdit((FRAME_WIDTH >> 1), 140, 80, 25, hWin, GUI_ID_EDIT2, 3,1);
}

/*
*********************************************************************************************************
*	函 数 名: Input_Enarge_Depth()
*	功能说明: 输入扩孔深度
*	返 回 值: 无
*********************************************************************************************************
*/
static void Input_Enarge_Depth(WM_HWIN hWin)
{
    _CreateText((FRAME_WIDTH >> 1)-130 , 110, 80, 20, hWin, GUI_ID_TEXT1,"扩孔深度");
    _CreateEdit((FRAME_WIDTH >> 1)-130, 140, 80, 25, hWin, GUI_ID_EDIT1, 3,1);
}
/*
*********************************************************************************************************
*	函 数 名: Input_Basice_Data()
*	功能说明: 输入孔数，奇偶数排
*	返 回 值: 无
*********************************************************************************************************
*/
static void Input_Basice_Data(WM_HWIN hWin)
{
    _CreateText((FRAME_WIDTH >> 1)-130 , 40, 80, 20, hWin,GUI_ID_TEXT0,"孔数");
    _CreateEdit((FRAME_WIDTH >> 1)-130 , 70, 80, 25, hWin, GUI_ID_EDIT0, 3,1);
    _Createradio((FRAME_WIDTH >> 1)-40, 50, 80, 70, hWin, GUI_ID_RADIO0,   OddEven_Item,GUI_COUNTOF(OddEven_Item));
}
/*
*********************************************************************************************************
*	函 数 名: _cbInputdrillParameter
*	功能说明: 第一个界面，用于大小钻头、奇偶数排等参数的设定
*	形    参：pMsg  参数指针
*	返 回 值: 无
*********************************************************************************************************
*/
static void _cbInputdrillParameter(WM_MESSAGE* pMsg) 
{
	WM_HWIN  hItem,hWin = pMsg->hWin;
	switch (pMsg->MsgId) 
	{
		case WM_CREATE:
			/* 设置聚焦 */
			WM_SetFocus(hWin);
            _CreateButton((FRAME_WIDTH >> 1)-90, 190, 80,  40,hWin, GUI_ID_BUTTON0,"执行");
			_CreateUserButton((FRAME_WIDTH >> 1)+120, 200, 30,  30,hWin, GUI_ID_BUTTON1, &bmreturn, sizeof(bmreturn), _cbButtonPic);
            Input_Basice_Data(hWin);
            if(buf[1]==1)
            {
                Input_Enarge_Depth(hWin);
            }
            else if(buf[1]==2)
            {
                Input_Enarge_Depth(hWin);
                Input_Drill_Depth(hWin);
            }
            Set_Drill_Data(hWin);
			buf[0] = 0;              //用发送数据
			break;
		 case WM_KEY:
			switch (((WM_KEY_INFO*)(pMsg->Data.p))->Key) 
			{
					case GUI_KEY_HOME:
						_DeleteFrame();
					break;
			}
            break;
		case WM_PAINT:
			_PaintFrame();
			break;
        case WM_NOTIFY_PARENT:
			if (pMsg->Data.v == WM_NOTIFICATION_RELEASED) 
			{
				int Id = WM_GetId(pMsg->hWinSrc);
				switch (Id) 
				{
					case GUI_ID_BUTTON0:
						Parameter_Check(hWin,edit_id);
						printf("%u",parameter_flag);
						if(parameter_flag == 0)
                        {
							Get_Drill_Data(hWin);
							NRF24L01_TX_Mode();
							NRF24L01_TxPacket(buf);
							_DeleteFrame();
							_CreateFrame(&_cbwait);
							parameter_flag = 1;
						}
						else
						{
							GUI_MessageBox("parameter error!","error",0);
						}
						break;
					case GUI_ID_BUTTON1:
                        _DeleteFrame();
						_hKeypadFrame = 0;
						_CreateFrame(&_cbInputParameter);					
						break;
					case GUI_ID_EDIT0:
						Input_Check(hWin,GUI_ID_EDIT0);
					break;
					case GUI_ID_EDIT1:
						Input_Check(hWin,GUI_ID_EDIT1);
					break;
					case GUI_ID_EDIT2:
						Input_Check(hWin,GUI_ID_EDIT2);
					break;
				}
				
			}
			break;
		default:
		WM_DefaultProc(pMsg);
	}
}

/*
*********************************************************************************************************
*	函 数 名: _cbInputParameter
*	功能说明: 第一个界面，用于转速、深度等参数的设定
*	形    参：pMsg  参数指针
*	返 回 值: 无
*********************************************************************************************************
*/
static void _cbInputParameter(WM_MESSAGE* pMsg) 
{
	WM_HWIN  hItem,hWin = pMsg->hWin;
	switch (pMsg->MsgId) 
	{
		case WM_CREATE:
			/* 设置聚焦 */
			WM_SetFocus(hWin);
            _CreateText((FRAME_WIDTH >> 1)-90, 50, 80, 20, hWin, GUI_ID_TEXT0,"模式选择");
            _Createradio((FRAME_WIDTH >> 1)-90, 80, 80,80, hWin, GUI_ID_RADIO0,model_Item,GUI_COUNTOF(model_Item));
            Set_User_Data(hWin);
            _CreateButton((FRAME_WIDTH >> 1)-90, 190, 80,  40,hWin, GUI_ID_BUTTON0, "设置");
			_CreateUserButton((FRAME_WIDTH >> 1)+120, 200, 30,  30,hWin, GUI_ID_BUTTON1, &bmreturn, sizeof(bmreturn), _cbButtonPic);
			break;
		 case WM_KEY:
			switch (((WM_KEY_INFO*)(pMsg->Data.p))->Key) 
			{ 
				 case GUI_KEY_HOME:
						_DeleteFrame();
					break;
			}
            break;
		case WM_PAINT:
			_PaintFrame();
			break;
         case WM_NOTIFY_PARENT:
			if (pMsg->Data.v == WM_NOTIFICATION_RELEASED) 
			{
				int Id = WM_GetId(pMsg->hWinSrc);
				switch (Id) 
				{
					case GUI_ID_BUTTON0:
                        Get_User_Data(hWin);
						_DeleteFrame();
                        _CreateFrame(&_cbInputdrillParameter);
						break;
					case GUI_ID_BUTTON1:
                        _DeleteFrame();
						break;
				}
			}
			break;
		default:
		WM_DefaultProc(pMsg);
	}
}

/*
*********************************************************************************************************
*	函 数 名: _cbSelect
*	功能说明: 主界面用作功能的选择
*	形    参：pMsg  参数指针
*	返 回 值: 无
*********************************************************************************************************
*/
static void _cbSelect(WM_MESSAGE* pMsg) 
{
	WM_HWIN hWin = pMsg->hWin;
    int sel;
	switch (pMsg->MsgId) 
	{
		case WM_CREATE:
			/* 设置聚焦 */
			WM_SetFocus(hWin);
            _CreateIcon(20,40,65*3+2*40,80*2+30,hWin,GUI_ID_ICONVIEW0); 
			break;
		 case WM_KEY:
			switch (((WM_KEY_INFO*)(pMsg->Data.p))->Key) 
			{ 
			}
            break;
		case WM_PAINT:
			_PaintFrame();
			break;
        case WM_NOTIFY_PARENT:
			switch (WM_GetId(pMsg->hWinSrc)) 
			{
				/* 点击ICONVIEW上相应的图标，打开相应的窗口 */
				case GUI_ID_ICONVIEW0:
					switch (pMsg->Data.v) 
					{
							case WM_NOTIFICATION_RELEASED:
								sel = ICONVIEW_GetSel(pMsg->hWinSrc);
								if(sel < GUI_COUNTOF(_aBitmapItem))
								{
									/* 进入相应的应用程序 */
									_CreateFrame(_apModules[sel]);
								}
							break;
					}
				break;
			}
			break;
		default:
		WM_DefaultProc(pMsg);
	}
}

void CreateFramewin(void) {
    
	/* 使能窗口使用内存设备 */
	WM_SetCreateFlags(WM_CF_MEMDEV);
    
	/* 使能控件的皮肤色 */
	FRAMEWIN_SetDefaultSkin(FRAMEWIN_SKIN_FLEX);
	PROGBAR_SetDefaultSkin(PROGBAR_SKIN_FLEX);
	BUTTON_SetDefaultSkin(BUTTON_SKIN_FLEX);
	DROPDOWN_SetDefaultSkin(DROPDOWN_SKIN_FLEX);
	RADIO_SetDefaultSkin(RADIO_SKIN_FLEX);
	Button_Set_flat(GUI_LIGHTGRAY,GUI_LIGHTBLUE);
	Dropdwon_Set_flat(GUI_LIGHTGRAY,GUI_LIGHTBLUE);
	Progbar_Set_flat(GUI_GREEN,GUI_LIGHTGRAY);
	Radio_Set_flat(GUI_LIGHTGRAY,GUI_BLACK,GUI_WHITE);
	Welcome_page();
	/*设置桌面窗口回调*/
	WM_SetCallback(WM_HBKWIN,&_cbBkWindow);
	_CreateFrame(&_cbSelect);
	
	GUI_UC_SetEncodeUTF8();
}


/*************************** End of file ****************************/
