/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "key.h"
#include "stdio.h"
#include "stdlib.h" 
#include "led.h"
#include "24L01.h"
#include "EmWinHZFont.h"
#include "FramewinDLG.h"



#define x 20

static WM_HWIN DialogWin;
extern GUI_CONST_STORAGE GUI_BITMAP bmwireless;
extern GUI_CONST_STORAGE GUI_BITMAP bmappstore;
extern GUI_CONST_STORAGE GUI_BITMAP bmset;
extern GUI_CONST_STORAGE GUI_BITMAP bmnotebook;

typedef struct User_data 
{
    uint8_t motion_num;//电机号
    uint16_t vm;      //转动速度
    uint8_t vt;       //钻孔速度
    uint8_t num;      //打孔次数
    uint8_t depth;    //打孔深度
    uint8_t h_space;  //间距
    uint8_t v_space;  //行距
}User_data;

User_data *u;
uint8_t buf[32];
/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "Framewin", ID_FRAMEWIN_0, 0, 0, 240, 320, 0, 0x0, 0 },
  
  { DROPDOWN_CreateIndirect, "Dropdown", ID_DROPDOWN_0, 90, 67-x, 60, 50, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_0, 90, 119-x, 60, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_1, 90, 151-x, 60, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_2, 90, 183-x, 60, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_3, 90, 215-x, 60, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_4, 90, 247-x, 60, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_5, 90, 279-x, 60, 20, 0, 0x64, 0 },
   
  
  { TEXT_CreateIndirect, "手持钻床控制器", ID_TEXT_1, 10, 10, 180, 40, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "钻头电机", ID_TEXT_0, 13, 67-x, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "转动速度", ID_TEXT_2, 13, 119-x, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "钻孔速度", ID_TEXT_3, 13, 151-x, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "打孔次数", ID_TEXT_4, 13, 183-x, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "钻孔深度", ID_TEXT_5, 13, 215-x, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "钻孔间距", ID_TEXT_6, 13, 247-x, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "钻孔行距", ID_TEXT_7, 13, 279-x, 80, 20, 0, 0x0, 0 },
  
  { BUTTON_CreateIndirect, "YES", ID_BUTTON_0, 13, 295, 60, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "NO", ID_BUTTON_1, 83, 295, 60, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_2, 170, 40, 60, 60, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_3, 170, 110, 60, 60, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_4, 170, 180, 60, 60, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_5, 170, 250, 60, 60, 0, 0x0, 0 },
  
};

void _SendMsg(char *pStr)
{
    WM_MESSAGE Message;
    Message.MsgId =  MSG_KEY_DOWN;
    Message.Data.p = pStr;
    WM_SendMessage(WM_GetClientWindow(DialogWin),&Message);
    WM_InvalidateWindow(DialogWin);  
}

static int Get_widget_value(GUI_HWIN hWin,int id)
{
    char tmp[10];
    WM_HWIN hItem;
    WM_CALLBACK *pCb;
    hItem = WM_GetDialogItem(hWin, id);
    pCb = WM_GetCallback(hItem);
    if(pCb == DROPDOWN_Callback)
    {    
        return DROPDOWN_GetSel(hItem);
    }
    else if(pCb == EDIT_Callback)
    {
        EDIT_GetText(hItem,tmp,10);
        return atoi(tmp);
    }
    
}

void User_data_encode(GUI_HWIN hwin)
{
    buf[0] = Get_widget_value(hwin,ID_DROPDOWN_0);
    buf[1] = Get_widget_value(hwin,ID_EDIT_0);
    buf[2] = Get_widget_value(hwin,ID_EDIT_1);
    buf[3] = Get_widget_value(hwin,ID_EDIT_2);
    buf[4] = Get_widget_value(hwin,ID_EDIT_3);
    buf[5] = Get_widget_value(hwin,ID_EDIT_4);
    buf[6] = Get_widget_value(hwin,ID_EDIT_5); 
}

static void _cbDesktop(WM_MESSAGE * pMsg) 
{
	unsigned i;

	switch (pMsg->MsgId) 
	{
		/* 重绘 */
		case WM_PAINT:
			GUI_SetBkColor(GUI_LIGHTGRAY);
			GUI_Clear();
			break;
	}
}

static void InitDialog(WM_MESSAGE * pMsg)
{
    WM_HWIN hItem;

    hItem = pMsg->hWin;
    FRAMEWIN_SetTitleVis(hItem, 0);
    
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetSkin(hItem,BUTTON_SKIN_FLEX);
    
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetSkin(hItem,BUTTON_SKIN_FLEX);
    
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    BUTTON_SetSkin(hItem,BUTTON_SKIN_FLEX);
    BUTTON_SetBitmapEx(hItem,0,&bmwireless,0,0);
    
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
    BUTTON_SetSkin(hItem,BUTTON_SKIN_FLEX);
    BUTTON_SetBitmapEx(hItem,0,&bmappstore,0,0);
    
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
    BUTTON_SetSkin(hItem,BUTTON_SKIN_FLEX);
    BUTTON_SetBitmapEx(hItem,0,&bmset,0,0);
    
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
    BUTTON_SetSkin(hItem,BUTTON_SKIN_FLEX);
    BUTTON_SetBitmapEx(hItem,0,&bmnotebook,0,0);
    
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem, &GUI_FontHZ24);
    
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, &GUI_FontHZ12);
    
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetFont(hItem, &GUI_FontHZ12);
    
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);   
    TEXT_SetFont(hItem, &GUI_FontHZ12);
    
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetFont(hItem, &GUI_FontHZ12);
    
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetFont(hItem, &GUI_FontHZ12);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    TEXT_SetFont(hItem, &GUI_FontHZ12);
    
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
    TEXT_SetFont(hItem, &GUI_FontHZ12);
    
    
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    EDIT_SetText(hItem, "30");
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_TOP);
    WM_SetFocus(hItem);
 
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
    EDIT_SetText(hItem, "22");
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_TOP);
    
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);
    EDIT_SetText(hItem, "10");
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_TOP);
    
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);
    EDIT_SetText(hItem, "20");
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_TOP);
    
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_4);
    EDIT_SetText(hItem, "5");
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_TOP);
    
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_5);
    EDIT_SetText(hItem, "4");
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_TOP);


    hItem = WM_GetDialogItem(pMsg->hWin,ID_DROPDOWN_0);
    DROPDOWN_SetFont(hItem,GUI_FONT_16_ASCII);
    DROPDOWN_SetAutoScroll(hItem,1);
    DROPDOWN_AddString(hItem,"M1");
    DROPDOWN_AddString(hItem,"M2");
    DROPDOWN_AddString(hItem,"M3");
    DROPDOWN_AddString(hItem,"M4");
    DROPDOWN_AddString(hItem,"M5");
    DROPDOWN_AddString(hItem,"M6");
}

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  User_data u;

  switch (pMsg->MsgId) {
              
  case WM_INIT_DIALOG:
    InitDialog(pMsg);
    break;
  case WM_KEY:
    hItem = WM_GetDialogItem(DialogWin, ID_BUTTON_0);
    switch(((WM_KEY_INFO*)(pMsg->Data.p))->Key)
    {
        case GUI_KEY_ENTER:
            WM_SetFocus(hItem);
            GUI_SendKeyMsg(GUI_KEY_ENTER,1);
            break;
        default:;break;
    }
    break;
    
  case WM_PAINT:
      GUI_SetBkColor(GUI_LIGHTGRAY);
      GUI_Clear();
      break;      
    
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'YES'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
//        hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
//        EDIT_GetText(hItem,buf,32);
        User_data_encode(pMsg->hWin);
        NRF24L01_TX_Mode();
        if(NRF24L01_TxPacket(buf)==TX_OK)
        {
            LED0 = ~LED0;
        }
        break;
      case WM_NOTIFICATION_RELEASED:
        break;
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'NO'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        break;
      }
      break;
    }
    break;

  default:
    WM_DefaultProc(pMsg);
    break;
  }

}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/

WM_HWIN CreateFramewin(void) {
    
  WM_HWIN hWin;
  
  DialogWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  hWin = DialogWin;  
  WM_SetCallback(WM_HBKWIN,_cbDesktop);
    
  return hWin;
}


/*************************** End of file ****************************/
