/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font Converter for emWin version 5.28                       *
*        Compiled Jan 30 2015, 16:40:45                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: font12.c                                              *
* Font:        ËÎÌו                                                  *
* Height:      16                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  16                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: E:\GitHub\wireless-human-computer-interaction-system\Client\TEXT\font12.txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontfont12;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_4F4D[ 32] = { /* code 4F4D */
  ____X___,X_______,
  ____X___,_X______,
  ____X___,_X______,
  ___X____,________,
  ___X_XXX,XXXXXX__,
  __XX____,________,
  __XX____,____X___,
  _X_X__X_,____X___,
  X__X__X_,____X___,
  ___X___X,___X____,
  ___X___X,___X____,
  ___X___X,___X____,
  ___X___X,__X_____,
  ___X____,__X_____,
  ___XXXXX,XXXXXXX_,
  ___X____,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_5076[ 32] = { /* code 5076 */
  ___X____,________,
  ___X_XXX,XXXXXX__,
  ___X_X__,_X___X__,
  __X__X__,_X___X__,
  __X__XXX,XXXXXX__,
  _XX__X__,_X___X__,
  _XX__X__,_X___X__,
  X_X__XXX,XXXXXX__,
  __X_____,_X______,
  __X_XXXX,XXXXXXX_,
  __X_X___,_X____X_,
  __X_X___,_X_X__X_,
  __X_X_XX,XXXX__X_,
  __X_X__X,___X__X_,
  __X_X___,____X_X_,
  __X_X___,_____X__};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_52A8[ 32] = { /* code 52A8 */
  ________,_X______,
  ________,_X______,
  _XXXXX__,_X______,
  ________,_X______,
  _______X,XXXXXX__,
  ________,_X___X__,
  XXXXXXX_,_X___X__,
  __X_____,_X___X__,
  __X_____,_X___X__,
  __X_____,X____X__,
  _X__X___,X____X__,
  _X___X__,X____X__,
  XXXXXX_X,_____X__,
  _X___X_X,_____X__,
  ______X_,__X_X___,
  _____X__,___X____};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_53D6[ 32] = { /* code 53D6 */
  ________,________,
  XXXXXXXX,X_______,
  __X___X_,XXXXXX__,
  __X___X_,_X___X__,
  __XXXXX_,_X___X__,
  __X___X_,_X___X__,
  __X___X_,_X___X__,
  __XXXXX_,_X___X__,
  __X___X_,__X_X___,
  __X___X_,__X_X___,
  __X__XXX,X_X_X___,
  XXXXX_X_,___X____,
  _X____X_,___X____,
  ______X_,__X_X___,
  ______X_,_X___X__,
  ______X_,X_____X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_5927[ 32] = { /* code 5927 */
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  _______X,________,
  _______X,________,
  ______X_,X_______,
  ______X_,X_______,
  _____X__,_X______,
  _____X__,_X______,
  ____X___,__X_____,
  ___X____,___X____,
  __X_____,____X___,
  XX______,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_5934[ 32] = { /* code 5934 */
  ________,X_______,
  ________,X_______,
  ____X___,X_______,
  _____X__,X_______,
  __X__X__,X_______,
  ___X____,X_______,
  ___X____,X_______,
  ________,X_______,
  XXXXXXXX,XXXXXXX_,
  _______X,________,
  _______X,_X______,
  ______X_,__X_____,
  _____X__,___X____,
  ____X___,____X___,
  __XX____,_____X__,
  XX______,_____X__};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_5947[ 32] = { /* code 5947 */
  _______X,________,
  _______X,________,
  __XXXXXX,XXXXX___,
  ______X_,X_______,
  _____X__,_X______,
  ____X___,__X_____,
  XXXXXXXX,XXXXXXX_,
  ________,___X____,
  ________,___X____,
  ___XXXXX,X__X____,
  ___X____,X__X____,
  ___X____,X__X____,
  ___XXXXX,X__X____,
  ________,___X____,
  ________,_X_X____,
  ________,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_5B54[ 32] = { /* code 5B54 */
  ________,_X______,
  _XXXXXX_,_X______,
  ______X_,_X______,
  _____X__,_X______,
  ____X___,_X______,
  ____X___,_X______,
  ____X_X_,_X______,
  ____XX__,_X______,
  __XXX___,_X______,
  XX__X___,_X______,
  ____X___,_X______,
  ____X___,_X____X_,
  ____X___,_X____X_,
  ____X___,_X____X_,
  __X_X___,__XXXXX_,
  ___X____,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_5B9A[ 32] = { /* code 5B9A */
  ______X_,________,
  _______X,________,
  _XXXXXXX,XXXXXXX_,
  _X______,______X_,
  X_______,_____X__,
  ________,________,
  __XXXXXX,XXXXX___,
  _______X,________,
  _______X,________,
  ___X___X,________,
  ___X___X,XXXXX___,
  ___X___X,________,
  ___X___X,________,
  __X_X__X,________,
  _X___XXX,XXXXXXX_,
  X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_5C0F[ 32] = { /* code 5C0F */
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  ___X___X,___X____,
  ___X___X,____X___,
  ___X___X,_____X__,
  __X____X,_____X__,
  __X____X,______X_,
  _X_____X,______X_,
  X______X,______X_,
  _______X,________,
  _______X,________,
  _____X_X,________,
  ______X_,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_5EA6[ 32] = { /* code 5EA6 */
  _______X,________,
  ________,X_______,
  __XXXXXX,XXXXXXX_,
  __X___X_,__X_____,
  __X___X_,__X_____,
  __XXXXXX,XXXXXX__,
  __X___X_,__X_____,
  __X___X_,__X_____,
  __X___XX,XXX_____,
  __X_____,________,
  __X_XXXX,XXXX____,
  __X__X__,___X____,
  _X____X_,__X_____,
  _X_____X,XX______,
  X____XX_,__XX____,
  __XXX___,____XXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_6253[ 32] = { /* code 6253 */
  ___X____,________,
  ___X____,________,
  ___X__XX,XXXXXXX_,
  ___X____,__X_____,
  XXXXXX__,__X_____,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X_X__,__X_____,
  ___XX___,__X_____,
  __XX____,__X_____,
  XX_X____,__X_____,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X____,__X_____,
  _X_X____,X_X_____,
  __X_____,_X______};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_6269[ 32] = { /* code 6269 */
  ___X____,__X_____,
  ___X____,___X____,
  ___X____,___X____,
  ___X___X,XXXXXXX_,
  XXXXXX_X,________,
  ___X___X,________,
  ___X___X,________,
  ___X_X_X,________,
  ___XX__X,________,
  __XX___X,________,
  XX_X___X,________,
  ___X___X,________,
  ___X___X,________,
  ___X__X_,________,
  _X_X__X_,________,
  __X__X__,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_62CD[ 32] = { /* code 62CD */
  ___X____,__X_____,
  ___X____,__X_____,
  ___X____,_X______,
  ___X___X,XXXXXX__,
  XXXXXX_X,_____X__,
  ___X___X,_____X__,
  ___X___X,_____X__,
  ___X_X_X,_____X__,
  ___XX__X,XXXXXX__,
  __XX___X,_____X__,
  XX_X___X,_____X__,
  ___X___X,_____X__,
  ___X___X,_____X__,
  ___X___X,_____X__,
  _X_X___X,XXXXXX__,
  __X____X,_____X__};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_6392[ 32] = { /* code 6392 */
  ___X____,X__X____,
  ___X____,X__X____,
  ___X____,X__X____,
  ___X_XXX,X__XXXX_,
  XXXXX___,X__X____,
  ___X____,X__X____,
  ___X____,X__X____,
  ___XX_XX,X__XXX__,
  __XX____,X__X____,
  XX_X____,X__X____,
  ___X____,X__X____,
  ___X_XXX,X__XXXX_,
  ___X____,X__X____,
  ___X____,X__X____,
  _X_X____,X__X____,
  __X_____,X__X____};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_6570[ 32] = { /* code 6570 */
  ____X___,__X_____,
  _X__X__X,__X_____,
  __X_X_X_,__X_____,
  ____X___,__XXXXX_,
  XXXXXXXX,_X___X__,
  __X_X_X_,_X___X__,
  _X__X__X,_X___X__,
  X___X___,X_X__X__,
  ___X____,__X_X___,
  XXXXXXX_,__X_X___,
  __X___X_,___X____,
  _X____X_,___X____,
  _XX__X__,__X_X___,
  ___XX___,__X_X___,
  __XX_X__,_X___X__,
  XX____X_,X_____X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_673A[ 32] = { /* code 673A */
  ___X____,________,
  ___X___X,XXXX____,
  ___X___X,___X____,
  ___X___X,___X____,
  XXXXXX_X,___X____,
  ___X___X,___X____,
  __XX___X,___X____,
  __XXX__X,___X____,
  _X_X_X_X,___X____,
  _X_X_X_X,___X____,
  X__X___X,___X____,
  ___X___X,___X__X_,
  ___X___X,___X__X_,
  ___X__X_,___X__X_,
  ___X__X_,____XXX_,
  ___X_X__,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_6B21[ 32] = { /* code 6B21 */
  ________,X_______,
  _X______,X_______,
  __X_____,X_______,
  __X_____,XXXXXX__,
  _______X,_____X__,
  ____X__X,____X___,
  ____X_X_,_X______,
  ___X_X__,_X______,
  ___X____,_X______,
  XXX_____,X_X_____,
  __X_____,X_X_____,
  __X____X,___X____,
  __X____X,___X____,
  __X___X_,____X___,
  __X__X__,_____X__,
  ____X___,______X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_6D88[ 32] = { /* code 6D88 */
  ________,_X______,
  __X___X_,_X__X___,
  ___X___X,_X__X___,
  ___X___X,_X_X____,
  X_______,_X______,
  _X____XX,XXXXX___,
  _X__X_X_,____X___,
  ____X_X_,____X___,
  ___X__XX,XXXXX___,
  ___X__X_,____X___,
  XXX___X_,____X___,
  __X___XX,XXXXX___,
  __X___X_,____X___,
  __X___X_,____X___,
  __X___X_,__X_X___,
  ______X_,___X____};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_6DF1[ 32] = { /* code 6DF1 */
  ________,________,
  __X__XXX,XXXXXX__,
  ___X_X__,_____X__,
  ___X_X__,X_X__X__,
  X______X,___X____,
  _X____X_,____X___,
  _X______,_X______,
  ___X____,_X______,
  ___X_XXX,XXXXXX__,
  __X_____,_X______,
  XXX_____,XXX_____,
  __X____X,_X_X____,
  __X___X_,_X__X___,
  __X_XX__,_X___XX_,
  __X_____,_X______,
  ________,_X______};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_7535[ 32] = { /* code 7535 */
  _______X,________,
  _______X,________,
  _______X,________,
  __XXXXXX,XXXXX___,
  __X____X,____X___,
  __X____X,____X___,
  __X____X,____X___,
  __XXXXXX,XXXXX___,
  __X____X,____X___,
  __X____X,____X___,
  __X____X,____X___,
  __XXXXXX,XXXXX___,
  __X____X,____X_X_,
  _______X,______X_,
  _______X,______X_,
  ________,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_786E[ 32] = { /* code 786E */
  ________,_X______,
  ________,_X______,
  XXXXXX__,_XXXXX__,
  ___X____,X____X__,
  ___X___X,____X___,
  __X___X_,XXXXXXX_,
  __XXXX__,X__X__X_,
  _XX__X__,X__X__X_,
  _XX__X__,XXXXXXX_,
  X_X__X__,X__X__X_,
  __X__X__,X__X__X_,
  __X__X__,XXXXXXX_,
  __XXXX__,X__X__X_,
  __X__X_X,___X__X_,
  __X____X,____X_X_,
  ______X_,_____X__};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_884C[ 32] = { /* code 884C */
  ____X___,________,
  ____X__X,XXXXXX__,
  ___X____,________,
  __X_____,________,
  _X__X___,________,
  ____X___,________,
  ___X__XX,XXXXXXX_,
  __XX____,__X_____,
  _X_X____,__X_____,
  X__X____,__X_____,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X____,X_X_____,
  ___X____,_X______};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_8BA4[ 32] = { /* code 8BA4 */
  ________,_X______,
  __X_____,_X______,
  ___X____,_X______,
  ___X____,_X______,
  ________,_X______,
  ________,_X______,
  XXXX____,_X______,
  ___X____,_X______,
  ___X____,X_X_____,
  ___X____,X_X_____,
  ___X____,X_X_____,
  ___X_X_X,___X____,
  ___XX__X,___X____,
  ___X__X_,____X___,
  _____X__,_____X__,
  ____X___,______X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_8DDD[ 32] = { /* code 8DDD */
  ________,________,
  _XXXXX_X,XXXXXXX_,
  _X___X_X,________,
  _X___X_X,________,
  _X___X_X,________,
  _XXXXX_X,XXXXXX__,
  ___X___X,_____X__,
  ___X___X,_____X__,
  _X_XXX_X,_____X__,
  _X_X___X,_____X__,
  _X_X___X,XXXXXX__,
  _X_X___X,________,
  _X_XXX_X,________,
  XXX____X,________,
  _______X,XXXXXXX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_8F6C[ 32] = { /* code 8F6C */
  __X_____,__X_____,
  __X_____,__X_____,
  __X_____,__X_____,
  XXXXXX_X,XXXXXX__,
  _X______,__X_____,
  _X_X____,_X______,
  X__X__XX,XXXXXXX_,
  XXXXXX__,_X______,
  ___X____,X_______,
  ___X___X,XXXXXX__,
  ___XXX__,_____X__,
  XXXX____,X___X___,
  _X_X____,_X_X____,
  ___X____,__X_____,
  ___X____,___X____,
  ___X____,___X____};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_901F[ 32] = { /* code 901F */
  ________,_X______,
  __X_____,_X______,
  ___X_XXX,XXXXXX__,
  ___X____,_X______,
  ______XX,XXXXX___,
  ______X_,_X__X___,
  XXXX__X_,_X__X___,
  ___X__XX,XXXXX___,
  ___X____,XXX_____,
  ___X___X,_X_X____,
  ___X__X_,_X__X___,
  ___X_X__,_X___X__,
  ___X____,_X______,
  __X_X___,________,
  _X___XXX,XXXXXXX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_9488[ 32] = { /* code 9488 */
  ___X____,__X_____,
  ___X____,__X_____,
  ___XXXX_,__X_____,
  __X_____,__X_____,
  __X_____,__X_____,
  _XXXXX__,__X_____,
  X__X__XX,XXXXXXX_,
  ___X____,__X_____,
  XXXXXXX_,__X_____,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X__X_,__X_____,
  ___X_X__,__X_____,
  ___XX___,__X_____,
  ___X____,__X_____,
  ________,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_94BB[ 32] = { /* code 94BB */
  ___X____,__X_____,
  ___X____,__X_____,
  __XXXX__,__X_____,
  __X_____,__X_____,
  _X______,__XXXXX_,
  X_XXXX__,__X_____,
  ___X____,__X_____,
  ___X____,__X_____,
  XXXXXX_X,XXXXXX__,
  ___X___X,_____X__,
  ___X___X,_____X__,
  ___X___X,_____X__,
  ___X_X_X,_____X__,
  ___XX__X,_____X__,
  ___X___X,XXXXXX__,
  _______X,_____X__};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_95F4[ 32] = { /* code 95F4 */
  __X_____,________,
  ___X__XX,XXXXXX__,
  ___X____,_____X__,
  _X______,_____X__,
  _X___XXX,XX___X__,
  _X___X__,_X___X__,
  _X___X__,_X___X__,
  _X___X__,_X___X__,
  _X___XXX,XX___X__,
  _X___X__,_X___X__,
  _X___X__,_X___X__,
  _X___X__,_X___X__,
  _X___XXX,XX___X__,
  _X______,_____X__,
  _X______,___X_X__,
  _X______,____X___};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Fontfont12_CharInfo[30] = {
   {  16,  16,  2, acGUI_Fontfont12_4F4D } /* code 4F4D */
  ,{  16,  16,  2, acGUI_Fontfont12_5076 } /* code 5076 */
  ,{  16,  16,  2, acGUI_Fontfont12_52A8 } /* code 52A8 */
  ,{  16,  16,  2, acGUI_Fontfont12_53D6 } /* code 53D6 */
  ,{  16,  16,  2, acGUI_Fontfont12_5927 } /* code 5927 */
  ,{  16,  16,  2, acGUI_Fontfont12_5934 } /* code 5934 */
  ,{  16,  16,  2, acGUI_Fontfont12_5947 } /* code 5947 */
  ,{  16,  16,  2, acGUI_Fontfont12_5B54 } /* code 5B54 */
  ,{  16,  16,  2, acGUI_Fontfont12_5B9A } /* code 5B9A */
  ,{  16,  16,  2, acGUI_Fontfont12_5C0F } /* code 5C0F */
  ,{  16,  16,  2, acGUI_Fontfont12_5EA6 } /* code 5EA6 */
  ,{  16,  16,  2, acGUI_Fontfont12_6253 } /* code 6253 */
  ,{  16,  16,  2, acGUI_Fontfont12_6269 } /* code 6269 */
  ,{  16,  16,  2, acGUI_Fontfont12_62CD } /* code 62CD */
  ,{  16,  16,  2, acGUI_Fontfont12_6392 } /* code 6392 */
  ,{  16,  16,  2, acGUI_Fontfont12_6570 } /* code 6570 */
  ,{  16,  16,  2, acGUI_Fontfont12_673A } /* code 673A */
  ,{  16,  16,  2, acGUI_Fontfont12_6B21 } /* code 6B21 */
  ,{  16,  16,  2, acGUI_Fontfont12_6D88 } /* code 6D88 */
  ,{  16,  16,  2, acGUI_Fontfont12_6DF1 } /* code 6DF1 */
  ,{  16,  16,  2, acGUI_Fontfont12_7535 } /* code 7535 */
  ,{  16,  16,  2, acGUI_Fontfont12_786E } /* code 786E */
  ,{  16,  16,  2, acGUI_Fontfont12_884C } /* code 884C */
  ,{  16,  16,  2, acGUI_Fontfont12_8BA4 } /* code 8BA4 */
  ,{  16,  16,  2, acGUI_Fontfont12_8DDD } /* code 8DDD */
  ,{  16,  16,  2, acGUI_Fontfont12_8F6C } /* code 8F6C */
  ,{  16,  16,  2, acGUI_Fontfont12_901F } /* code 901F */
  ,{  16,  16,  2, acGUI_Fontfont12_9488 } /* code 9488 */
  ,{  16,  16,  2, acGUI_Fontfont12_94BB } /* code 94BB */
  ,{  16,  16,  2, acGUI_Fontfont12_95F4 } /* code 95F4 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont12_Prop30 = {
   0x95F4 /* first character */
  ,0x95F4 /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 29] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont12_Prop29 = {
   0x94BB /* first character */
  ,0x94BB /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 28] /* address of first character */
  ,&GUI_Fontfont12_Prop30 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont12_Prop28 = {
   0x9488 /* first character */
  ,0x9488 /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 27] /* address of first character */
  ,&GUI_Fontfont12_Prop29 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont12_Prop27 = {
   0x901F /* first character */
  ,0x901F /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 26] /* address of first character */
  ,&GUI_Fontfont12_Prop28 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont12_Prop26 = {
   0x8F6C /* first character */
  ,0x8F6C /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 25] /* address of first character */
  ,&GUI_Fontfont12_Prop27 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont12_Prop25 = {
   0x8DDD /* first character */
  ,0x8DDD /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 24] /* address of first character */
  ,&GUI_Fontfont12_Prop26 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont12_Prop24 = {
   0x8BA4 /* first character */
  ,0x8BA4 /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 23] /* address of first character */
  ,&GUI_Fontfont12_Prop25 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont12_Prop23 = {
   0x884C /* first character */
  ,0x884C /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 22] /* address of first character */
  ,&GUI_Fontfont12_Prop24 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont12_Prop22 = {
   0x786E /* first character */
  ,0x786E /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 21] /* address of first character */
  ,&GUI_Fontfont12_Prop23 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont12_Prop21 = {
   0x7535 /* first character */
  ,0x7535 /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 20] /* address of first character */
  ,&GUI_Fontfont12_Prop22 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont12_Prop20 = {
   0x6DF1 /* first character */
  ,0x6DF1 /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 19] /* address of first character */
  ,&GUI_Fontfont12_Prop21 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont12_Prop19 = {
   0x6D88 /* first character */
  ,0x6D88 /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 18] /* address of first character */
  ,&GUI_Fontfont12_Prop20 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont12_Prop18 = {
   0x6B21 /* first character */
  ,0x6B21 /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 17] /* address of first character */
  ,&GUI_Fontfont12_Prop19 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont12_Prop17 = {
   0x673A /* first character */
  ,0x673A /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 16] /* address of first character */
  ,&GUI_Fontfont12_Prop18 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont12_Prop16 = {
   0x6570 /* first character */
  ,0x6570 /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 15] /* address of first character */
  ,&GUI_Fontfont12_Prop17 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont12_Prop15 = {
   0x6392 /* first character */
  ,0x6392 /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 14] /* address of first character */
  ,&GUI_Fontfont12_Prop16 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont12_Prop14 = {
   0x62CD /* first character */
  ,0x62CD /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 13] /* address of first character */
  ,&GUI_Fontfont12_Prop15 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont12_Prop13 = {
   0x6269 /* first character */
  ,0x6269 /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 12] /* address of first character */
  ,&GUI_Fontfont12_Prop14 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont12_Prop12 = {
   0x6253 /* first character */
  ,0x6253 /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 11] /* address of first character */
  ,&GUI_Fontfont12_Prop13 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont12_Prop11 = {
   0x5EA6 /* first character */
  ,0x5EA6 /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 10] /* address of first character */
  ,&GUI_Fontfont12_Prop12 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont12_Prop10 = {
   0x5C0F /* first character */
  ,0x5C0F /* last character  */
  ,&GUI_Fontfont12_CharInfo[  9] /* address of first character */
  ,&GUI_Fontfont12_Prop11 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont12_Prop9 = {
   0x5B9A /* first character */
  ,0x5B9A /* last character  */
  ,&GUI_Fontfont12_CharInfo[  8] /* address of first character */
  ,&GUI_Fontfont12_Prop10 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont12_Prop8 = {
   0x5B54 /* first character */
  ,0x5B54 /* last character  */
  ,&GUI_Fontfont12_CharInfo[  7] /* address of first character */
  ,&GUI_Fontfont12_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont12_Prop7 = {
   0x5947 /* first character */
  ,0x5947 /* last character  */
  ,&GUI_Fontfont12_CharInfo[  6] /* address of first character */
  ,&GUI_Fontfont12_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont12_Prop6 = {
   0x5934 /* first character */
  ,0x5934 /* last character  */
  ,&GUI_Fontfont12_CharInfo[  5] /* address of first character */
  ,&GUI_Fontfont12_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont12_Prop5 = {
   0x5927 /* first character */
  ,0x5927 /* last character  */
  ,&GUI_Fontfont12_CharInfo[  4] /* address of first character */
  ,&GUI_Fontfont12_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont12_Prop4 = {
   0x53D6 /* first character */
  ,0x53D6 /* last character  */
  ,&GUI_Fontfont12_CharInfo[  3] /* address of first character */
  ,&GUI_Fontfont12_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont12_Prop3 = {
   0x52A8 /* first character */
  ,0x52A8 /* last character  */
  ,&GUI_Fontfont12_CharInfo[  2] /* address of first character */
  ,&GUI_Fontfont12_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont12_Prop2 = {
   0x5076 /* first character */
  ,0x5076 /* last character  */
  ,&GUI_Fontfont12_CharInfo[  1] /* address of first character */
  ,&GUI_Fontfont12_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont12_Prop1 = {
   0x4F4D /* first character */
  ,0x4F4D /* last character  */
  ,&GUI_Fontfont12_CharInfo[  0] /* address of first character */
  ,&GUI_Fontfont12_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontfont12 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,16 /* height of font  */
  ,16 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontfont12_Prop1}
  ,14 /* Baseline */
  ,7 /* Height of lowercase characters */
  ,11 /* Height of capital characters */
};

