/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font Converter for emWin version 5.28                       *
*        Compiled Jan 30 2015, 16:40:45                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: font16.c                                              *
* Font:        ËÎÌו                                                  *
* Height:      21                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  21                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: E:\GitHub\wireless-human-computer-interaction-system\Client\TEXT\font16.txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontfont16;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Fontfont16_5236[ 63] = { /* code 5236 */
  ________,________,________,
  ______X_,________,__X_____,
  ______X_,________,__X_____,
  ___X__X_,________,__X_____,
  ___X__X_,______X_,__X_____,
  ___XXXXX,XXX___X_,__X_____,
  __X___X_,______X_,__X_____,
  __X___X_,______X_,__X_____,
  __XXXXXX,XXXX__X_,__X_____,
  ______X_,______X_,__X_____,
  __XXXXXX,XXXX__X_,__X_____,
  __X___X_,__X___X_,__X_____,
  __X___X_,__X___X_,__X_____,
  __X___X_,__X___X_,__X_____,
  __X___X_,__X___X_,__X_____,
  __X___X_,X_X_____,__X_____,
  __X___X_,_XX_____,__X_____,
  ______X_,________,__X_____,
  ______X_,_______X,XXX_____,
  ______X_,________,_X______,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont16_5668[ 63] = { /* code 5668 */
  ________,________,________,
  ________,________,________,
  ____XXXX,X___XXXX,X_______,
  ____X___,X___X___,X_______,
  ____X___,X___X___,X_______,
  ____X___,X___X___,X_______,
  ____XXXX,X___XXXX,X_______,
  ____X___,XX__XX__,X_______,
  ________,_XX___XX,________,
  _XXXXXXX,XXXXXXXX,XXX_____,
  ________,X___X___,________,
  _______X,_____X__,________,
  _____XX_,______XX,________,
  ____XXXX,XX_XXXXX,XXXX____,
  __XXX___,X__X____,X_X_____,
  ____X___,X__X____,X_______,
  ____X___,X__X____,X_______,
  ____XXXX,X__XXXXX,X_______,
  ____X___,X__X____,X_______,
  ____X___,___X____,X_______,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont16_5E8A[ 63] = { /* code 5E8A */
  ________,________,________,
  ________,__X_____,________,
  ________,___X____,________,
  ________,___X____,________,
  ___XXXXX,XXX_XXXX,XXX_____,
  ___X____,___X____,________,
  ___X____,___X____,________,
  ___X____,___X____,________,
  ___XXXXX,XX_X_XXX,XXX_____,
  ___X____,__XXX___,________,
  ___X____,_X_X_X__,________,
  ___X____,_X_X_X__,________,
  ___X____,X__X__X_,________,
  ___X___X,___X__X_,________,
  __X____X,___X___X,________,
  __X___X_,___X____,XX______,
  __X__X__,___X____,XXXX____,
  _X__X___,___X____,________,
  _X_X____,___X____,________,
  ________,___X____,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont16_624B[ 63] = { /* code 624B */
  ________,________,________,
  ________,_______X,X_______,
  ________,___XXXXX,X_______,
  ___XXXXX,XXX_____,________,
  ________,__X_____,________,
  ________,__X_____,________,
  ________,__X_____,X_______,
  ___XXXXX,XXXXXXXX,XX______,
  ________,__X_____,________,
  ________,__X_____,________,
  ________,__X_____,__X_____,
  _XXXXXXX,XXXXXXXX,XXXX____,
  ________,__X_____,________,
  ________,__X_____,________,
  ________,__X_____,________,
  ________,__X_____,________,
  ________,__X_____,________,
  ________,__X_____,________,
  _______X,XXX_____,________,
  ________,_X______,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont16_6301[ 63] = { /* code 6301 */
  ________,________,________,
  ____X___,_____X__,________,
  ____XX__,_____X__,________,
  ____XX__,_____X__,________,
  ____XX__,XXXXXXXX,XX______,
  _XXXXXXX,_____X__,________,
  ____XX__,_____X__,________,
  ____XX__,_____X__,________,
  ____XX_X,XXXXXXXX,XXXX____,
  ____XXXX,_______X,X_______,
  ____XX__,_______X,________,
  _XXXXX__,XXXXXXXX,XXX_____,
  __X_XX__,_______X,________,
  ____XX__,_X_____X,________,
  ____XX__,__X____X,________,
  ____XX__,__XX___X,________,
  ____XX__,_______X,________,
  ____XX__,_______X,________,
  ___XX___,____XXXX,________,
  ____X___,______X_,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont16_63A7[ 63] = { /* code 63A7 */
  ________,________,________,
  ____X___,________,________,
  ____X___,____XX__,________,
  ____X___,_____XX_,________,
  ____X___,_XXXXXXX,XXX_____,
  _XXXXXXX,_X______,__X_____,
  ____X___,X_______,_X______,
  ____X___,___XX__X,________,
  ____X___,__XX____,XX______,
  ____X_XX,_X______,_XX_____,
  ____XX__,X_______,__X_____,
  __XXX___,_XXXXXXX,XX______,
  _XX_X___,_____X__,________,
  ____X___,_____X__,________,
  ____X___,_____X__,________,
  ____X___,_____X__,________,
  ____X___,_____X__,__X_____,
  ____X__X,XXXXXXXX,XXXX____,
  __XXX___,________,________,
  ____X___,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont16_94BB[ 63] = { /* code 94BB */
  ________,________,________,
  ____X___,_____X__,________,
  ____XX__,_____X__,________,
  ____X___,X____X__,________,
  ____XXXX,X____X__,________,
  ___X____,_____X__,__X_____,
  ___X____,_____XXX,XXXX____,
  __X_____,_____X__,________,
  __XXXXXX,X____X__,________,
  _X__XX__,_____X__,________,
  ____XX__,_____X__,________,
  __XXXXXX,XXXXXXXX,XXX_____,
  ____XX__,__X_____,_X______,
  ____XX__,__X_____,_X______,
  ____XX__,__X_____,_X______,
  ____XX_X,X_X_____,_X______,
  ____XXX_,__X_____,_X______,
  ____XX__,__XXXXXX,XX______,
  ____XX__,__X_____,_X______,
  ________,__X_____,_X______,
  ________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Fontfont16_CharInfo[7] = {
   {  21,  21,  3, acGUI_Fontfont16_5236 } /* code 5236 */
  ,{  21,  21,  3, acGUI_Fontfont16_5668 } /* code 5668 */
  ,{  21,  21,  3, acGUI_Fontfont16_5E8A } /* code 5E8A */
  ,{  21,  21,  3, acGUI_Fontfont16_624B } /* code 624B */
  ,{  21,  21,  3, acGUI_Fontfont16_6301 } /* code 6301 */
  ,{  21,  21,  3, acGUI_Fontfont16_63A7 } /* code 63A7 */
  ,{  21,  21,  3, acGUI_Fontfont16_94BB } /* code 94BB */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont16_Prop7 = {
   0x94BB /* first character */
  ,0x94BB /* last character  */
  ,&GUI_Fontfont16_CharInfo[  6] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont16_Prop6 = {
   0x63A7 /* first character */
  ,0x63A7 /* last character  */
  ,&GUI_Fontfont16_CharInfo[  5] /* address of first character */
  ,&GUI_Fontfont16_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont16_Prop5 = {
   0x6301 /* first character */
  ,0x6301 /* last character  */
  ,&GUI_Fontfont16_CharInfo[  4] /* address of first character */
  ,&GUI_Fontfont16_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont16_Prop4 = {
   0x624B /* first character */
  ,0x624B /* last character  */
  ,&GUI_Fontfont16_CharInfo[  3] /* address of first character */
  ,&GUI_Fontfont16_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont16_Prop3 = {
   0x5E8A /* first character */
  ,0x5E8A /* last character  */
  ,&GUI_Fontfont16_CharInfo[  2] /* address of first character */
  ,&GUI_Fontfont16_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont16_Prop2 = {
   0x5668 /* first character */
  ,0x5668 /* last character  */
  ,&GUI_Fontfont16_CharInfo[  1] /* address of first character */
  ,&GUI_Fontfont16_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont16_Prop1 = {
   0x5236 /* first character */
  ,0x5236 /* last character  */
  ,&GUI_Fontfont16_CharInfo[  0] /* address of first character */
  ,&GUI_Fontfont16_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontfont16 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,21 /* height of font  */
  ,21 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontfont16_Prop1}
  ,18 /* Baseline */
  ,10 /* Height of lowercase characters */
  ,14 /* Height of capital characters */
};

