/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font Converter for emWin version 5.28                       *
*        Compiled Jan 30 2015, 16:40:45                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: font14.c                                              *
* Font:        Î¢ÈíÑÅºÚ                                              *
* Height:      25                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  25                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: E:\GitHub\wireless-human-computer-interaction-system\Client\TEXT\font12.txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontfont14;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Fontfont14_4E0A[ 51] = { /* code 4E0A */
  ________,X_______,________,
  ________,X_______,________,
  ________,X_______,________,
  ________,X_______,________,
  ________,X_______,________,
  ________,X_______,________,
  ________,XXXXXXXX,XX______,
  ________,X_______,________,
  ________,X_______,________,
  ________,X_______,________,
  ________,X_______,________,
  ________,X_______,________,
  ________,X_______,________,
  ________,X_______,________,
  ________,X_______,________,
  ________,X_______,________,
  XXXXXXXX,XXXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont14_4E0B[ 51] = { /* code 4E0B */
  XXXXXXXX,XXXXXXXX,XXX_____,
  ________,X_______,________,
  ________,X_______,________,
  ________,X_______,________,
  ________,X_______,________,
  ________,XXX_____,________,
  ________,X_XXX___,________,
  ________,X___XX__,________,
  ________,X____XXX,________,
  ________,X______X,X_______,
  ________,X_______,XX______,
  ________,X_______,________,
  ________,X_______,________,
  ________,X_______,________,
  ________,X_______,________,
  ________,X_______,________,
  ________,X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont14_4F4D[ 54] = { /* code 4F4D */
  _____X__,___X____,________,
  _____X__,___XX___,________,
  ____X___,____X___,________,
  ____X___,____X___,________,
  ___X__XX,XXXXXXXX,XX______,
  ___X____,________,________,
  __XX___X,________,X_______,
  __XX___X,X_______,X_______,
  _XXX____,X______X,________,
  XX_X____,X______X,________,
  X__X____,_X_____X,________,
  ___X____,_X____X_,________,
  ___X____,_X____X_,________,
  ___X____,__X___X_,________,
  ___X____,__X__X__,________,
  ___X____,_____X__,________,
  ___X_XXX,XXXXXXXX,XX______,
  ___X____,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont14_5076[ 54] = { /* code 5076 */
  ____X___,________,________,
  ____X_XX,XXXXXXXX,________,
  ___X__X_,___X___X,________,
  ___X__X_,___X___X,________,
  __X___XX,XXXXXXXX,________,
  __X___X_,___X___X,________,
  _XX___X_,___X___X,________,
  _XX___XX,XXXXXXXX,________,
  X_X___X_,___X___X,________,
  X_X_____,___X____,________,
  __X__XXX,XXXXXXXX,X_______,
  __X__X__,___X____,X_______,
  __X__X__,___X_X__,X_______,
  __X__X__,___X_X__,X_______,
  __X__X_X,XXXXX_X_,X_______,
  __X__X__,______X_,X_______,
  __X__X__,________,X_______,
  __X__X__,_____XXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont14_52A8[ 54] = { /* code 52A8 */
  ________,___X____,________,
  _XXXXXXX,___X____,________,
  ________,___X____,________,
  ________,XXXXXXXX,X_______,
  ________,___X___X,X_______,
  ________,___X___X,X_______,
  XXXXXXXX,X__X___X,X_______,
  ___X____,___X___X,________,
  ___X____,___X___X,________,
  __X__X__,___X___X,________,
  __X__XX_,__XX___X,________,
  __X___X_,__X____X,________,
  _X____X_,__X____X,________,
  _X__XXXX,__X____X,________,
  XXXX___X,_X_____X,________,
  ________,XX_____X,________,
  ________,X___XXX_,________,
  _______X,X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont14_5347[ 54] = { /* code 5347 */
  ________,_____X__,________,
  ______XX,XXX__X__,________,
  XXXXXX__,_____X__,________,
  _____X__,_____X__,________,
  _____X__,_____X__,________,
  _____X__,_____X__,________,
  _____X__,_____X__,________,
  _____X__,_____X__,________,
  XXXXXXXX,XXXXXXXX,XXX_____,
  _____X__,_____X__,________,
  _____X__,_____X__,________,
  _____X__,_____X__,________,
  _____X__,_____X__,________,
  ____XX__,_____X__,________,
  ____X___,_____X__,________,
  ___XX___,_____X__,________,
  __XX____,_____X__,________,
  _XX_____,_____X__,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont14_53D6[ 51] = { /* code 53D6 */
  XXXXXXXX,XXXXXXXX,XX______,
  __X____X,___X____,_X______,
  __X____X,___X____,_X______,
  __X____X,___X____,_X______,
  __XXXXXX,___X____,X_______,
  __X____X,____X___,X_______,
  __X____X,____X___,X_______,
  __X____X,____X___,X_______,
  __XXXXXX,____X__X,________,
  __X____X,_____X_X,________,
  __X____X,_____XXX,________,
  __X____X,_____XX_,________,
  __X_XXXX,XX___XX_,________,
  XXXX___X,___XXX_X,________,
  _______X,__XX____,X_______,
  _______X,_XX_____,XX______,
  _______X,XX______,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont14_5927[ 54] = { /* code 5927 */
  ________,X_______,________,
  ________,X_______,________,
  ________,X_______,________,
  ________,X_______,________,
  ________,X_______,________,
  XXXXXXXX,XXXXXXXX,X_______,
  ________,X_______,________,
  ________,X_______,________,
  ________,X_______,________,
  _______X,_X______,________,
  _______X,_X______,________,
  ______XX,__X_____,________,
  ______X_,__X_____,________,
  _____X__,___X____,________,
  ____XX__,___XX___,________,
  ___XX___,____XX__,________,
  _XX_____,_____XX_,________,
  XX______,_______X,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont14_5934[ 54] = { /* code 5934 */
  ________,_X______,________,
  ___XX___,_X______,________,
  ____XX__,_X______,________,
  _____XX_,_X______,________,
  ______XX,_X______,________,
  _XX_____,_X______,________,
  __XXX___,_X______,________,
  ____XX__,_X______,________,
  _____XX_,_X______,________,
  ________,_X______,________,
  ________,_X______,________,
  XXXXXXXX,XXXXXXXX,XX______,
  ________,_X______,________,
  ________,XXX_____,________,
  _______X,X_XX____,________,
  _____XXX,____XX__,________,
  ___XXX__,______XX,________,
  XXX_____,_______X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont14_5947[ 54] = { /* code 5947 */
  ________,X_______,________,
  ________,X_______,________,
  _XXXXXXX,XXXXXXXX,________,
  _______X,X_______,________,
  ______X_,XXXX____,________,
  ____XX__,___XXX__,________,
  _XXX____,_____XX_,________,
  ________,________,________,
  XXXXXXXX,XXXXXXXX,X_______,
  ________,_____X__,________,
  ________,_____X__,________,
  __XXXXXX,X____X__,________,
  __X_____,X____X__,________,
  __X_____,X____X__,________,
  __XXXXXX,X____X__,________,
  __X_____,_____X__,________,
  ________,_____X__,________,
  ________,_XXXX___,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont14_5B54[ 51] = { /* code 5B54 */
  ________,___X____,________,
  _XXXXXXX,X__X____,________,
  _______X,X__X____,________,
  ______XX,___X____,________,
  ______XX,___X____,________,
  _____XX_,___X____,________,
  _____X__,___X____,________,
  _____X__,XX_X____,________,
  _____XXX,___X____,________,
  __XXXX__,___X____,________,
  XX___X__,___X____,________,
  _____X__,___X____,_X______,
  _____X__,___X____,_X______,
  _____X__,___X____,_X______,
  _____X__,___X____,_X______,
  _____X__,___X____,XX______,
  _XXXX___,____XXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont14_5B9A[ 54] = { /* code 5B9A */
  ________,X_______,________,
  ________,XX______,________,
  _XXXXXXX,XXXXXXXX,X_______,
  _X______,________,X_______,
  _X______,________,X_______,
  ________,________,________,
  XXXXXXXX,XXXXXXXX,XX______,
  ________,_X______,________,
  ____X___,_X______,________,
  ____X___,_X______,________,
  ____X___,_X______,________,
  ___X____,_XXXXXXX,________,
  ___XX___,_X______,________,
  ___XX___,_X______,________,
  __X_XX__,_X______,________,
  __X__XXX,_X______,________,
  _X_____X,XXXXXXXX,XX______,
  X_______,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont14_5C0F[ 51] = { /* code 5C0F */
  ________,_X______,________,
  ________,_X______,________,
  ________,_X______,________,
  ________,_X______,________,
  ____X___,_X___X__,________,
  ___XX___,_X____X_,________,
  ___X____,_X____XX,________,
  ___X____,_X_____X,________,
  __X_____,_X_____X,X_______,
  __X_____,_X______,X_______,
  _X______,_X______,_X______,
  XX______,_X______,_XX_____,
  X_______,_X______,__X_____,
  ________,_X______,________,
  ________,_X______,________,
  ________,_X______,________,
  ____XXXX,X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont14_5EA6[ 54] = { /* code 5EA6 */
  ________,_X______,________,
  ________,__X_____,________,
  __XXXXXX,XXXXXXXX,XX______,
  __X_____,________,________,
  __X____X,_____X__,________,
  __XXXXXX,XXXXXXXX,XX______,
  __X____X,_____X__,________,
  __X____X,_____X__,________,
  __X____X,XXXXXX__,________,
  __X____X,_____X__,________,
  __X_____,________,________,
  __X_XXXX,XXXXXXXX,________,
  __X___X_,_____XX_,________,
  __X____X,X___XX__,________,
  _X______,XXXX____,________,
  _X______,XX_XX___,________,
  XX___XXX,____XXX_,________,
  X__XXX__,_______X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont14_6253[ 51] = { /* code 6253 */
  ___X____,________,________,
  ___X___X,XXXXXXXX,X_______,
  ___X____,_____X__,________,
  XXXXXXX_,_____X__,________,
  ___X____,_____X__,________,
  ___X____,_____X__,________,
  ___X____,_____X__,________,
  ___X__X_,_____X__,________,
  ___XXX__,_____X__,________,
  _XXX____,_____X__,________,
  X__X____,_____X__,________,
  ___X____,_____X__,________,
  ___X____,_____X__,________,
  ___X____,_____X__,________,
  ___X____,_____X__,________,
  ___X____,_____X__,________,
  _XXX____,_XXXX___,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont14_6269[ 51] = { /* code 6269 */
  ___X____,____X___,________,
  ___X____,____XX__,________,
  ___X____,_____X__,________,
  ___X____,XXXXXXXX,XXX_____,
  XXXXXXX_,X_______,________,
  ___X____,X_______,________,
  ___X____,X_______,________,
  ___X____,X_______,________,
  ___X_XX_,X_______,________,
  __XXX___,X_______,________,
  XX_X____,X_______,________,
  ___X____,X_______,________,
  ___X___X,________,________,
  ___X___X,________,________,
  ___X__XX,________,________,
  ___X_XX_,________,________,
  XXXX_X__,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont14_62CD[ 54] = { /* code 62CD */
  ___X____,___X____,________,
  ___X____,__X_____,________,
  ___X____,__X_____,________,
  ___X___X,XXXXXXXX,X_______,
  XXXXXX_X,________,X_______,
  ___X___X,________,X_______,
  ___X___X,________,X_______,
  ___X___X,________,X_______,
  ___XXX_X,________,X_______,
  __XX___X,XXXXXXXX,X_______,
  XX_X___X,________,X_______,
  ___X___X,________,X_______,
  ___X___X,________,X_______,
  ___X___X,________,X_______,
  ___X___X,________,X_______,
  ___X___X,________,X_______,
  ___X___X,XXXXXXXX,X_______,
  XXX____X,________,X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont14_6392[ 54] = { /* code 6392 */
  __X_____,X___X___,________,
  __X_____,X___X___,________,
  __X_____,X___X___,________,
  __X_____,X___X___,________,
  XXXXXXXX,X___XXXX,XX______,
  __X_____,X___X___,________,
  __X_____,X___X___,________,
  __X_____,X___X___,________,
  __X_XXXX,X___XXXX,X_______,
  __XX____,X___X___,________,
  _XX_____,X___X___,________,
  X_X_____,X___X___,________,
  __X_____,X___X___,________,
  __X_XXXX,X___XXXX,XX______,
  __X_____,X___X___,________,
  __X_____,X___X___,________,
  __X_____,X___X___,________,
  XXX_____,X___X___,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont14_6570[ 57] = { /* code 6570 */
  _____X__,____X___,________,
  _X___X__,_X__X___,________,
  _XX__X__,X__XX___,________,
  __X__X_X,___X____,________,
  _____X__,___XXXXX,XX______,
  XXXXXXXX,X_XX____,X_______,
  ____XX__,__XX____,X_______,
  ___XXXX_,_XXX____,X_______,
  _XX__X_X,_X_X___X,X_______,
  XX___X__,X__XX__X,________,
  ____X___,___XX__X,________,
  XXXXXXXX,X___X_XX,________,
  __X_____,X___XXX_,________,
  _XX____X,____XXX_,________,
  __XXX__X,____XXX_,________,
  ____XXX_,____X_XX,________,
  ____XXXX,___XX_XX,________,
  __XX___X,X_XX___X,X_______,
  XX______,_XX_____,XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont14_673A[ 54] = { /* code 673A */
  ___X____,________,________,
  ___X____,_XXXXXX_,________,
  ___X____,_X____X_,________,
  XXXXXXX_,_X____X_,________,
  ___X____,_X____X_,________,
  ___X____,_X____X_,________,
  __XX____,_X____X_,________,
  __XXXX__,_X____X_,________,
  __XX_XX_,_X____X_,________,
  _X_X__XX,_X____X_,________,
  _X_X____,_X____X_,________,
  XX_X____,_X____X_,________,
  X__X____,_X____X_,__X_____,
  ___X____,X_____X_,__X_____,
  ___X____,X_____X_,__X_____,
  ___X___X,X_____X_,_XX_____,
  ___X___X,______XX,XX______,
  ___X__XX,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont14_6B21[ 54] = { /* code 6B21 */
  ________,_X______,________,
  _X______,_X______,________,
  _XX_____,X_______,________,
  __XX____,XXXXXXXX,XX______,
  ___XX__X,________,_X______,
  ____X__X,___X____,X_______,
  ______X_,___X____,X_______,
  ______X_,___X___X,________,
  ____X___,___X____,________,
  ____X___,__XXX___,________,
  ___X____,__X_X___,________,
  ___X____,__X_X___,________,
  __X_____,_X___X__,________,
  __X_____,XX___XX_,________,
  _X_____X,X_____XX,________,
  X_____XX,_______X,X_______,
  X___XX__,________,XX______,
  ___XX___,________,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont14_6D88[ 54] = { /* code 6D88 */
  XX___X__,___X____,X_______,
  _XX___X_,___X___X,X_______,
  __XX__XX,___X__XX,________,
  _______X,___X__X_,________,
  ________,___X____,________,
  X____XXX,XXXXXXXX,X_______,
  _X___X__,________,X_______,
  _X___X__,________,X_______,
  _____X__,________,X_______,
  _____XXX,XXXXXXXX,X_______,
  __X__X__,________,X_______,
  __X__X__,________,X_______,
  _X___X__,________,X_______,
  _X___XXX,XXXXXXXX,X_______,
  _X___X__,________,X_______,
  _X___X__,________,X_______,
  X____X__,________,X_______,
  X____X__,___XXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont14_6DF1[ 54] = { /* code 6DF1 */
  XX______,________,________,
  _XXX_XXX,XXXXXXXX,X_______,
  ___XXX__,________,X_______,
  _____X__,________,X_______,
  ________,_XX_XX__,________,
  X_______,XX___XX_,________,
  _XX___XX,X__X__XX,________,
  ______X_,___X___X,________,
  ________,___X____,________,
  _____XXX,XXXXXXXX,X_______,
  __X_____,__XXX___,________,
  __X_____,_XXXXX__,________,
  _XX_____,XX_X_X__,________,
  _X_____X,X__X__X_,________,
  _X____XX,___X__XX,X_______,
  _X__XXX_,___X___X,XX______,
  X____X__,___X____,X_______,
  X_______,___X____,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont14_7535[ 51] = { /* code 7535 */
  _______X,________,________,
  _______X,________,________,
  XXXXXXXX,XXXXXXX_,________,
  X______X,______X_,________,
  X______X,______X_,________,
  X______X,______X_,________,
  X______X,______X_,________,
  XXXXXXXX,XXXXXXX_,________,
  X______X,______X_,________,
  X______X,______X_,________,
  X______X,______X_,________,
  X______X,______X_,________,
  XXXXXXXX,XXXXXXX_,________,
  X______X,________,X_______,
  _______X,________,X_______,
  _______X,_______X,X_______,
  ________,XXXXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont14_786E[ 57] = { /* code 786E */
  ________,___X____,________,
  ________,__XX____,________,
  _XXXXXX_,_XXXXXXX,________,
  ___X____,XX____X_,________,
  ___X___X,X____X__,________,
  ___X__X_,XXXXXXXX,XX______,
  __X_____,X___X___,_X______,
  __XXXX__,X___X___,_X______,
  _XX__X__,X___X___,_X______,
  _XX__X__,XXXXXXXX,XX______,
  XXX__X__,X___X___,_X______,
  X_X__X__,X___X___,_X______,
  __X__X__,X___X___,_X______,
  __X__X__,XXXXXXXX,XX______,
  __X__X__,X___X___,_X______,
  __XXXX_X,X___X___,_X______,
  __X____X,____X___,_X______,
  _______X,____X_XX,XX______,
  ______X_,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont14_884C[ 51] = { /* code 884C */
  _____X__,________,________,
  ____XX_X,XXXXXXXX,X_______,
  ____X___,________,________,
  ___X____,________,________,
  __X__X__,________,________,
  _X__XX__,________,________,
  ____X___,________,________,
  ___X__XX,XXXXXXXX,XX______,
  __XX____,_____X__,________,
  __XX____,_____X__,________,
  _X_X____,_____X__,________,
  X__X____,_____X__,________,
  ___X____,_____X__,________,
  ___X____,_____X__,________,
  ___X____,_____X__,________,
  ___X____,_____X__,________,
  ___X____,_XXXX___,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont14_8BA4[ 54] = { /* code 8BA4 */
  __X_____,___X____,________,
  __XX____,___X____,________,
  ___XX___,___X____,________,
  ____XX__,___X____,________,
  _____X__,___X____,________,
  ________,___X____,________,
  XXXX____,___X____,________,
  ___X____,___X____,________,
  ___X____,___XX___,________,
  ___X____,__X_X___,________,
  ___X____,__X_X___,________,
  ___X__X_,__X_XX__,________,
  ___X_XX_,_X___X__,________,
  ___X_X__,_X___X__,________,
  ___XX___,X_____X_,________,
  ___X___X,X_____XX,________,
  ______XX,_______X,X_______,
  _____XX_,________,XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont14_8DDD[ 48] = { /* code 8DDD */
  _XXXXX__,XXXXXXXX,X_______,
  _X___X__,X_______,________,
  _X___X__,X_______,________,
  _X___X__,X_______,________,
  _XXXXX__,X_______,________,
  _X__X___,XXXXXXXX,________,
  ____X___,X______X,________,
  _X__X___,X______X,________,
  _X__X___,X______X,________,
  _X__XXX_,X______X,________,
  _X__X___,XXXXXXXX,________,
  _X__X___,X______X,________,
  _X__X___,X_______,________,
  _X__X_X_,X_______,________,
  _XXXXX__,X_______,________,
  XX______,XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont14_8F6C[ 57] = { /* code 8F6C */
  ____X___,____X___,________,
  ___X____,____X___,________,
  ___X____,____X___,________,
  XXXXXXXX,_XXXXXXX,X_______,
  __X_____,___X____,________,
  __X_X___,___X____,________,
  _X__X___,__X_____,________,
  _X__X___,XXXXXXXX,XX______,
  X___X___,__X_____,________,
  XXXXXXXX,_X______,________,
  ____X___,_X______,________,
  ____X___,_XXXXXXX,X_______,
  ____X___,_______X,X_______,
  ____XXXX,_X____XX,________,
  XXXXX___,__XX_XX_,________,
  ____X___,___XXX__,________,
  ____X___,____XX__,________,
  ____X___,_____XX_,________,
  ____X___,______XX,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont14_901F[ 54] = { /* code 901F */
  _X______,___X____,________,
  _XX_____,___X____,________,
  __X__XXX,XXXXXXXX,XX______,
  __XX____,___X____,________,
  ___X____,___X____,________,
  _______X,XXXXXXXX,X_______,
  _______X,___X____,X_______,
  XXX____X,___X____,X_______,
  __X____X,___X____,X_______,
  __X____X,XXXXXXXX,X_______,
  __X____X,__XX____,X_______,
  __X_____,_XXXXX__,________,
  __X_____,XX_X_XX_,________,
  __X___XX,___X___X,X_______,
  __X__XX_,___X____,XX______,
  _XX_____,___X____,________,
  XX_XX___,________,________,
  X___XXXX,XXXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont14_9488[ 54] = { /* code 9488 */
  ___X____,____X___,________,
  __XX____,____X___,________,
  __XX____,____X___,________,
  __XXXXXX,____X___,________,
  _XX_____,____X___,________,
  _X______,____X___,________,
  XXXXXXX_,____X___,________,
  ___X____,XXXXXXXX,XX______,
  ___X____,____X___,________,
  ___X____,____X___,________,
  XXXXXXXX,____X___,________,
  ___X____,____X___,________,
  ___X____,____X___,________,
  ___X____,____X___,________,
  ___X___X,____X___,________,
  ___X_XX_,____X___,________,
  ___XX___,____X___,________,
  __XX____,____X___,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont14_94BB[ 54] = { /* code 94BB */
  ___X____,___X____,________,
  __XX____,___X____,________,
  __X_____,___X____,________,
  _XXXXXX_,___X____,________,
  _X______,___XXXXX,XX______,
  X_______,___X____,________,
  XXXXXXX_,___X____,________,
  ___X____,___X____,________,
  ___X____,___X____,________,
  ___X____,___X____,________,
  XXXXXXX_,XXXXXXXX,X_______,
  ___X____,X_______,X_______,
  ___X____,X_______,X_______,
  ___X____,X_______,X_______,
  ___X____,X_______,X_______,
  ___X_XX_,X_______,X_______,
  ___XXX__,XXXXXXXX,X_______,
  __XX____,X_______,X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont14_95F4[ 36] = { /* code 95F4 */
  _X______,________,
  __XX_XXX,XXXXXXXX,
  ___X____,_______X,
  X_______,_______X,
  X_______,_______X,
  X___XXXX,XXXX___X,
  X___X___,___X___X,
  X___X___,___X___X,
  X___X___,___X___X,
  X___XXXX,XXXX___X,
  X___X___,___X___X,
  X___X___,___X___X,
  X___X___,___X___X,
  X___XXXX,XXXX___X,
  X___X___,_______X,
  X_______,_______X,
  X_______,_______X,
  X_______,___XXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont14_964D[ 54] = { /* code 964D */
  ________,_X______,________,
  XXXX____,XX______,________,
  X__X____,XXXXXXXX,________,
  X__X___X,XX____XX,________,
  X_X___XX,_XX__XX_,________,
  X_X___X_,__XXXX__,________,
  X_X_____,_XXXXXX_,________,
  X_X___XX,X______X,XX______,
  X__X____,___X____,________,
  X__X____,___X____,________,
  X__X__XX,XXXXXXXX,X_______,
  X__X____,___X____,________,
  X__X___X,___X____,________,
  XXX___X_,___X____,________,
  X_____XX,XXXXXXXX,X_______,
  X_______,___X____,________,
  X_______,___X____,________,
  X_______,___X____,________};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_Fontfont14_CharInfo[34] = {
   {  19,  17,   0,   4,  19, acGUI_Fontfont14_4E0A } /* code 4E0A */
  ,{  19,  17,   0,   5,  19, acGUI_Fontfont14_4E0B } /* code 4E0B */
  ,{  18,  18,   0,   4,  19, acGUI_Fontfont14_4F4D } /* code 4F4D */
  ,{  17,  18,   1,   4,  19, acGUI_Fontfont14_5076 } /* code 5076 */
  ,{  17,  18,   1,   4,  19, acGUI_Fontfont14_52A8 } /* code 52A8 */
  ,{  19,  18,   0,   4,  19, acGUI_Fontfont14_5347 } /* code 5347 */
  ,{  19,  17,   0,   5,  19, acGUI_Fontfont14_53D6 } /* code 53D6 */
  ,{  17,  18,   1,   4,  19, acGUI_Fontfont14_5927 } /* code 5927 */
  ,{  18,  18,   1,   4,  19, acGUI_Fontfont14_5934 } /* code 5934 */
  ,{  17,  18,   1,   4,  19, acGUI_Fontfont14_5947 } /* code 5947 */
  ,{  18,  17,   0,   4,  19, acGUI_Fontfont14_5B54 } /* code 5B54 */
  ,{  18,  18,   0,   4,  19, acGUI_Fontfont14_5B9A } /* code 5B9A */
  ,{  19,  17,   0,   4,  19, acGUI_Fontfont14_5C0F } /* code 5C0F */
  ,{  18,  18,   0,   4,  19, acGUI_Fontfont14_5EA6 } /* code 5EA6 */
  ,{  17,  17,   1,   4,  19, acGUI_Fontfont14_6253 } /* code 6253 */
  ,{  19,  17,   0,   4,  19, acGUI_Fontfont14_6269 } /* code 6269 */
  ,{  17,  18,   0,   4,  19, acGUI_Fontfont14_62CD } /* code 62CD */
  ,{  18,  18,   1,   4,  19, acGUI_Fontfont14_6392 } /* code 6392 */
  ,{  18,  19,   0,   4,  19, acGUI_Fontfont14_6570 } /* code 6570 */
  ,{  19,  18,   0,   4,  19, acGUI_Fontfont14_673A } /* code 673A */
  ,{  19,  18,   0,   4,  19, acGUI_Fontfont14_6B21 } /* code 6B21 */
  ,{  17,  18,   1,   4,  19, acGUI_Fontfont14_6D88 } /* code 6D88 */
  ,{  18,  18,   1,   4,  19, acGUI_Fontfont14_6DF1 } /* code 6DF1 */
  ,{  17,  17,   1,   4,  19, acGUI_Fontfont14_7535 } /* code 7535 */
  ,{  18,  19,   0,   3,  19, acGUI_Fontfont14_786E } /* code 786E */
  ,{  18,  17,   0,   5,  19, acGUI_Fontfont14_884C } /* code 884C */
  ,{  18,  18,   0,   4,  19, acGUI_Fontfont14_8BA4 } /* code 8BA4 */
  ,{  17,  16,   1,   5,  19, acGUI_Fontfont14_8DDD } /* code 8DDD */
  ,{  18,  19,   1,   4,  19, acGUI_Fontfont14_8F6C } /* code 8F6C */
  ,{  18,  18,   0,   4,  19, acGUI_Fontfont14_901F } /* code 901F */
  ,{  18,  18,   1,   4,  19, acGUI_Fontfont14_9488 } /* code 9488 */
  ,{  18,  18,   0,   4,  19, acGUI_Fontfont14_94BB } /* code 94BB */
  ,{  16,  18,   1,   4,  19, acGUI_Fontfont14_95F4 } /* code 95F4 */
  ,{  18,  18,   1,   4,  19, acGUI_Fontfont14_964D } /* code 964D */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont14_Prop33 = {
   0x964D /* first character */
  ,0x964D /* last character  */
  ,&GUI_Fontfont14_CharInfo[ 33] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont14_Prop32 = {
   0x95F4 /* first character */
  ,0x95F4 /* last character  */
  ,&GUI_Fontfont14_CharInfo[ 32] /* address of first character */
  ,&GUI_Fontfont14_Prop33 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont14_Prop31 = {
   0x94BB /* first character */
  ,0x94BB /* last character  */
  ,&GUI_Fontfont14_CharInfo[ 31] /* address of first character */
  ,&GUI_Fontfont14_Prop32 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont14_Prop30 = {
   0x9488 /* first character */
  ,0x9488 /* last character  */
  ,&GUI_Fontfont14_CharInfo[ 30] /* address of first character */
  ,&GUI_Fontfont14_Prop31 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont14_Prop29 = {
   0x901F /* first character */
  ,0x901F /* last character  */
  ,&GUI_Fontfont14_CharInfo[ 29] /* address of first character */
  ,&GUI_Fontfont14_Prop30 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont14_Prop28 = {
   0x8F6C /* first character */
  ,0x8F6C /* last character  */
  ,&GUI_Fontfont14_CharInfo[ 28] /* address of first character */
  ,&GUI_Fontfont14_Prop29 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont14_Prop27 = {
   0x8DDD /* first character */
  ,0x8DDD /* last character  */
  ,&GUI_Fontfont14_CharInfo[ 27] /* address of first character */
  ,&GUI_Fontfont14_Prop28 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont14_Prop26 = {
   0x8BA4 /* first character */
  ,0x8BA4 /* last character  */
  ,&GUI_Fontfont14_CharInfo[ 26] /* address of first character */
  ,&GUI_Fontfont14_Prop27 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont14_Prop25 = {
   0x884C /* first character */
  ,0x884C /* last character  */
  ,&GUI_Fontfont14_CharInfo[ 25] /* address of first character */
  ,&GUI_Fontfont14_Prop26 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont14_Prop24 = {
   0x786E /* first character */
  ,0x786E /* last character  */
  ,&GUI_Fontfont14_CharInfo[ 24] /* address of first character */
  ,&GUI_Fontfont14_Prop25 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont14_Prop23 = {
   0x7535 /* first character */
  ,0x7535 /* last character  */
  ,&GUI_Fontfont14_CharInfo[ 23] /* address of first character */
  ,&GUI_Fontfont14_Prop24 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont14_Prop22 = {
   0x6DF1 /* first character */
  ,0x6DF1 /* last character  */
  ,&GUI_Fontfont14_CharInfo[ 22] /* address of first character */
  ,&GUI_Fontfont14_Prop23 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont14_Prop21 = {
   0x6D88 /* first character */
  ,0x6D88 /* last character  */
  ,&GUI_Fontfont14_CharInfo[ 21] /* address of first character */
  ,&GUI_Fontfont14_Prop22 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont14_Prop20 = {
   0x6B21 /* first character */
  ,0x6B21 /* last character  */
  ,&GUI_Fontfont14_CharInfo[ 20] /* address of first character */
  ,&GUI_Fontfont14_Prop21 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont14_Prop19 = {
   0x673A /* first character */
  ,0x673A /* last character  */
  ,&GUI_Fontfont14_CharInfo[ 19] /* address of first character */
  ,&GUI_Fontfont14_Prop20 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont14_Prop18 = {
   0x6570 /* first character */
  ,0x6570 /* last character  */
  ,&GUI_Fontfont14_CharInfo[ 18] /* address of first character */
  ,&GUI_Fontfont14_Prop19 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont14_Prop17 = {
   0x6392 /* first character */
  ,0x6392 /* last character  */
  ,&GUI_Fontfont14_CharInfo[ 17] /* address of first character */
  ,&GUI_Fontfont14_Prop18 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont14_Prop16 = {
   0x62CD /* first character */
  ,0x62CD /* last character  */
  ,&GUI_Fontfont14_CharInfo[ 16] /* address of first character */
  ,&GUI_Fontfont14_Prop17 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont14_Prop15 = {
   0x6269 /* first character */
  ,0x6269 /* last character  */
  ,&GUI_Fontfont14_CharInfo[ 15] /* address of first character */
  ,&GUI_Fontfont14_Prop16 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont14_Prop14 = {
   0x6253 /* first character */
  ,0x6253 /* last character  */
  ,&GUI_Fontfont14_CharInfo[ 14] /* address of first character */
  ,&GUI_Fontfont14_Prop15 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont14_Prop13 = {
   0x5EA6 /* first character */
  ,0x5EA6 /* last character  */
  ,&GUI_Fontfont14_CharInfo[ 13] /* address of first character */
  ,&GUI_Fontfont14_Prop14 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont14_Prop12 = {
   0x5C0F /* first character */
  ,0x5C0F /* last character  */
  ,&GUI_Fontfont14_CharInfo[ 12] /* address of first character */
  ,&GUI_Fontfont14_Prop13 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont14_Prop11 = {
   0x5B9A /* first character */
  ,0x5B9A /* last character  */
  ,&GUI_Fontfont14_CharInfo[ 11] /* address of first character */
  ,&GUI_Fontfont14_Prop12 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont14_Prop10 = {
   0x5B54 /* first character */
  ,0x5B54 /* last character  */
  ,&GUI_Fontfont14_CharInfo[ 10] /* address of first character */
  ,&GUI_Fontfont14_Prop11 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont14_Prop9 = {
   0x5947 /* first character */
  ,0x5947 /* last character  */
  ,&GUI_Fontfont14_CharInfo[  9] /* address of first character */
  ,&GUI_Fontfont14_Prop10 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont14_Prop8 = {
   0x5934 /* first character */
  ,0x5934 /* last character  */
  ,&GUI_Fontfont14_CharInfo[  8] /* address of first character */
  ,&GUI_Fontfont14_Prop9 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont14_Prop7 = {
   0x5927 /* first character */
  ,0x5927 /* last character  */
  ,&GUI_Fontfont14_CharInfo[  7] /* address of first character */
  ,&GUI_Fontfont14_Prop8 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont14_Prop6 = {
   0x53D6 /* first character */
  ,0x53D6 /* last character  */
  ,&GUI_Fontfont14_CharInfo[  6] /* address of first character */
  ,&GUI_Fontfont14_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont14_Prop5 = {
   0x5347 /* first character */
  ,0x5347 /* last character  */
  ,&GUI_Fontfont14_CharInfo[  5] /* address of first character */
  ,&GUI_Fontfont14_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont14_Prop4 = {
   0x52A8 /* first character */
  ,0x52A8 /* last character  */
  ,&GUI_Fontfont14_CharInfo[  4] /* address of first character */
  ,&GUI_Fontfont14_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont14_Prop3 = {
   0x5076 /* first character */
  ,0x5076 /* last character  */
  ,&GUI_Fontfont14_CharInfo[  3] /* address of first character */
  ,&GUI_Fontfont14_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont14_Prop2 = {
   0x4F4D /* first character */
  ,0x4F4D /* last character  */
  ,&GUI_Fontfont14_CharInfo[  2] /* address of first character */
  ,&GUI_Fontfont14_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont14_Prop1 = {
   0x4E0A /* first character */
  ,0x4E0B /* last character  */
  ,&GUI_Fontfont14_CharInfo[  0] /* address of first character */
  ,&GUI_Fontfont14_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontfont14 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,25 /* height of font  */
  ,25 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontfont14_Prop1}
  ,20 /* Baseline */
  ,10 /* Height of lowercase characters */
  ,14 /* Height of capital characters */
};

