/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font Converter for emWin version 5.28                       *
*        Compiled Jan 30 2015, 16:40:45                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: font24.c                                              *
* Font:        Î¢ÈíÑÅºÚ Light                                        *
* Height:      41                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  41                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: E:\GitHub\wireless-human-computer-interaction-system\Client\TEXT\font16.txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontfont24;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Fontfont24_5236[120] = { /* code 5236 */
  ________,_XX_____,________,___X____,
  ____X___,_XX_____,________,___X____,
  ___XX___,_XX_____,________,___X____,
  ___XX___,_XX_____,_____X__,___X____,
  ___XXXXX,XXXXXXXX,X____X__,___X____,
  __XXXXXX,XXXXXXXX,X____X__,___X____,
  __X_____,_XX_____,_____X__,___X____,
  _XX_____,_XX_____,_____X__,___X____,
  _X______,_XX_____,_____X__,___X____,
  ________,_XX_____,_____X__,___X____,
  ________,_XX_____,_____X__,___X____,
  XXXXXXXX,XXXXXXXX,XXX__X__,___X____,
  XXXXXXXX,XXXXXXXX,XXX__X__,___X____,
  ________,_XX_____,_____X__,___X____,
  ________,_XX_____,_____X__,___X____,
  ________,_XX_____,_____X__,___X____,
  ________,_XX_____,_____X__,___X____,
  __XXXXXX,XXXXXXXX,X____X__,___X____,
  __XX____,_XX_____,X____X__,___X____,
  __XX____,_XX_____,X____X__,___X____,
  __XX____,_XX_____,X____X__,___X____,
  __XX____,_XX_____,X_______,___X____,
  __XX____,_XX_____,X_______,___X____,
  __XX____,_XX_____,X_______,___X____,
  __XX____,_XX_____,X_______,___X____,
  __XX____,_XX_XXXX,X_______,___X____,
  __XX____,_XX_XXXX,________,___X____,
  ________,_XX_____,_____XXX,XXXX____,
  ________,_XX_____,_____XXX,XXXX____,
  ________,_XX_____,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont24_5668[112] = { /* code 5668 */
  ___XXXXX,XXXXX___,_XXXXXXX,XXX_____,
  ___X____,___XX___,_X______,__X_____,
  ___X____,___XX___,_X______,__X_____,
  ___X____,___XX___,_X______,__X_____,
  ___X____,___XX___,_X______,__X_____,
  ___X____,___XX___,_X______,__X_____,
  ___XXXXX,XXXXX___,_XXXXXXX,XXX_____,
  ________,________,________,________,
  ________,______XX,____XX__,________,
  ________,______X_,_____XX_,________,
  ________,______X_,_____XX_,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  ________,_____X__,XX______,________,
  ________,___XXX__,XXX_____,________,
  ________,_XXXX___,__XXX___,________,
  _____XXX,XXX_____,___XXXXX,________,
  XXXXXXXX,________,______XX,XXXXXX__,
  _XX_____,________,________,___XX___,
  ________,________,________,________,
  ___XXXXX,XXXXX___,_XXXXXXX,XXX_____,
  ___X____,___XX___,_X______,__X_____,
  ___X____,___XX___,_X______,__X_____,
  ___X____,___XX___,_X______,__X_____,
  ___X____,___XX___,_X______,__X_____,
  ___X____,___XX___,_X______,__X_____,
  ___XXXXX,XXXXX___,_XXXXXXX,XXX_____,
  ___X____,___XX___,_X______,__X_____,
  ___X____,___XX___,_X______,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont24_5E8A[120] = { /* code 5E8A */
  ________,_______X,________,________,
  ________,_______X,X_______,________,
  ________,________,XX______,________,
  ________,________,XX______,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
  ___XX___,________,________,________,
  ___XX___,________,________,________,
  ___XX___,________,_X______,________,
  ___XX___,________,_X______,________,
  ___XX___,________,_X______,________,
  ___XX___,________,_X______,________,
  ___XX__X,XXXXXXXX,XXXXXXXX,XXXXX___,
  ___XX__X,XXXXXXXX,XXXXXXXX,XXXXX___,
  ___XX___,_______X,XX_X____,________,
  ___XX___,_______X,_X_X____,________,
  ___XX___,______XX,_X_XX___,________,
  ___XX___,______X_,_X__XX__,________,
  ___XX___,_____XX_,_X___X__,________,
  ___XX___,____XX__,_X___XX_,________,
  ___XX___,___XX___,_X____XX,________,
  ___XX___,__XXX___,_X_____X,X_______,
  ___X____,_XXX____,_X______,XX______,
  __XX____,XXX_____,_X______,_XXX____,
  __XX___X,XX______,_X______,__XXX___,
  __X__XXX,________,_X______,___XX___,
  _XX___X_,________,_X______,________,
  XXX_____,________,_X______,________,
  XX______,________,_X______,________,
  ________,________,_X______,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont24_624B[112] = { /* code 624B */
  ________,________,__XXXXXX,XXX_____,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  __XXX___,______XX,________,________,
  ________,______XX,________,________,
  ________,______XX,________,________,
  ________,______XX,________,________,
  ________,______XX,________,________,
  ________,______XX,________,________,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ________,______XX,________,________,
  ________,______XX,________,________,
  ________,______XX,________,________,
  ________,______XX,________,________,
  ________,______XX,________,________,
  ________,______XX,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
  ________,______XX,________,________,
  ________,______XX,________,________,
  ________,______XX,________,________,
  ________,______XX,________,________,
  ________,______XX,________,________,
  ________,______XX,________,________,
  ________,______XX,________,________,
  ________,______XX,________,________,
  _______X,XXXXXXX_,________,________,
  _______X,XXXXXX__,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont24_6301[116] = { /* code 6301 */
  ____XX__,________,___XX___,________,
  ____XX__,________,___XX___,________,
  ____XX__,________,___XX___,________,
  ____XX__,________,___XX___,________,
  ____XX__,____XXXX,XXXXXXXX,XXXXX___,
  ____XX__,____XXXX,XXXXXXXX,XXXXX___,
  XXXXXXXX,XX______,___XX___,________,
  XXXXXXXX,XX______,___XX___,________,
  ____XX__,________,___XX___,________,
  ____XX__,________,___XX___,________,
  ____XX__,__XXXXXX,XXXXXXXX,XXXXXX__,
  ____XX__,__XXXXXX,XXXXXXXX,XXXXXX__,
  ____XX__,________,________,________,
  ____XX__,________,_______X,X_______,
  ____XX__,XX______,_______X,X_______,
  ____XXXX,XX______,_______X,X_______,
  XXXXXX__,__XXXXXX,XXXXXXXX,XXXXXX__,
  XX__XX__,__XXXXXX,XXXXXXXX,XXXXXX__,
  ____XX__,________,_______X,X_______,
  ____XX__,________,_______X,X_______,
  ____XX__,____XX__,_______X,X_______,
  ____XX__,_____XX_,_______X,X_______,
  ____XX__,______XX,_______X,X_______,
  ____XX__,_______X,X______X,X_______,
  ____XX__,________,X______X,X_______,
  ____XX__,________,_______X,X_______,
  ____XX__,________,_______X,X_______,
  XXXXXX__,________,_XXXXXXX,X_______,
  _XXXX___,________,_XXXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont24_63A7[120] = { /* code 63A7 */
  ____XX__,________,__XX____,________,
  ____XX__,________,__XX____,________,
  ____XX__,________,___XX___,________,
  ____XX__,________,____X___,________,
  ____XX__,___XXXXX,XXXXXXXX,XXXXX___,
  ____XX__,___XXXXX,XXXXXXXX,XXXXX___,
  XXXXXXXX,X__XX___,________,___XX___,
  XXXXXXXX,X__XX___,________,___XX___,
  ____XX__,___XX___,________,___XX___,
  ____XX__,___XX___,________,___XX___,
  ____XX__,________,XX____XX,________,
  ____XX__,_______X,XX_____X,XX______,
  ____XX__,______XX,________,XXX_____,
  ____XX__,____XXX_,________,_XXX____,
  ____XX__,___XXX__,________,__XXX___,
  ____XXXX,X__XX___,________,____X___,
  __XXXXXX,________,________,________,
  XXXXXX__,________,________,________,
  X___XX__,___XXXXX,XXXXXXXX,XXXXX___,
  ____XX__,________,___XX___,________,
  ____XX__,________,___XX___,________,
  ____XX__,________,___XX___,________,
  ____XX__,________,___XX___,________,
  ____XX__,________,___XX___,________,
  ____XX__,________,___XX___,________,
  ____XX__,________,___XX___,________,
  ____XX__,________,___XX___,________,
  ____XX__,_XXXXXXX,XXXXXXXX,XXXXXX__,
  XXXXXX__,_XXXXXXX,XXXXXXXX,XXXXXX__,
  XXXXX___,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont24_94BB[120] = { /* code 94BB */
  ____XX__,________,___XX___,________,
  ____XX__,________,___XX___,________,
  ____X___,________,___XX___,________,
  ___XX___,________,___XX___,________,
  ___XXXXX,XXXX____,___XX___,________,
  __XXXXXX,XXXX____,___XX___,________,
  __X_____,________,___XXXXX,XXXXXX__,
  _XX_____,________,___XXXXX,XXXXXX__,
  XX______,________,___XX___,________,
  XX______,________,___XX___,________,
  ________,________,___XX___,________,
  __XXXXXX,XX______,___XX___,________,
  ____XX__,________,___XX___,________,
  ____XX__,________,___XX___,________,
  ____XX__,________,___XX___,________,
  ____XX__,_____XXX,XXXXXXXX,XXXX____,
  XXXXXXXX,XXX__XXX,XXXXXXXX,XXXX____,
  XXXXXXXX,XXX__XX_,________,___X____,
  ____XX__,_____XX_,________,___X____,
  ____XX__,_____XX_,________,___X____,
  ____XX__,_____XX_,________,___X____,
  ____XX__,_____XX_,________,___X____,
  ____XX__,_____XX_,________,___X____,
  ____XX__,_____XX_,________,___X____,
  ____XX__,_XX__XX_,________,___X____,
  ____XX__,XXX__XX_,________,___X____,
  ____XXXX,X____XXX,XXXXXXXX,XXXX____,
  ____XXX_,_____XXX,XXXXXXXX,XXXX____,
  ____XX__,_____XX_,________,___X____,
  ________,_____XX_,________,___X____};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_Fontfont24_CharInfo[7] = {
   {  29,  30,   1,   7,  32, acGUI_Fontfont24_5236 } /* code 5236 */
  ,{  30,  28,   1,   9,  32, acGUI_Fontfont24_5668 } /* code 5668 */
  ,{  30,  30,   1,   7,  32, acGUI_Fontfont24_5E8A } /* code 5E8A */
  ,{  30,  28,   1,   8,  32, acGUI_Fontfont24_624B } /* code 624B */
  ,{  30,  29,   1,   7,  32, acGUI_Fontfont24_6301 } /* code 6301 */
  ,{  30,  30,   1,   7,  32, acGUI_Fontfont24_63A7 } /* code 63A7 */
  ,{  30,  30,   1,   7,  32, acGUI_Fontfont24_94BB } /* code 94BB */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont24_Prop7 = {
   0x94BB /* first character */
  ,0x94BB /* last character  */
  ,&GUI_Fontfont24_CharInfo[  6] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont24_Prop6 = {
   0x63A7 /* first character */
  ,0x63A7 /* last character  */
  ,&GUI_Fontfont24_CharInfo[  5] /* address of first character */
  ,&GUI_Fontfont24_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont24_Prop5 = {
   0x6301 /* first character */
  ,0x6301 /* last character  */
  ,&GUI_Fontfont24_CharInfo[  4] /* address of first character */
  ,&GUI_Fontfont24_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont24_Prop4 = {
   0x624B /* first character */
  ,0x624B /* last character  */
  ,&GUI_Fontfont24_CharInfo[  3] /* address of first character */
  ,&GUI_Fontfont24_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont24_Prop3 = {
   0x5E8A /* first character */
  ,0x5E8A /* last character  */
  ,&GUI_Fontfont24_CharInfo[  2] /* address of first character */
  ,&GUI_Fontfont24_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont24_Prop2 = {
   0x5668 /* first character */
  ,0x5668 /* last character  */
  ,&GUI_Fontfont24_CharInfo[  1] /* address of first character */
  ,&GUI_Fontfont24_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont24_Prop1 = {
   0x5236 /* first character */
  ,0x5236 /* last character  */
  ,&GUI_Fontfont24_CharInfo[  0] /* address of first character */
  ,&GUI_Fontfont24_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontfont24 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,41 /* height of font  */
  ,41 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontfont24_Prop1}
  ,33 /* Baseline */
  ,18 /* Height of lowercase characters */
  ,25 /* Height of capital characters */
};

