/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font Converter for emWin version 5.28                       *
*        Compiled Jan 30 2015, 16:40:45                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: font12.c                                              *
* Font:        Î¢ÈíÑÅºÚ                                              *
* Height:      21                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  21                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: E:\GitHub\wireless-human-computer-interaction-system\Client\TEXT\font12.txt*
* Read pattern file: E:\GitHub\wireless-human-computer-interaction-system\Client\TEXT\font12.txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontfont12;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_4E0A[ 26] = { /* code 4E0A */
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,XXXXXXX_,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  XXXXXXXX,XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_4E0B[ 28] = { /* code 4E0B */
  XXXXXXXX,XXXXXXXX,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,XX______,
  _______X,_XX_____,
  _______X,___XX___,
  _______X,____XX__,
  _______X,_____XX_,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_4EF6[ 28] = { /* code 4EF6 */
  ___X____,__X_____,
  ___X___X,__X_____,
  __X____X,__X_____,
  __X___XX,XXXXXXX_,
  _XX___X_,__X_____,
  _XX__X__,__X_____,
  XXX__X__,__X_____,
  X_X_____,__X_____,
  __X__XXX,XXXXXXXX,
  __X_____,__X_____,
  __X_____,__X_____,
  __X_____,__X_____,
  __X_____,__X_____,
  __X_____,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_4F20[ 30] = { /* code 4F20 */
  ___X____,_X______,
  ___X____,_X______,
  __X__XXX,XXXXXXX_,
  __X_____,X_______,
  __X____X,________,
  _XX_XXXX,XXXXXXXX,
  _XX____X,________,
  X_X___X_,________,
  X_X___XX,XXXXXXX_,
  __X_____,_____X__,
  __X__XX_,____X___,
  __X___XX,___X____,
  __X_____,XXX_____,
  __X_____,__XX____,
  __X_____,___XX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_4F4D[ 30] = { /* code 4F4D */
  ____X___,_X______,
  ___X____,__X_____,
  ___X____,___X____,
  __X__XXX,XXXXXXXX,
  __X_____,________,
  __X___X_,______X_,
  _XX___X_,_____XX_,
  XXX____X,_____X__,
  X_X____X,_____X__,
  __X____X,____X___,
  __X_____,X___X___,
  __X_____,X__X____,
  __X_____,___X____,
  __X_XXXX,XXXXXXXX,
  __X_____,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_5076[ 30] = { /* code 5076 */
  ___X____,________,
  ___X__XX,XXXXXX__,
  __X___X_,_X___X__,
  __X___XX,XXXXXX__,
  __X___X_,_X___X__,
  _XX___X_,_X___X__,
  _XX___XX,XXXXXX__,
  X_X_____,_X______,
  X_X__XXX,XXXXXXX_,
  __X__X__,_X____X_,
  __X__X__,_X_X__X_,
  __X__X_X,XXXXX_X_,
  __X__X__,____X_X_,
  __X__X__,______X_,
  __X__X__,___XXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_51CF[ 30] = { /* code 51CF */
  ________,___XXX__,
  X_______,___X_XX_,
  _X__XXXX,XXXXXXXX,
  __X_X___,___X____,
  ____X_XX,XX_X____,
  ____X___,___X__X_,
  __X_X___,___X__X_,
  __X_X_XX,XX_X_X__,
  _X__X_X_,_X_X_X__,
  _X__X_X_,_X_XXX__,
  _X__X_X_,_X_XX___,
  X__X__XX,XX_XX__X,
  X__X__X_,__XXX__X,
  __XX____,_XX__X_X,
  __X_____,X____XX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_52A0[ 30] = { /* code 52A0 */
  ___X____,________,
  ___X____,________,
  ___X____,_XXXXXX_,
  _XXXXXX_,_X____X_,
  ___X__X_,_X____X_,
  ___X__X_,_X____X_,
  ___X__X_,_X____X_,
  ___X__X_,_X____X_,
  ___X__X_,_X____X_,
  ___X__X_,_X____X_,
  __X___X_,_X____X_,
  __X___X_,_X____X_,
  _XX___X_,_XXXXXX_,
  _X_XXX__,_X____X_,
  X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_52A8[ 28] = { /* code 52A8 */
  ________,_X______,
  _XXXXXX_,_X______,
  ________,_X______,
  _______X,XXXXXX__,
  ________,_X___X__,
  XXXXXXX_,_X___X__,
  __X_____,_X___X__,
  __X_____,_X___X__,
  _X__X___,_X___X__,
  _X___X__,X____X__,
  _X__XX__,X____X__,
  XXXX__XX,X____X__,
  _______X,_____X__,
  ______X_,__XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_5347[ 30] = { /* code 5347 */
  ________,___X____,
  ______XX,XX_X____,
  XXXXXX__,___X____,
  ____X___,___X____,
  ____X___,___X____,
  ____X___,___X____,
  XXXXXXXX,XXXXXXXX,
  ____X___,___X____,
  ____X___,___X____,
  ____X___,___X____,
  ____X___,___X____,
  ___X____,___X____,
  __XX____,___X____,
  _XX_____,___X____,
  XX______,___X____};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_53D6[ 26] = { /* code 53D6 */
  XXXXXXXX,XXXXXX__,
  _X___X__,X____X__,
  _X___X__,X____X__,
  _XXXXX__,X____X__,
  _X___X__,_X__X___,
  _X___X__,_X__X___,
  _XXXXX__,_X__X___,
  _X___X__,_XXX____,
  _X___X__,__XX____,
  _X_XXXXX,__XX____,
  XXX__X__,XX_XX___,
  _____X_X,X___XX__,
  _____XXX,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_53F3[ 30] = { /* code 53F3 */
  _______X,________,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  ______X_,________,
  _____X__,________,
  ____XX__,________,
  ___XX___,________,
  ___XXXXX,XXXXXX__,
  __XXX___,_____X__,
  _XX_X___,_____X__,
  XX__X___,_____X__,
  ____X___,_____X__,
  ____X___,_____X__,
  ____XXXX,XXXXXX__,
  ____X___,_____X__};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_56DE[ 28] = { /* code 56DE */
  XXXXXXXX,XXXXXX__,
  X_______,_____X__,
  X_______,_____X__,
  X___XXXX,XX___X__,
  X___X___,_X___X__,
  X___X___,_X___X__,
  X___X___,_X___X__,
  X___X___,_X___X__,
  X___XXXX,XX___X__,
  X___X___,_X___X__,
  X_______,_____X__,
  X_______,_____X__,
  XXXXXXXX,XXXXXX__,
  X_______,_____X__};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_5757[ 28] = { /* code 5757 */
  __X_____,_X______,
  __X_____,_X______,
  __X_____,_X______,
  __X___XX,XXXXXX__,
  XXXXX___,_X___X__,
  __X_____,_X___X__,
  __X_____,_X___X__,
  __X_____,_X___X__,
  __X__XXX,XXXXXXXX,
  __X_____,XX______,
  __XXXX__,X_X_____,
  XXX____X,___X____,
  _____XX_,____XX__,
  ____XX__,______XX};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_589E[ 30] = { /* code 589E */
  __X____X,_____X__,
  __X_____,X__XX___,
  __X__XXX,XXXXXXX_,
  __X__X__,__X___X_,
  XXXXXX_X,__X_X_X_,
  __X__X__,X_XX__X_,
  __X__XXX,XXXXXXX_,
  __X__X__,______X_,
  __X_____,________,
  __X___XX,XXXXXX__,
  __X_X_X_,_____X__,
  _XXX__XX,XXXXXX__,
  X_____X_,_____X__,
  ______XX,XXXXXX__,
  ______X_,_____X__};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_5927[ 30] = { /* code 5927 */
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  _______X,________,
  _______X,________,
  ______XX,X_______,
  ______X_,X_______,
  ______X_,X_______,
  _____X__,_X______,
  ____X___,__X_____,
  ___X____,__XX____,
  _XX_____,___XX___,
  XX______,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_5934[ 30] = { /* code 5934 */
  __X____X,________,
  ___X___X,________,
  ____X__X,________,
  _____X_X,________,
  _XX____X,________,
  __XX___X,________,
  ___XX__X,________,
  _______X,________,
  XXXXXXXX,XXXXXX__,
  _______X,________,
  ______XX,X_______,
  ______X_,XX______,
  ____XX__,__XX____,
  __XXX___,___XX___,
  XX______,_____X__};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_5947[ 30] = { /* code 5947 */
  _______X,________,
  _XXXXXXX,XXXXXX__,
  ______XX,X_______,
  ____XX__,XXXX____,
  _XXX____,____XX__,
  ________,________,
  XXXXXXXX,XXXXXXX_,
  ________,____X___,
  __XXXXXX,X___X___,
  __X_____,X___X___,
  __X_____,X___X___,
  __X_____,X___X___,
  __XXXXXX,X___X___,
  __X_____,____X___,
  ________,_XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_5B54[ 28] = { /* code 5B54 */
  ________,_X______,
  _XXXXXXX,_X______,
  ______XX,_X______,
  _____XX_,_X______,
  ____XX__,_X______,
  ____X___,_X______,
  ____X_XX,_X______,
  __XXXX__,_X______,
  XX__X___,_X______,
  ____X___,_X____X_,
  ____X___,_X____X_,
  ____X___,_X____X_,
  ____X___,_X____X_,
  _XXXX___,_XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_5B9A[ 30] = { /* code 5B9A */
  _______X,________,
  _______X,X_______,
  _XXXXXXX,XXXXXXX_,
  _X______,______X_,
  ________,________,
  XXXXXXXX,XXXXXXXX,
  ________,X_______,
  ___X____,X_______,
  ___X____,X_______,
  ___X____,XXXXXXX_,
  __XX____,X_______,
  __XXX___,X_______,
  _XX_XX__,X_______,
  _X____XX,XXXXXXXX,
  X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_5C0F[ 28] = { /* code 5C0F */
  ________,X_______,
  ________,X_______,
  ________,X_______,
  ____X___,X__X____,
  ___XX___,X___X___,
  ___X____,X___X___,
  __X_____,X____X__,
  __X_____,X____XX_,
  _X______,X_____X_,
  _X______,X_____XX,
  X_______,X______X,
  ________,X_______,
  ________,X_______,
  ____XXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_5C11[ 28] = { /* code 5C11 */
  _______X,________,
  _______X,________,
  ___X___X,__X_____,
  __XX___X,___X____,
  __X____X,____X___,
  __X____X,_____X__,
  _X_____X,____X_X_,
  XX_____X,___X____,
  X______X,__X_____,
  ________,_X______,
  _______X,X_______,
  _____XXX,________,
  ___XXX__,________,
  XXX_____,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_5DE5[ 26] = { /* code 5DE5 */
  _XXXXXXX,XXXXXXX_,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  XXXXXXXX,XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_5DE6[ 28] = { /* code 5DE6 */
  ______X_,________,
  ______X_,________,
  _____X__,________,
  _XXXXXXX,XXXXXXXX,
  _____X__,________,
  _____X__,________,
  ____X___,________,
  ____XXXX,XXXXXXX_,
  ___X____,_X______,
  ___X____,_X______,
  __X_____,_X______,
  _XX_____,_X______,
  _X______,_X______,
  X__XXXXX,XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_5EA6[ 28] = { /* code 5EA6 */
  ________,X_______,
  ________,_X______,
  __XXXXXX,XXXXXXXX,
  __X_____,________,
  __X___X_,____X___,
  __XXXXXX,XXXXXXXX,
  __X___X_,____X___,
  __X___XX,XXXXX___,
  __X_____,________,
  __X_XXXX,XXXXXX__,
  __X__X__,___XX___,
  _X____XX,XXX_____,
  _X____XX,XXXX____,
  X__XXX__,____XXXX};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_5F0F[ 30] = { /* code 5F0F */
  ________,_X_XX___,
  ________,_X__XX__,
  ________,_X___X__,
  XXXXXXXX,XXXXXXXX,
  ________,_X______,
  ________,_X______,
  _XXXXXXX,_X______,
  ____X___,_X______,
  ____X___,__X_____,
  ____X___,__X_____,
  ____X___,__X_____,
  ____X_XX,X_XX___X,
  __XXXX__,___X___X,
  XX______,___XX_XX,
  ________,____XXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_6253[ 28] = { /* code 6253 */
  ___X____,________,
  ___X___X,XXXXXXXX,
  ___X____,____X___,
  XXXXXX__,____X___,
  ___X____,____X___,
  ___X____,____X___,
  ___X_XX_,____X___,
  __XXX___,____X___,
  XX_X____,____X___,
  ___X____,____X___,
  ___X____,____X___,
  ___X____,____X___,
  ___X____,____X___,
  XXXX____,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_6267[ 28] = { /* code 6267 */
  __X_____,X_______,
  __X_____,X_______,
  __X_____,X_______,
  XXXXXXXX,XXXXX___,
  __X_____,X___X___,
  __X_____,X___X___,
  __X__XX_,X___X___,
  __XXX__X,X___X___,
  XXX____X,XX__X___,
  __X____X,__X_X___,
  __X___XX,____X__X,
  __X___X_,____X__X,
  __X__XX_,____X_XX,
  XXX_XX__,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_6269[ 28] = { /* code 6269 */
  __X_____,_X______,
  __X_____,__X_____,
  __X___XX,XXXXXXX_,
  XXXXX_X_,________,
  __X___X_,________,
  __X___X_,________,
  __X_X_X_,________,
  _XXX__X_,________,
  X_X___X_,________,
  __X___X_,________,
  __X__XX_,________,
  __X__X__,________,
  __X_XX__,________,
  XXX_X___,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_62E9[ 30] = { /* code 62E9 */
  __X_____,________,
  __X___XX,XXXXXXX_,
  __X____X,_____XX_,
  XXXXX___,X___XX__,
  __X_____,_XXX____,
  __X____X,XXXXX___,
  __X__XXX,__X__XXX,
  __X_X___,__X_____,
  _XXX__XX,XXXXXXX_,
  X_X_____,__X_____,
  __X_____,__X_____,
  __X__XXX,XXXXXXXX,
  __X_____,__X_____,
  __X_____,__X_____,
  XXX_____,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_636E[ 30] = { /* code 636E */
  __X_____,________,
  __X___XX,XXXXXXX_,
  __X___X_,______X_,
  XXXXX_X_,______X_,
  __X___XX,XXXXXXX_,
  __X___X_,___X__X_,
  __X___X_,___X____,
  __X_X_XX,XXXXXXXX,
  _XXX__X_,___X____,
  X_X___X_,___X____,
  __X___XX,XXXXXXX_,
  __X__XXX,______X_,
  __X__X_X,______X_,
  __X__X_X,XXXXXXX_,
  XXX_X__X,______X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_6392[ 30] = { /* code 6392 */
  __X_____,X__X____,
  __X_____,X__X____,
  __X_____,X__X____,
  XXXXXXXX,X__XXXXX,
  __X_____,X__X____,
  __X_____,X__X____,
  __X_X___,X__X____,
  __XX_XXX,X__XXXX_,
  _XX_____,X__X____,
  X_X_____,X__X____,
  __X_____,X__X____,
  __X_XXXX,X__XXXXX,
  __X_____,X__X____,
  __X_____,X__X____,
  XXX_____,X__X____};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_6570[ 30] = { /* code 6570 */
  ____X___,__X_____,
  _X__X__X,__X_____,
  __X_X_X_,__X_____,
  ____X___,_XXXXXX_,
  XXXXXXXX,_X___X__,
  ___XXX__,XX___X__,
  _XX_XXX_,XX___X__,
  X___X_X_,__X_X___,
  ___X____,__X_X___,
  XXXXXXX_,__X_X___,
  _XX___X_,__XX____,
  _XX__X__,__XX____,
  ___XX___,_XX_X___,
  __XX_XXX,XX___X__,
  XX_____X,X_____X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_673A[ 28] = { /* code 673A */
  ___X____,________,
  ___X___X,XXXXX___,
  ___X___X,____X___,
  XXXXXX_X,____X___,
  ___X___X,____X___,
  __XX___X,____X___,
  __XXX__X,____X___,
  __XX_X_X,____X___,
  _X_X___X,____X___,
  XX_X___X,____X___,
  X__X___X,____X__X,
  ___X__X_,____X__X,
  ___X__X_,____X__X,
  ___X_X__,____XXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_68C0[ 30] = { /* code 68C0 */
  __X_____,_X______,
  __X_____,XXX_____,
  __X_____,X__X____,
  XXXXXX_X,___XX___,
  __X___X_,____XX__,
  __X__X__,_____XX_,
  _XXX__XX,XXXX____,
  _XX_X___,________,
  X_X__X__,X___X___,
  X_X__X__,X__X____,
  X_X___X_,_X_X____,
  __X___X_,_X_X____,
  __X_____,__X_____,
  __X_XXXX,XXXXXX__,
  __X_____,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_6A21[ 30] = { /* code 6A21 */
  __X____X,___X____,
  __X____X,___X____,
  __X__XXX,XXXXXXX_,
  __X____X,___X____,
  XXXXX__X,___X____,
  __X___XX,XXXXXX__,
  _XX___X_,_____X__,
  _XXX__XX,XXXXXX__,
  _XX_X_X_,_____X__,
  X_X___XX,XXXXXX__,
  X_X_____,_X______,
  __X__XXX,XXXXXXX_,
  __X_____,XXX_____,
  __X____X,X__X____,
  __X_XXX_,____XXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_6B21[ 28] = { /* code 6B21 */
  _______X,________,
  _X_____X,________,
  __X___XX,XXXXXXX_,
  __XX__X_,______X_,
  ___X_X__,_X___XX_,
  _____X__,_X___X__,
  ___X____,_X______,
  ___X____,_XX_____,
  __X_____,X_X_____,
  __X_____,X__X____,
  _X_____X,___X____,
  X_____X_,____X___,
  X___XX__,_____XX_,
  ___XX___,______XX};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_6D4B[ 30] = { /* code 6D4B */
  X_______,_____X__,
  _X__XXXX,X__X_X__,
  __X_X___,X__X_X__,
  ____X_X_,X__X_X__,
  X___X_X_,X__X_X__,
  _X__X_X_,X__X_X__,
  __X_X_X_,X__X_X__,
  ____X_X_,X__X_X__,
  ____X_X_,X__X_X__,
  __X_X_X_,X__X_X__,
  __X___X_,___X_X__,
  _X___XX_,_____X__,
  _X__XX_X,_____X__,
  X__XX___,X____X__,
  X_XX____,_X_XXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_6D88[ 26] = { /* code 6D88 */
  X___X___,_X___X__,
  _X___X__,_X__X___,
  __X__XX_,_X_X____,
  ______X_,_X______,
  X_______,_X______,
  _X__XXXX,XXXXXX__,
  ____X___,_____X__,
  _X__XXXX,XXXXXX__,
  _X__X___,_____X__,
  _X__XXXX,XXXXXX__,
  X___X___,_____X__,
  X___X___,_____X__,
  X___X___,_XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_6DF1[ 30] = { /* code 6DF1 */
  XX______,________,
  _XX_XXXX,XXXXXX__,
  __XXX___,_____X__,
  _______X,X_XX____,
  X_____XX,___XX___,
  _X__XX__,_X___X__,
  __X_____,_X______,
  ____XXXX,XXXXXX__,
  __X_____,XXX_____,
  __X____X,_XX_____,
  _X____XX,_X_X____,
  _X___XX_,_X__X___,
  _X__XX__,_X___XX_,
  X___X___,_X______,
  X_______,_X______};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_7535[ 28] = { /* code 7535 */
  ______X_,________,
  ______X_,________,
  XXXXXXXX,XXXXX___,
  X_____X_,____X___,
  X_____X_,____X___,
  X_____X_,____X___,
  XXXXXXXX,XXXXX___,
  X_____X_,____X___,
  X_____X_,____X___,
  X_____X_,____X___,
  XXXXXXXX,XXXXX___,
  X_____X_,_____X__,
  ______X_,_____X__,
  ______XX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_786E[ 28] = { /* code 786E */
  ________,_X______,
  _XXXXX__,XXXXX___,
  ___X___X,___XX___,
  ___X__X_,___X____,
  __X__X_X,XXXXXXX_,
  __XXXX_X,__X___X_,
  _XX__X_X,__X___X_,
  _XX__X_X,XXXXXXX_,
  X_X__X_X,__X___X_,
  __X__X_X,__X___X_,
  __X__X_X,XXXXXXX_,
  __XXXXXX,__X___X_,
  __X___X_,__X___X_,
  _____X__,__X_XXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_7C97[ 30] = { /* code 7C97 */
  ___X____,________,
  X__X__XX,XXXXXX__,
  X__X_X_X,_____X__,
  _X_X_X_X,_____X__,
  _X_XX__X,_____X__,
  ___X___X,XXXXXX__,
  XXXXXX_X,_____X__,
  ___X___X,_____X__,
  __XXX__X,_____X__,
  _XXXXX_X,XXXXXX__,
  XX_X__XX,_____X__,
  X__X___X,_____X__,
  ___X___X,_____X__,
  ___X_XXX,XXXXXXX_,
  ___X____,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_7EC6[ 28] = { /* code 7EC6 */
  ___X____,________,
  __X___XX,XXXXXXX_,
  __X___X_,__X___X_,
  _X__X_X_,__X___X_,
  XX_X__X_,__X___X_,
  XXXX__X_,__X___X_,
  __X___XX,XXXXXXX_,
  _X____X_,__X___X_,
  XXXXX_X_,__X___X_,
  ______X_,__X___X_,
  ______X_,__X___X_,
  __XXX_X_,__X___X_,
  XX____XX,XXXXXXX_,
  ______X_,______X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_7F6E[ 26] = { /* code 7F6E */
  _XXXXXXX,XXXXX___,
  _X___X__,_X__X___,
  _XXXXXXX,XXXXX___,
  _______X,________,
  XXXXXXXX,XXXXXX__,
  _______X,________,
  __XXXXXX,XXXXX___,
  __X_____,____X___,
  __XXXXXX,XXXXX___,
  __X_____,____X___,
  __XXXXXX,XXXXX___,
  __X_____,____X___,
  XXXXXXXX,XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_884C[ 30] = { /* code 884C */
  ____X___,________,
  ___X___X,XXXXXXX_,
  __X_____,________,
  _X______,________,
  X____X__,________,
  ____X___,________,
  ___X__XX,XXXXXXXX,
  ___X____,____X___,
  __XX____,____X___,
  _X_X____,____X___,
  ___X____,____X___,
  ___X____,____X___,
  ___X____,____X___,
  ___X____,____X___,
  ___X____,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_8BA4[ 30] = { /* code 8BA4 */
  _X______,_X______,
  __X_____,_X______,
  __XX____,_X______,
  ___X____,_X______,
  ________,_X______,
  XXX_____,_X______,
  __X_____,_X______,
  __X_____,_XX_____,
  __X_____,X_X_____,
  __X__X__,X_X_____,
  __X_XX_X,X__X____,
  __XXX__X,___X____,
  __XX__X_,____X___,
  __X__XX_,____XX__,
  ____XX__,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_8BBE[ 28] = { /* code 8BBE */
  _X____XX,XXXX____,
  __X___X_,___X____,
  ___X__X_,___X____,
  _____X__,___X____,
  XXX_XX__,___XXXX_,
  __X_____,________,
  __X__XXX,XXXXX___,
  __X___X_,____X___,
  __X___XX,___X____,
  __X____X,__XX____,
  __X_X___,XXX_____,
  __XXX__X,XXX_____,
  _XX__XXX,___XX___,
  ___XX___,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_8C03[ 28] = { /* code 8C03 */
  _X______,________,
  __X__XXX,XXXXXXX_,
  __XX_X__,______X_,
  ___X_X__,__X___X_,
  _____X_X,XXXXX_X_,
  XXX__X__,__X___X_,
  __X__X_X,XXXXX_X_,
  __X__X__,______X_,
  __X__X__,XXXX__X_,
  __X_XX__,X__X__X_,
  __XX_X__,XXXX__X_,
  _X__X___,X_____X_,
  ____X___,______X_,
  ___X____,__XXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_8DDD[ 26] = { /* code 8DDD */
  _XXXXX__,XXXXXXXX,
  _X___X__,X_______,
  _X___X__,X_______,
  _X___X__,X_______,
  _XXXXX__,XXXXXXX_,
  _X_X____,X_____X_,
  ___X____,X_____X_,
  _X_XXXX_,X_____X_,
  _X_X____,XXXXXXX_,
  _X_X____,X_____X_,
  _X_X____,X_______,
  _X_XXXX_,X_______,
  XXX_____,XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_8F6C[ 32] = { /* code 8F6C */
  ___X____,__X_____,
  ___X____,__X_____,
  __X_____,_X______,
  __XXXX_X,XXXXXX__,
  _XX_____,_X______,
  _X_X____,X_______,
  _X_X__XX,XXXXXXX_,
  _X_X____,X_______,
  X__X___X,________,
  XXXXXX_X,XXXXXX__,
  ___X____,____XX__,
  ___XXXXX,___XX___,
  XXXX____,XX_X____,
  ___X____,_XX_____,
  ___X____,__XX____,
  ___X____,____X___};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_8F93[ 30] = { /* code 8F93 */
  ___X____,_XX_____,
  __X_____,X_XX____,
  XXXXXX__,X__X____,
  __X____X,____X___,
  _X____XX,XXXXXXX_,
  _X_X_XX_,______XX,
  X__X__XX,XX____X_,
  XXXXX_X_,_X__X_X_,
  ___X__X_,_X__X_X_,
  ___X__XX,XX__X_X_,
  ___XXXX_,_X__X_X_,
  XXXX__XX,XX__X_X_,
  ___X__X_,_X____X_,
  ___X__X_,_X____X_,
  ___X__XX,XX__XXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_8FD4[ 30] = { /* code 8FD4 */
  _X______,____XXX_,
  __X___XX,XXXX____,
  __XX__X_,________,
  ___X__X_,________,
  ______XX,XXXXXXX_,
  XXX___X_,______X_,
  __X___XX,X____X__,
  __X___X_,XX___X__,
  __X___X_,__XXX___,
  __X__X__,___XX___,
  __X__X__,_XX_XX__,
  __X_XX_X,XX___XX_,
  _XX_X_XX,______X_,
  XX_X____,________,
  X___XXXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_9009[ 26] = { /* code 9009 */
  _X____X_,__X_____,
  __X___X_,__X_____,
  __XX_XXX,XXXXXX__,
  ___X_X__,__X_____,
  ________,__X_____,
  XXX_XXXX,XXXXXXX_,
  __X____X,___X____,
  __X____X,___X__X_,
  __X___XX,___X__X_,
  __X__XX_,___X__X_,
  __X_XX__,___XXX__,
  XX_X____,________,
  X___XXXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_901F[ 28] = { /* code 901F */
  _X______,_X______,
  __X_____,_X______,
  __XXXXXX,XXXXXXX_,
  ___X____,_X______,
  _____XXX,XXXXXX__,
  XXX__X__,_X___X__,
  __X__X__,_X___X__,
  __X__XXX,XXXXXX__,
  __X__X__,XX___X__,
  __X____X,XXXX____,
  __X__XX_,_X__XX__,
  __X_XX__,_X___XX_,
  _XXX____,________,
  X__XXXXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_9488[ 30] = { /* code 9488 */
  __X_____,__X_____,
  __X_____,__X_____,
  _XXXXX__,__X_____,
  _X______,__X_____,
  XX______,__X_____,
  XXXXX_XX,XXXXXXX_,
  __X_____,__X_____,
  __X_____,__X_____,
  XXXXXX__,__X_____,
  __X_____,__X_____,
  __X_____,__X_____,
  __X__X__,__X_____,
  __X_X___,__X_____,
  __XX____,__X_____,
  __X_____,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_94BB[ 30] = { /* code 94BB */
  __X_____,__X_____,
  _X______,__X_____,
  _XXXXX__,__X_____,
  X_______,__XXXXXX,
  X_______,__X_____,
  XXXXXX__,__X_____,
  __X_____,__X_____,
  __X_____,__X_____,
  XXXXXX_X,XXXXXXX_,
  __X____X,______X_,
  __X____X,______X_,
  __X____X,______X_,
  __X_XX_X,______X_,
  __XXX__X,XXXXXXX_,
  __X____X,______X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_95F4[ 30] = { /* code 95F4 */
  _X______,________,
  __X__XXX,XXXXXX__,
  ___X____,_____X__,
  X_______,_____X__,
  X___XXXX,XX___X__,
  X___X___,_X___X__,
  X___X___,_X___X__,
  X___XXXX,XX___X__,
  X___X___,_X___X__,
  X___X___,_X___X__,
  X___X___,_X___X__,
  X___XXXX,XX___X__,
  X___X___,_____X__,
  X_______,_____X__,
  X_______,_XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_964D[ 30] = { /* code 964D */
  _______X,________,
  XXXX__XX,________,
  X__X_XXX,XXXXX___,
  X__X_XX_,___XX___,
  X_X_X__X,XXX_____,
  X_X____X,XXX_____,
  X_X_XXX_,___XXX__,
  X__X____,_X______,
  X__X_XXX,XXXXX___,
  X__X____,_X______,
  X__X__X_,_X______,
  XXX__X__,_X______,
  X____XXX,XXXXXX__,
  X_______,_X______,
  X_______,_X______};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_Fontfont12_CharInfo[59] = {
   {  16,  13,   0,   5,  16, acGUI_Fontfont12_4E0A } /* code 4E0A */
  ,{  16,  14,   0,   5,  16, acGUI_Fontfont12_4E0B } /* code 4E0B */
  ,{  16,  14,   0,   4,  16, acGUI_Fontfont12_4EF6 } /* code 4EF6 */
  ,{  16,  15,   0,   4,  16, acGUI_Fontfont12_4F20 } /* code 4F20 */
  ,{  16,  15,   0,   4,  16, acGUI_Fontfont12_4F4D } /* code 4F4D */
  ,{  15,  15,   0,   4,  16, acGUI_Fontfont12_5076 } /* code 5076 */
  ,{  16,  15,   0,   4,  16, acGUI_Fontfont12_51CF } /* code 51CF */
  ,{  15,  15,   0,   4,  16, acGUI_Fontfont12_52A0 } /* code 52A0 */
  ,{  14,  14,   1,   4,  16, acGUI_Fontfont12_52A8 } /* code 52A8 */
  ,{  16,  15,   0,   4,  16, acGUI_Fontfont12_5347 } /* code 5347 */
  ,{  15,  13,   1,   5,  16, acGUI_Fontfont12_53D6 } /* code 53D6 */
  ,{  15,  15,   0,   4,  16, acGUI_Fontfont12_53F3 } /* code 53F3 */
  ,{  14,  14,   1,   5,  16, acGUI_Fontfont12_56DE } /* code 56DE */
  ,{  16,  14,   0,   4,  16, acGUI_Fontfont12_5757 } /* code 5757 */
  ,{  15,  15,   0,   4,  16, acGUI_Fontfont12_589E } /* code 589E */
  ,{  15,  15,   0,   4,  16, acGUI_Fontfont12_5927 } /* code 5927 */
  ,{  14,  15,   1,   4,  16, acGUI_Fontfont12_5934 } /* code 5934 */
  ,{  15,  15,   0,   4,  16, acGUI_Fontfont12_5947 } /* code 5947 */
  ,{  15,  14,   0,   4,  16, acGUI_Fontfont12_5B54 } /* code 5B54 */
  ,{  16,  15,   0,   4,  16, acGUI_Fontfont12_5B9A } /* code 5B9A */
  ,{  16,  14,   0,   4,  16, acGUI_Fontfont12_5C0F } /* code 5C0F */
  ,{  15,  14,   1,   4,  16, acGUI_Fontfont12_5C11 } /* code 5C11 */
  ,{  16,  13,   0,   5,  16, acGUI_Fontfont12_5DE5 } /* code 5DE5 */
  ,{  16,  14,   0,   4,  16, acGUI_Fontfont12_5DE6 } /* code 5DE6 */
  ,{  16,  14,   0,   4,  16, acGUI_Fontfont12_5EA6 } /* code 5EA6 */
  ,{  16,  15,   0,   4,  16, acGUI_Fontfont12_5F0F } /* code 5F0F */
  ,{  16,  14,   0,   4,  16, acGUI_Fontfont12_6253 } /* code 6253 */
  ,{  16,  14,   0,   4,  16, acGUI_Fontfont12_6267 } /* code 6267 */
  ,{  15,  14,   1,   4,  16, acGUI_Fontfont12_6269 } /* code 6269 */
  ,{  16,  15,   0,   4,  16, acGUI_Fontfont12_62E9 } /* code 62E9 */
  ,{  16,  15,   0,   4,  16, acGUI_Fontfont12_636E } /* code 636E */
  ,{  16,  15,   0,   4,  16, acGUI_Fontfont12_6392 } /* code 6392 */
  ,{  15,  15,   0,   4,  16, acGUI_Fontfont12_6570 } /* code 6570 */
  ,{  16,  14,   0,   4,  16, acGUI_Fontfont12_673A } /* code 673A */
  ,{  15,  15,   1,   4,  16, acGUI_Fontfont12_68C0 } /* code 68C0 */
  ,{  15,  15,   1,   4,  16, acGUI_Fontfont12_6A21 } /* code 6A21 */
  ,{  16,  14,   0,   4,  16, acGUI_Fontfont12_6B21 } /* code 6B21 */
  ,{  14,  15,   1,   4,  16, acGUI_Fontfont12_6D4B } /* code 6D4B */
  ,{  14,  13,   1,   5,  16, acGUI_Fontfont12_6D88 } /* code 6D88 */
  ,{  15,  15,   1,   4,  16, acGUI_Fontfont12_6DF1 } /* code 6DF1 */
  ,{  14,  14,   1,   4,  16, acGUI_Fontfont12_7535 } /* code 7535 */
  ,{  15,  14,   0,   4,  16, acGUI_Fontfont12_786E } /* code 786E */
  ,{  15,  15,   0,   4,  16, acGUI_Fontfont12_7C97 } /* code 7C97 */
  ,{  15,  14,   0,   4,  16, acGUI_Fontfont12_7EC6 } /* code 7EC6 */
  ,{  14,  13,   1,   5,  16, acGUI_Fontfont12_7F6E } /* code 7F6E */
  ,{  16,  15,   0,   4,  16, acGUI_Fontfont12_884C } /* code 884C */
  ,{  15,  15,   1,   4,  16, acGUI_Fontfont12_8BA4 } /* code 8BA4 */
  ,{  15,  14,   1,   5,  16, acGUI_Fontfont12_8BBE } /* code 8BBE */
  ,{  15,  14,   0,   4,  16, acGUI_Fontfont12_8C03 } /* code 8C03 */
  ,{  16,  13,   0,   5,  16, acGUI_Fontfont12_8DDD } /* code 8DDD */
  ,{  15,  16,   1,   3,  16, acGUI_Fontfont12_8F6C } /* code 8F6C */
  ,{  16,  15,   0,   4,  16, acGUI_Fontfont12_8F93 } /* code 8F93 */
  ,{  16,  15,   0,   4,  16, acGUI_Fontfont12_8FD4 } /* code 8FD4 */
  ,{  15,  13,   0,   5,  16, acGUI_Fontfont12_9009 } /* code 9009 */
  ,{  15,  14,   0,   4,  16, acGUI_Fontfont12_901F } /* code 901F */
  ,{  15,  15,   1,   4,  16, acGUI_Fontfont12_9488 } /* code 9488 */
  ,{  16,  15,   0,   4,  16, acGUI_Fontfont12_94BB } /* code 94BB */
  ,{  14,  15,   1,   4,  16, acGUI_Fontfont12_95F4 } /* code 95F4 */
  ,{  14,  15,   1,   4,  16, acGUI_Fontfont12_964D } /* code 964D */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop57 = {
   0x964D /* first character */
  ,0x964D /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 58] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop56 = {
   0x95F4 /* first character */
  ,0x95F4 /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 57] /* address of first character */
  ,&GUI_Fontfont12_Prop57 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop55 = {
   0x94BB /* first character */
  ,0x94BB /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 56] /* address of first character */
  ,&GUI_Fontfont12_Prop56 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop54 = {
   0x9488 /* first character */
  ,0x9488 /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 55] /* address of first character */
  ,&GUI_Fontfont12_Prop55 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop53 = {
   0x901F /* first character */
  ,0x901F /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 54] /* address of first character */
  ,&GUI_Fontfont12_Prop54 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop52 = {
   0x9009 /* first character */
  ,0x9009 /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 53] /* address of first character */
  ,&GUI_Fontfont12_Prop53 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop51 = {
   0x8FD4 /* first character */
  ,0x8FD4 /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 52] /* address of first character */
  ,&GUI_Fontfont12_Prop52 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop50 = {
   0x8F93 /* first character */
  ,0x8F93 /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 51] /* address of first character */
  ,&GUI_Fontfont12_Prop51 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop49 = {
   0x8F6C /* first character */
  ,0x8F6C /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 50] /* address of first character */
  ,&GUI_Fontfont12_Prop50 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop48 = {
   0x8DDD /* first character */
  ,0x8DDD /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 49] /* address of first character */
  ,&GUI_Fontfont12_Prop49 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop47 = {
   0x8C03 /* first character */
  ,0x8C03 /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 48] /* address of first character */
  ,&GUI_Fontfont12_Prop48 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop46 = {
   0x8BBE /* first character */
  ,0x8BBE /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 47] /* address of first character */
  ,&GUI_Fontfont12_Prop47 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop45 = {
   0x8BA4 /* first character */
  ,0x8BA4 /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 46] /* address of first character */
  ,&GUI_Fontfont12_Prop46 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop44 = {
   0x884C /* first character */
  ,0x884C /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 45] /* address of first character */
  ,&GUI_Fontfont12_Prop45 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop43 = {
   0x7F6E /* first character */
  ,0x7F6E /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 44] /* address of first character */
  ,&GUI_Fontfont12_Prop44 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop42 = {
   0x7EC6 /* first character */
  ,0x7EC6 /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 43] /* address of first character */
  ,&GUI_Fontfont12_Prop43 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop41 = {
   0x7C97 /* first character */
  ,0x7C97 /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 42] /* address of first character */
  ,&GUI_Fontfont12_Prop42 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop40 = {
   0x786E /* first character */
  ,0x786E /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 41] /* address of first character */
  ,&GUI_Fontfont12_Prop41 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop39 = {
   0x7535 /* first character */
  ,0x7535 /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 40] /* address of first character */
  ,&GUI_Fontfont12_Prop40 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop38 = {
   0x6DF1 /* first character */
  ,0x6DF1 /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 39] /* address of first character */
  ,&GUI_Fontfont12_Prop39 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop37 = {
   0x6D88 /* first character */
  ,0x6D88 /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 38] /* address of first character */
  ,&GUI_Fontfont12_Prop38 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop36 = {
   0x6D4B /* first character */
  ,0x6D4B /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 37] /* address of first character */
  ,&GUI_Fontfont12_Prop37 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop35 = {
   0x6B21 /* first character */
  ,0x6B21 /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 36] /* address of first character */
  ,&GUI_Fontfont12_Prop36 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop34 = {
   0x6A21 /* first character */
  ,0x6A21 /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 35] /* address of first character */
  ,&GUI_Fontfont12_Prop35 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop33 = {
   0x68C0 /* first character */
  ,0x68C0 /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 34] /* address of first character */
  ,&GUI_Fontfont12_Prop34 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop32 = {
   0x673A /* first character */
  ,0x673A /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 33] /* address of first character */
  ,&GUI_Fontfont12_Prop33 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop31 = {
   0x6570 /* first character */
  ,0x6570 /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 32] /* address of first character */
  ,&GUI_Fontfont12_Prop32 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop30 = {
   0x6392 /* first character */
  ,0x6392 /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 31] /* address of first character */
  ,&GUI_Fontfont12_Prop31 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop29 = {
   0x636E /* first character */
  ,0x636E /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 30] /* address of first character */
  ,&GUI_Fontfont12_Prop30 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop28 = {
   0x62E9 /* first character */
  ,0x62E9 /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 29] /* address of first character */
  ,&GUI_Fontfont12_Prop29 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop27 = {
   0x6269 /* first character */
  ,0x6269 /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 28] /* address of first character */
  ,&GUI_Fontfont12_Prop28 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop26 = {
   0x6267 /* first character */
  ,0x6267 /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 27] /* address of first character */
  ,&GUI_Fontfont12_Prop27 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop25 = {
   0x6253 /* first character */
  ,0x6253 /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 26] /* address of first character */
  ,&GUI_Fontfont12_Prop26 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop24 = {
   0x5F0F /* first character */
  ,0x5F0F /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 25] /* address of first character */
  ,&GUI_Fontfont12_Prop25 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop23 = {
   0x5EA6 /* first character */
  ,0x5EA6 /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 24] /* address of first character */
  ,&GUI_Fontfont12_Prop24 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop22 = {
   0x5DE5 /* first character */
  ,0x5DE6 /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 22] /* address of first character */
  ,&GUI_Fontfont12_Prop23 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop21 = {
   0x5C11 /* first character */
  ,0x5C11 /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 21] /* address of first character */
  ,&GUI_Fontfont12_Prop22 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop20 = {
   0x5C0F /* first character */
  ,0x5C0F /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 20] /* address of first character */
  ,&GUI_Fontfont12_Prop21 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop19 = {
   0x5B9A /* first character */
  ,0x5B9A /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 19] /* address of first character */
  ,&GUI_Fontfont12_Prop20 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop18 = {
   0x5B54 /* first character */
  ,0x5B54 /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 18] /* address of first character */
  ,&GUI_Fontfont12_Prop19 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop17 = {
   0x5947 /* first character */
  ,0x5947 /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 17] /* address of first character */
  ,&GUI_Fontfont12_Prop18 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop16 = {
   0x5934 /* first character */
  ,0x5934 /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 16] /* address of first character */
  ,&GUI_Fontfont12_Prop17 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop15 = {
   0x5927 /* first character */
  ,0x5927 /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 15] /* address of first character */
  ,&GUI_Fontfont12_Prop16 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop14 = {
   0x589E /* first character */
  ,0x589E /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 14] /* address of first character */
  ,&GUI_Fontfont12_Prop15 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop13 = {
   0x5757 /* first character */
  ,0x5757 /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 13] /* address of first character */
  ,&GUI_Fontfont12_Prop14 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop12 = {
   0x56DE /* first character */
  ,0x56DE /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 12] /* address of first character */
  ,&GUI_Fontfont12_Prop13 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop11 = {
   0x53F3 /* first character */
  ,0x53F3 /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 11] /* address of first character */
  ,&GUI_Fontfont12_Prop12 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop10 = {
   0x53D6 /* first character */
  ,0x53D6 /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 10] /* address of first character */
  ,&GUI_Fontfont12_Prop11 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop9 = {
   0x5347 /* first character */
  ,0x5347 /* last character  */
  ,&GUI_Fontfont12_CharInfo[  9] /* address of first character */
  ,&GUI_Fontfont12_Prop10 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop8 = {
   0x52A8 /* first character */
  ,0x52A8 /* last character  */
  ,&GUI_Fontfont12_CharInfo[  8] /* address of first character */
  ,&GUI_Fontfont12_Prop9 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop7 = {
   0x52A0 /* first character */
  ,0x52A0 /* last character  */
  ,&GUI_Fontfont12_CharInfo[  7] /* address of first character */
  ,&GUI_Fontfont12_Prop8 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop6 = {
   0x51CF /* first character */
  ,0x51CF /* last character  */
  ,&GUI_Fontfont12_CharInfo[  6] /* address of first character */
  ,&GUI_Fontfont12_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop5 = {
   0x5076 /* first character */
  ,0x5076 /* last character  */
  ,&GUI_Fontfont12_CharInfo[  5] /* address of first character */
  ,&GUI_Fontfont12_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop4 = {
   0x4F4D /* first character */
  ,0x4F4D /* last character  */
  ,&GUI_Fontfont12_CharInfo[  4] /* address of first character */
  ,&GUI_Fontfont12_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop3 = {
   0x4F20 /* first character */
  ,0x4F20 /* last character  */
  ,&GUI_Fontfont12_CharInfo[  3] /* address of first character */
  ,&GUI_Fontfont12_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop2 = {
   0x4EF6 /* first character */
  ,0x4EF6 /* last character  */
  ,&GUI_Fontfont12_CharInfo[  2] /* address of first character */
  ,&GUI_Fontfont12_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop1 = {
   0x4E0A /* first character */
  ,0x4E0B /* last character  */
  ,&GUI_Fontfont12_CharInfo[  0] /* address of first character */
  ,&GUI_Fontfont12_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontfont12 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,21 /* height of font  */
  ,21 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontfont12_Prop1}
  ,17 /* Baseline */
  ,9 /* Height of lowercase characters */
  ,12 /* Height of capital characters */
};

