/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font Converter for emWin version 5.28                       *
*        Compiled Jan 30 2015, 16:40:45                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: font12.c                                              *
* Font:        微软雅黑                                              *
* Height:      21                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  21                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: F:\02-Work\毕业设计\毕业设计\手持终端控制器\Client\TEXT\font12.txt*
* Character enabled:   0x31 (49)                                     *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontfont12;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0020[  1] = { /* code 0020, SPACE */
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0021[ 12] = { /* code 0021, EXCLAMATION MARK */
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  ________,
  ________,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0022[  4] = { /* code 0022, QUOTATION MARK */
  X_X_____,
  X_X_____,
  X_X_____,
  X_X_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0023[ 22] = { /* code 0023, NUMBER SIGN */
  ___X___X,________,
  ___X___X,________,
  ___X___X,________,
  _XXXXXXX,XX______,
  __X___X_,________,
  __X___X_,________,
  __X___X_,________,
  XXXXXXXX,X_______,
  __X___X_,________,
  _X___X__,________,
  _X___X__,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0024[ 15] = { /* code 0024, DOLLAR SIGN */
  ___XX___,
  __XXXX__,
  _X_XX_X_,
  XX_XX___,
  XX_XX___,
  XX_XX___,
  _XXXX___,
  ___XXX__,
  ___XXXX_,
  ___XXXX_,
  ___XXXX_,
  X__XXXX_,
  _XXXXX__,
  ___XX___,
  ___XX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0025[ 24] = { /* code 0025, PERCENT SIGN */
  _XXX____,_X______,
  X___X___,X_______,
  X___X___,X_______,
  X___X__X,________,
  X___X_X_,________,
  _XXX__X_,________,
  _____X__,XXX_____,
  _____X_X,___X____,
  ____X__X,___X____,
  ___X___X,___X____,
  ___X___X,___X____,
  __X_____,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0026[ 24] = { /* code 0026, AMPERSAND */
  ___XXXX_,________,
  __XX__XX,________,
  __XX__XX,________,
  __XX__XX,__XX____,
  ___XXXX_,__XX____,
  __XXXXX_,__XX____,
  _XX___XX,__XX____,
  XX_____X,X_X_____,
  XX______,XXX_____,
  XX______,XX______,
  _XX____X,XXX_____,
  __XXXXX_,__XXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0027[  4] = { /* code 0027, APOSTROPHE */
  X_______,
  X_______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0028[ 15] = { /* code 0028, LEFT PARENTHESIS */
  ___X____,
  __X_____,
  _X______,
  _X______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  _X______,
  _X______,
  __X_____,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0029[ 15] = { /* code 0029, RIGHT PARENTHESIS */
  X_______,
  _X______,
  __X_____,
  __X_____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  __X_____,
  __X_____,
  _X______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_002A[  6] = { /* code 002A, ASTERISK */
  ___X____,
  ___X____,
  XXXXXXX_,
  ___X____,
  __X_X___,
  _X___X__};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_002B[  7] = { /* code 002B, PLUS SIGN */
  ___X____,
  ___X____,
  ___X____,
  XXXXXXX_,
  ___X____,
  ___X____,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_002C[  4] = { /* code 002C, COMMA */
  _X______,
  _X______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_002D[  1] = { /* code 002D, HYPHEN-MINUS */
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_002E[  2] = { /* code 002E, FULL STOP */
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_002F[ 14] = { /* code 002F, SOLIDUS */
  _____XX_,
  ____XX__,
  ____XX__,
  ____XX__,
  ___XX___,
  ___XX___,
  ___XX___,
  __XX____,
  __XX____,
  __XX____,
  _XX_____,
  _XX_____,
  _XX_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0030[ 12] = { /* code 0030, DIGIT ZERO */
  __XXXX__,
  _XX__XX_,
  _X____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____X_,
  _XX__XX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0031[ 12] = { /* code 0031, DIGIT ONE */
  ___X____,
  _XXX____,
  X_XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0032[ 12] = { /* code 0032, DIGIT TWO */
  _XXXX___,
  X___XXX_,
  _____XX_,
  _____XX_,
  _____XX_,
  ____XX__,
  ___XXX__,
  __XX____,
  _XX_____,
  XX______,
  XX______,
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0033[ 12] = { /* code 0033, DIGIT THREE */
  _XXXXX__,
  X___XXX_,
  _____XX_,
  _____XX_,
  ____XX__,
  _XXXX___,
  _____XX_,
  ______XX,
  ______XX,
  ______XX,
  X____XX_,
  _XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0034[ 24] = { /* code 0034, DIGIT FOUR */
  ______XX,________,
  _____XXX,________,
  ____XXXX,________,
  ____X_XX,________,
  ___XX_XX,________,
  __XX__XX,________,
  _XX___XX,________,
  _X____XX,________,
  XXXXXXXX,XX______,
  ______XX,________,
  ______XX,________,
  ______XX,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0035[ 12] = { /* code 0035, DIGIT FIVE */
  XXXXXX__,
  XX______,
  XX______,
  XX______,
  XX______,
  XXXXX___,
  ____XXX_,
  _____XX_,
  _____XX_,
  _____XX_,
  X___XX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0036[ 12] = { /* code 0036, DIGIT SIX */
  ___XXXX_,
  __XX____,
  _XX_____,
  XX______,
  XX______,
  XX_XXXX_,
  XXX__XXX,
  XX____XX,
  XX____XX,
  XX____XX,
  _XX__XX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0037[ 12] = { /* code 0037, DIGIT SEVEN */
  XXXXXXX_,
  _____XX_,
  ____XX__,
  ____XX__,
  ____XX__,
  ___XX___,
  ___XX___,
  ___XX___,
  __XX____,
  __XX____,
  __XX____,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0038[ 12] = { /* code 0038, DIGIT EIGHT */
  ___XXXX_,
  _XX___XX,
  _XX___XX,
  _XX___XX,
  __XX_XX_,
  ___XXX__,
  _XX__XX_,
  XX____XX,
  XX____XX,
  XX____XX,
  _XX__XX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0039[ 12] = { /* code 0039, DIGIT NINE */
  __XXXX__,
  _XX__XX_,
  XX____XX,
  XX____XX,
  XX____XX,
  _XX__XXX,
  __XXX_XX,
  ______XX,
  ______XX,
  _____XX_,
  _X___XX_,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_003A[  9] = { /* code 003A, COLON */
  XX______,
  XX______,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_003B[ 11] = { /* code 003B, SEMICOLON */
  XX______,
  XX______,
  ________,
  ________,
  ________,
  ________,
  ________,
  _X______,
  _X______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_003C[  7] = { /* code 003C, LESS-THAN SIGN */
  ______X_,
  ___XXXX_,
  _XXX____,
  XX______,
  _XXX____,
  ___XXXX_,
  ______X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_003D[  4] = { /* code 003D, EQUALS SIGN */
  XXXXXXXX,
  ________,
  ________,
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_003E[  7] = { /* code 003E, GREATER-THAN SIGN */
  X_______,
  XXXX____,
  ___XXX__,
  _____XX_,
  ___XXX__,
  XXXX____,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_003F[ 12] = { /* code 003F, QUESTION MARK */
  _XXXXX__,
  X___XXX_,
  _____XX_,
  _____XX_,
  ____XX__,
  ___XX___,
  __XX____,
  __XX____,
  ________,
  ________,
  __XX____,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0040[ 28] = { /* code 0040, COMMERCIAL AT */
  ____XXXX,XX______,
  ___XX___,__XX____,
  __X_____,___XX___,
  _X____XX,XX__X___,
  XX___X__,_X___X__,
  X___X___,_X___X__,
  X___X___,_X___X__,
  X___X___,_X___X__,
  X___X___,_X___X__,
  X___XX__,XX__X___,
  _X___XXX,_XXX____,
  _XX_____,________,
  __XX____,__X_____,
  ____XXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0041[ 24] = { /* code 0041, LATIN CAPITAL LETTER A */
  _____XX_,________,
  ____XXXX,________,
  ____XXXX,________,
  ____X_XX,________,
  ___XX__X,X_______,
  ___XX__X,X_______,
  __XX____,X_______,
  __XXXXXX,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _X______,_XX_____,
  XX______,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0042[ 12] = { /* code 0042, LATIN CAPITAL LETTER B */
  XXXXXX__,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX__XX__,
  XXXXX___,
  XX___XX_,
  XX____XX,
  XX____XX,
  XX____XX,
  XX___XX_,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0043[ 24] = { /* code 0043, LATIN CAPITAL LETTER C */
  ____XXXX,________,
  __XX____,X_______,
  _XX_____,________,
  _X______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  _XX_____,________,
  __XX____,X_______,
  ___XXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0044[ 24] = { /* code 0044, LATIN CAPITAL LETTER D */
  XXXXXX__,________,
  XX____XX,________,
  XX_____X,X_______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,X_______,
  XX_____X,X_______,
  XX____XX,________,
  XXXXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0045[ 12] = { /* code 0045, LATIN CAPITAL LETTER E */
  XXXXXXX_,
  XX______,
  XX______,
  XX______,
  XX______,
  XXXXXX__,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0046[ 12] = { /* code 0046, LATIN CAPITAL LETTER F */
  XXXXXX__,
  XX______,
  XX______,
  XX______,
  XX______,
  XXXXXX__,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0047[ 24] = { /* code 0047, LATIN CAPITAL LETTER G */
  ____XXXX,X_______,
  __XX____,_X______,
  _XX_____,________,
  _XX_____,________,
  XX______,________,
  XX______,________,
  XX____XX,XX______,
  XX______,XX______,
  XX______,XX______,
  _XX_____,XX______,
  __XX____,XX______,
  ___XXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0048[ 24] = { /* code 0048, LATIN CAPITAL LETTER H */
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XXXXXXXX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0049[ 12] = { /* code 0049, LATIN CAPITAL LETTER I */
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_004A[ 12] = { /* code 004A, LATIN CAPITAL LETTER J */
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  __XX____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_004B[ 12] = { /* code 004B, LATIN CAPITAL LETTER K */
  XX____XX,
  XX___XX_,
  XX__XX__,
  XX_XX___,
  XX_X____,
  XXX_____,
  XXXX____,
  XX_X____,
  XX_XX___,
  XX__XX__,
  XX___XX_,
  XX____XX};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_004C[ 12] = { /* code 004C, LATIN CAPITAL LETTER L */
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_004D[ 24] = { /* code 004D, LATIN CAPITAL LETTER M */
  XX______,___X____,
  XXX_____,__XX____,
  XXX_____,__XX____,
  X_XX____,_X_X____,
  X_XX____,_X_X____,
  X__XX___,XX_X____,
  X__XX___,X__X____,
  X___X___,X__X____,
  X___XX_X,___X____,
  X____X_X,___X____,
  X____XXX,___X____,
  X_____X_,___X____};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_004E[ 24] = { /* code 004E, LATIN CAPITAL LETTER N */
  XXX_____,XX______,
  XXXX____,XX______,
  XXXX____,XX______,
  XX_XX___,XX______,
  XX_XX___,XX______,
  XX__XX__,XX______,
  XX___X__,XX______,
  XX___XX_,XX______,
  XX____X_,XX______,
  XX____XX,XX______,
  XX_____X,XX______,
  XX_____X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_004F[ 24] = { /* code 004F, LATIN CAPITAL LETTER O */
  ___XXXXX,X_______,
  __XX____,XX______,
  _XX_____,_XX_____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  _XX_____,_XX_____,
  __XX____,XX______,
  ___XXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0050[ 12] = { /* code 0050, LATIN CAPITAL LETTER P */
  XXXXXX__,
  XX___XX_,
  XX____XX,
  XX____XX,
  XX____XX,
  XX___XX_,
  XXXXXX__,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0051[ 28] = { /* code 0051, LATIN CAPITAL LETTER Q */
  ___XXXXX,X_______,
  __XX____,XX______,
  _XX_____,_XX_____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  _XX_____,_XX_____,
  __XX____,XX______,
  ___XXXXX,XX______,
  ________,_XX_____,
  ________,__XX____};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0052[ 12] = { /* code 0052, LATIN CAPITAL LETTER R */
  XXXXXX__,
  XX__XXX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX__XX__,
  XXXXX___,
  XX__X___,
  XX__XX__,
  XX___XX_,
  XX___XX_,
  XX____XX};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0053[ 12] = { /* code 0053, LATIN CAPITAL LETTER S */
  __XXXX__,
  _XX___X_,
  XX______,
  XX______,
  XXX_____,
  _XXX____,
  ___XXX__,
  _____XXX,
  ______XX,
  ______XX,
  X____XXX,
  _XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0054[ 12] = { /* code 0054, LATIN CAPITAL LETTER T */
  XXXXXXXX,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0055[ 24] = { /* code 0055, LATIN CAPITAL LETTER U */
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  _XX____X,X_______,
  __XXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0056[ 24] = { /* code 0056, LATIN CAPITAL LETTER V */
  XX______,_XX_____,
  XX______,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX____X,X_______,
  __XX___X,X_______,
  __XX__XX,________,
  __XX__XX,________,
  ___XX_X_,________,
  ___XXXX_,________,
  ___XXXX_,________,
  ____XX__,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0057[ 24] = { /* code 0057, LATIN CAPITAL LETTER W */
  XX_____X,X_____XX,
  XX_____X,X_____XX,
  _XX___XX,XX____X_,
  _XX___XX,XX___XX_,
  _XX___X_,_X___XX_,
  _XX__XX_,_XX__XX_,
  __X__XX_,_XX__X__,
  __XX_X__,__X__X__,
  __XXXX__,__XXXX__,
  __XXXX__,__XXXX__,
  ___XX___,___XX___,
  ___XX___,___XX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0058[ 24] = { /* code 0058, LATIN CAPITAL LETTER X */
  XX______,XX______,
  _XX____X,X_______,
  __X___XX,________,
  __XX__XX,________,
  ___XXXX_,________,
  ____XX__,________,
  ____XX__,________,
  ___XXXX_,________,
  __XX__XX,________,
  __X___XX,________,
  _XX____X,X_______,
  XX______,XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0059[ 24] = { /* code 0059, LATIN CAPITAL LETTER Y */
  XX______,XX______,
  _XX____X,X_______,
  _XX____X,X_______,
  __XX__XX,________,
  __XX__XX,________,
  ___XXXX_,________,
  ___XXXX_,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_005A[ 24] = { /* code 005A, LATIN CAPITAL LETTER Z */
  _XXXXXXX,XX______,
  ________,X_______,
  _______X,________,
  ______X_,________,
  _____XX_,________,
  _____X__,________,
  ____X___,________,
  ___XX___,________,
  __XX____,________,
  __X_____,________,
  _X______,________,
  XXXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_005B[ 15] = { /* code 005B, LEFT SQUARE BRACKET */
  XXX_____,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_005C[ 14] = { /* code 005C, REVERSE SOLIDUS */
  X_______,
  _X______,
  _X______,
  _XX_____,
  __X_____,
  __X_____,
  ___X____,
  ___X____,
  ____X___,
  ____X___,
  ____XX__,
  _____X__,
  _____X__,
  ______X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_005D[ 15] = { /* code 005D, RIGHT SQUARE BRACKET */
  XXX_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_005E[  7] = { /* code 005E, CIRCUMFLEX ACCENT */
  ____X___,
  ___XXX__,
  ___X_X__,
  __X__XX_,
  _XX___X_,
  _X____X_,
  X______X};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_005F[  1] = { /* code 005F, LOW LINE */
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0060[  3] = { /* code 0060, GRAVE ACCENT */
  X_______,
  _X______,
  __X_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0061[  9] = { /* code 0061, LATIN SMALL LETTER A */
  __XXXX__,
  _X___XX_,
  _____XX_,
  ____XXX_,
  _XXX_XX_,
  XX___XX_,
  XX___XX_,
  XX__XXX_,
  _XXX_XX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0062[ 26] = { /* code 0062, LATIN SMALL LETTER B */
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX_XXXX_,________,
  XXX___XX,________,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XXX___XX,________,
  XX_XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0063[  9] = { /* code 0063, LATIN SMALL LETTER C */
  __XXXX__,
  _XX_____,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  _XX_____,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0064[ 13] = { /* code 0064, LATIN SMALL LETTER D */
  ______XX,
  ______XX,
  ______XX,
  ______XX,
  __XXX_XX,
  _XX__XXX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  _XX__XXX,
  __XXX_XX};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0065[  9] = { /* code 0065, LATIN SMALL LETTER E */
  __XXXX__,
  _XX__XX_,
  XX____XX,
  XX____XX,
  XXXXXXXX,
  XX______,
  XX______,
  _XX___X_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0066[ 13] = { /* code 0066, LATIN SMALL LETTER F */
  __XXX___,
  _XX_____,
  _XX_____,
  _XX_____,
  XXXXX___,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0067[ 13] = { /* code 0067, LATIN SMALL LETTER G */
  __XXX_XX,
  _XX__XXX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  _XX__XXX,
  __XXX_XX,
  ______XX,
  ______XX,
  _X___XX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0068[ 13] = { /* code 0068, LATIN SMALL LETTER H */
  XX______,
  XX______,
  XX______,
  XX______,
  XX_XXXX_,
  XXX__XXX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0069[ 13] = { /* code 0069, LATIN SMALL LETTER I */
  XX______,
  XX______,
  ________,
  ________,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_006A[ 17] = { /* code 006A, LATIN SMALL LETTER J */
  ___XX___,
  ___XX___,
  ________,
  ________,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  __XX____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_006B[ 13] = { /* code 006B, LATIN SMALL LETTER K */
  XX______,
  XX______,
  XX______,
  XX______,
  XX____X_,
  XX___X__,
  XX__X___,
  XX_X____,
  XXXX____,
  XX_XX___,
  XX__XX__,
  XX___XX_,
  XX____XX};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_006C[ 13] = { /* code 006C, LATIN SMALL LETTER L */
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_006D[ 18] = { /* code 006D, LATIN SMALL LETTER M */
  XX_XXXX_,_XXX____,
  XXX__XXX,X__XX___,
  XX____XX,___XX___,
  XX____XX,___XX___,
  XX____XX,___XX___,
  XX____XX,___XX___,
  XX____XX,___XX___,
  XX____XX,___XX___,
  XX____XX,___XX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_006E[  9] = { /* code 006E, LATIN SMALL LETTER N */
  XX_XXXX_,
  XXX__XXX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_006F[ 18] = { /* code 006F, LATIN SMALL LETTER O */
  __XXXXX_,________,
  _XX___XX,________,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  _XX___XX,________,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0070[ 26] = { /* code 0070, LATIN SMALL LETTER P */
  XX_XXXX_,________,
  XXX___XX,________,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XXX___XX,________,
  XX_XXXX_,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0071[ 13] = { /* code 0071, LATIN SMALL LETTER Q */
  __XXX_XX,
  _XX__XXX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  _XX__XXX,
  __XXX_XX,
  ______XX,
  ______XX,
  ______XX,
  ______XX};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0072[  9] = { /* code 0072, LATIN SMALL LETTER R */
  XX_XX___,
  XXX_____,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0073[  9] = { /* code 0073, LATIN SMALL LETTER S */
  _XXXX___,
  XX___X__,
  XX______,
  XXX_____,
  _XXXX___,
  ___XXX__,
  ____XX__,
  X___XX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0074[ 12] = { /* code 0074, LATIN SMALL LETTER T */
  _XX_____,
  _XX_____,
  _XX_____,
  XXXXX___,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0075[  9] = { /* code 0075, LATIN SMALL LETTER U */
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XXX__XXX,
  _XXXX_XX};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0076[  9] = { /* code 0076, LATIN SMALL LETTER V */
  XX____XX,
  XX____XX,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  __X__X__,
  __XXXX__,
  __XXXX__,
  ___XX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0077[ 18] = { /* code 0077, LATIN SMALL LETTER W */
  XX____X_,____X___,
  XX____XX,____X___,
  _XX__XXX,___X____,
  _XX__XXX,___X____,
  _XX__X__,X__X____,
  __X__X__,X__X____,
  __XXXX__,XXXX____,
  __XXX___,_XX_____,
  ___XX___,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0078[  9] = { /* code 0078, LATIN SMALL LETTER X */
  XX____XX,
  _XX__XX_,
  __X__X__,
  __XXXX__,
  ___XX___,
  __XXXX__,
  __X_XX__,
  _XX__XX_,
  XX____XX};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_0079[ 13] = { /* code 0079, LATIN SMALL LETTER Y */
  XX____XX,
  _X____X_,
  _XX__XX_,
  _XX__XX_,
  __X__X__,
  __X_XX__,
  __XXXX__,
  ___XX___,
  ___XX___,
  ___X____,
  ___X____,
  __XX____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_007A[  9] = { /* code 007A, LATIN SMALL LETTER Z */
  XXXXXXXX,
  _____XX_,
  _____X__,
  ____XX__,
  ___XX___,
  __XX____,
  __X_____,
  _XX_____,
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_007B[ 15] = { /* code 007B, LEFT CURLY BRACKET */
  __X_____,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  X_______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  __X_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_007C[ 17] = { /* code 007C, VERTICAL LINE */
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_007D[ 15] = { /* code 007D, RIGHT CURLY BRACKET */
  X_______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  __X_____,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_007E[  2] = { /* code 007E, TILDE */
  _XXX___X,
  X___XXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_007F[  1] = { /* code 007F, <control> */
  ________};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_4E0A[ 26] = { /* code 4E0A */
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,XXXXXXX_,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  XXXXXXXX,XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_4E0B[ 28] = { /* code 4E0B */
  XXXXXXXX,XXXXXXXX,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,XX______,
  _______X,_XX_____,
  _______X,___XX___,
  _______X,____XX__,
  _______X,_____XX_,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_4E3B[ 28] = { /* code 4E3B */
  _______X,________,
  _______X,X_______,
  ________,X_______,
  _XXXXXXX,XXXXXXX_,
  ________,X_______,
  ________,X_______,
  ________,X_______,
  ________,X_______,
  _XXXXXXX,XXXXXXX_,
  ________,X_______,
  ________,X_______,
  ________,X_______,
  ________,X_______,
  XXXXXXXX,XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_4ECE[ 30] = { /* code 4ECE */
  ___X____,_X______,
  ___X____,_X______,
  ___X____,_X______,
  ___X____,_X______,
  ___X____,_X______,
  ___X____,_X______,
  ___XX___,_X______,
  ___XXX__,XXX_____,
  ___X__X_,X_X_____,
  __X____X,X_X_____,
  __X____X,___X____,
  __X____X,___X____,
  _X____X_,____X___,
  _X___X__,____XX__,
  X___X___,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_4EF6[ 28] = { /* code 4EF6 */
  ___X____,__X_____,
  ___X___X,__X_____,
  __X____X,__X_____,
  __X___XX,XXXXXXX_,
  _XX___X_,__X_____,
  _XX__X__,__X_____,
  XXX__X__,__X_____,
  X_X_____,__X_____,
  __X__XXX,XXXXXXXX,
  __X_____,__X_____,
  __X_____,__X_____,
  __X_____,__X_____,
  __X_____,__X_____,
  __X_____,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_4F20[ 30] = { /* code 4F20 */
  ___X____,_X______,
  ___X____,_X______,
  __X__XXX,XXXXXXX_,
  __X_____,X_______,
  __X____X,________,
  _XX_XXXX,XXXXXXXX,
  _XX____X,________,
  X_X___X_,________,
  X_X___XX,XXXXXXX_,
  __X_____,_____X__,
  __X__XX_,____X___,
  __X___XX,___X____,
  __X_____,XXX_____,
  __X_____,__XX____,
  __X_____,___XX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_4F4D[ 30] = { /* code 4F4D */
  ____X___,_X______,
  ___X____,__X_____,
  ___X____,___X____,
  __X__XXX,XXXXXXXX,
  __X_____,________,
  __X___X_,______X_,
  _XX___X_,_____XX_,
  XXX____X,_____X__,
  X_X____X,_____X__,
  __X____X,____X___,
  __X_____,X___X___,
  __X_____,X__X____,
  __X_____,___X____,
  __X_XXXX,XXXXXXXX,
  __X_____,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_4F5C[ 30] = { /* code 4F5C */
  ___X____,X_______,
  ___X___X,________,
  __X____X,XXXXXXXX,
  __X___X_,_X______,
  __X__X__,_X______,
  _XX__X__,_X______,
  _XX_X___,_XXXXXX_,
  X_X_____,_X______,
  X_X_____,_X______,
  __X_____,_X______,
  __X_____,_XXXXXXX,
  __X_____,_X______,
  __X_____,_X______,
  __X_____,_X______,
  __X_____,_X______};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_5076[ 30] = { /* code 5076 */
  ___X____,________,
  ___X__XX,XXXXXX__,
  __X___X_,_X___X__,
  __X___XX,XXXXXX__,
  __X___X_,_X___X__,
  _XX___X_,_X___X__,
  _XX___XX,XXXXXX__,
  X_X_____,_X______,
  X_X__XXX,XXXXXXX_,
  __X__X__,_X____X_,
  __X__X__,_X_X__X_,
  __X__X_X,XXXXX_X_,
  __X__X__,____X_X_,
  __X__X__,______X_,
  __X__X__,___XXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_5149[ 28] = { /* code 5149 */
  _______X,________,
  _X_____X,_____X__,
  __X____X,____X___,
  ___X___X,___X____,
  ____X__X,__X_____,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  ____X___,_X______,
  ____X___,_X______,
  ____X___,_X______,
  ___X____,_X____X_,
  ___X____,_X____X_,
  _XX_____,_X____X_,
  XX______,_XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_5165[ 28] = { /* code 5165 */
  ____X___,________,
  _____X__,________,
  ______X_,________,
  ______XX,________,
  ______XX,________,
  ______X_,X_______,
  _____XX_,X_______,
  _____X__,_X______,
  ____XX__,_X______,
  ____X___,__X_____,
  ___XX___,__XX____,
  __XX____,___XX___,
  _XX_____,____XX__,
  XX______,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_51C6[ 30] = { /* code 51C6 */
  _______X,__X_____,
  X_____XX,__XX____,
  _X____X_,___X____,
  _XX__XXX,XXXXXXXX,
  __X_XXX_,___X____,
  ____XXX_,___X____,
  ___XX_XX,XXXXXXX_,
  ______X_,___X____,
  __X___X_,___X____,
  _XX___XX,XXXXXXX_,
  _X____X_,___X____,
  _X____X_,___X____,
  X_____X_,___X____,
  X_____XX,XXXXXXXX,
  ______X_,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_51CF[ 30] = { /* code 51CF */
  ________,___XXX__,
  X_______,___X_XX_,
  _X__XXXX,XXXXXXXX,
  __X_X___,___X____,
  ____X_XX,XX_X____,
  ____X___,___X__X_,
  __X_X___,___X__X_,
  __X_X_XX,XX_X_X__,
  _X__X_X_,_X_X_X__,
  _X__X_X_,_X_XXX__,
  _X__X_X_,_X_XX___,
  X__X__XX,XX_XX__X,
  X__X__X_,__XXX__X,
  __XX____,_XX__X_X,
  __X_____,X____XX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_5207[ 30] = { /* code 5207 */
  __X_____,________,
  __X___XX,XXXXXXX_,
  __X_____,XX___XX_,
  __X_____,X____XX_,
  XXXXXX__,X____XX_,
  __X_____,X____X__,
  __X_____,X____X__,
  __X_____,X____X__,
  __X_____,X____X__,
  __X___X_,X____X__,
  __X_XX_X,X____X__,
  __XX___X,_____X__,
  _XX___XX,_____X__,
  _____XX_,_XXXX___,
  ____XX__,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_52A0[ 30] = { /* code 52A0 */
  ___X____,________,
  ___X____,________,
  ___X____,_XXXXXX_,
  _XXXXXX_,_X____X_,
  ___X__X_,_X____X_,
  ___X__X_,_X____X_,
  ___X__X_,_X____X_,
  ___X__X_,_X____X_,
  ___X__X_,_X____X_,
  ___X__X_,_X____X_,
  __X___X_,_X____X_,
  __X___X_,_X____X_,
  _XX___X_,_XXXXXX_,
  _X_XXX__,_X____X_,
  X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_52A8[ 28] = { /* code 52A8 */
  ________,_X______,
  _XXXXXX_,_X______,
  ________,_X______,
  _______X,XXXXXX__,
  ________,_X___X__,
  XXXXXXX_,_X___X__,
  __X_____,_X___X__,
  __X_____,_X___X__,
  _X__X___,_X___X__,
  _X___X__,X____X__,
  _X__XX__,X____X__,
  XXXX__XX,X____X__,
  _______X,_____X__,
  ______X_,__XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_5347[ 30] = { /* code 5347 */
  ________,___X____,
  ______XX,XX_X____,
  XXXXXX__,___X____,
  ____X___,___X____,
  ____X___,___X____,
  ____X___,___X____,
  XXXXXXXX,XXXXXXXX,
  ____X___,___X____,
  ____X___,___X____,
  ____X___,___X____,
  ____X___,___X____,
  ___X____,___X____,
  __XX____,___X____,
  _XX_____,___X____,
  XX______,___X____};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_53C2[ 30] = { /* code 53C2 */
  _______X,________,
  _____XX_,_X______,
  ____X___,__X_____,
  __XXXXXX,XXXX____,
  ______X_,____X___,
  _XXXXXXX,XXXXXXX_,
  ____XX__,_X______,
  ___XX___,X_X_____,
  _XX___XX,___XX___,
  XX__XX__,_XX__XX_,
  ___X___X,XX______,
  ____XXXX,___XX___,
  __XXX___,_XXX____,
  ______XX,X_______,
  __XXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_53D6[ 26] = { /* code 53D6 */
  XXXXXXXX,XXXXXX__,
  _X___X__,X____X__,
  _X___X__,X____X__,
  _XXXXX__,X____X__,
  _X___X__,_X__X___,
  _X___X__,_X__X___,
  _XXXXX__,_X__X___,
  _X___X__,_XXX____,
  _X___X__,__XX____,
  _X_XXXXX,__XX____,
  XXX__X__,XX_XX___,
  _____X_X,X___XX__,
  _____XXX,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_53F3[ 30] = { /* code 53F3 */
  _______X,________,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  ______X_,________,
  _____X__,________,
  ____XX__,________,
  ___XX___,________,
  ___XXXXX,XXXXXX__,
  __XXX___,_____X__,
  _XX_X___,_____X__,
  XX__X___,_____X__,
  ____X___,_____X__,
  ____X___,_____X__,
  ____XXXX,XXXXXX__,
  ____X___,_____X__};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_56DE[ 28] = { /* code 56DE */
  XXXXXXXX,XXXXXX__,
  X_______,_____X__,
  X_______,_____X__,
  X___XXXX,XX___X__,
  X___X___,_X___X__,
  X___X___,_X___X__,
  X___X___,_X___X__,
  X___X___,_X___X__,
  X___XXXX,XX___X__,
  X___X___,_X___X__,
  X_______,_____X__,
  X_______,_____X__,
  XXXXXXXX,XXXXXX__,
  X_______,_____X__};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_5757[ 28] = { /* code 5757 */
  __X_____,_X______,
  __X_____,_X______,
  __X_____,_X______,
  __X___XX,XXXXXX__,
  XXXXX___,_X___X__,
  __X_____,_X___X__,
  __X_____,_X___X__,
  __X_____,_X___X__,
  __X__XXX,XXXXXXXX,
  __X_____,XX______,
  __XXXX__,X_X_____,
  XXX____X,___X____,
  _____XX_,____XX__,
  ____XX__,______XX};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_589E[ 30] = { /* code 589E */
  __X____X,_____X__,
  __X_____,X__XX___,
  __X__XXX,XXXXXXX_,
  __X__X__,__X___X_,
  XXXXXX_X,__X_X_X_,
  __X__X__,X_XX__X_,
  __X__XXX,XXXXXXX_,
  __X__X__,______X_,
  __X_____,________,
  __X___XX,XXXXXX__,
  __X_X_X_,_____X__,
  _XXX__XX,XXXXXX__,
  X_____X_,_____X__,
  ______XX,XXXXXX__,
  ______X_,_____X__};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_5927[ 30] = { /* code 5927 */
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  _______X,________,
  _______X,________,
  ______XX,X_______,
  ______X_,X_______,
  ______X_,X_______,
  _____X__,_X______,
  ____X___,__X_____,
  ___X____,__XX____,
  _XX_____,___XX___,
  XX______,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_5934[ 30] = { /* code 5934 */
  __X____X,________,
  ___X___X,________,
  ____X__X,________,
  _____X_X,________,
  _XX____X,________,
  __XX___X,________,
  ___XX__X,________,
  _______X,________,
  XXXXXXXX,XXXXXX__,
  _______X,________,
  ______XX,X_______,
  ______X_,XX______,
  ____XX__,__XX____,
  __XXX___,___XX___,
  XX______,_____X__};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_5947[ 30] = { /* code 5947 */
  _______X,________,
  _XXXXXXX,XXXXXX__,
  ______XX,X_______,
  ____XX__,XXXX____,
  _XXX____,____XX__,
  ________,________,
  XXXXXXXX,XXXXXXX_,
  ________,____X___,
  __XXXXXX,X___X___,
  __X_____,X___X___,
  __X_____,X___X___,
  __X_____,X___X___,
  __XXXXXX,X___X___,
  __X_____,____X___,
  ________,_XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_5B54[ 28] = { /* code 5B54 */
  ________,_X______,
  _XXXXXXX,_X______,
  ______XX,_X______,
  _____XX_,_X______,
  ____XX__,_X______,
  ____X___,_X______,
  ____X_XX,_X______,
  __XXXX__,_X______,
  XX__X___,_X______,
  ____X___,_X____X_,
  ____X___,_X____X_,
  ____X___,_X____X_,
  ____X___,_X____X_,
  _XXXX___,_XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_5B9A[ 30] = { /* code 5B9A */
  _______X,________,
  _______X,X_______,
  _XXXXXXX,XXXXXXX_,
  _X______,______X_,
  ________,________,
  XXXXXXXX,XXXXXXXX,
  ________,X_______,
  ___X____,X_______,
  ___X____,X_______,
  ___X____,XXXXXXX_,
  __XX____,X_______,
  __XXX___,X_______,
  _XX_XX__,X_______,
  _X____XX,XXXXXXXX,
  X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_5C0F[ 28] = { /* code 5C0F */
  ________,X_______,
  ________,X_______,
  ________,X_______,
  ____X___,X__X____,
  ___XX___,X___X___,
  ___X____,X___X___,
  __X_____,X____X__,
  __X_____,X____XX_,
  _X______,X_____X_,
  _X______,X_____XX,
  X_______,X______X,
  ________,X_______,
  ________,X_______,
  ____XXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_5C11[ 28] = { /* code 5C11 */
  _______X,________,
  _______X,________,
  ___X___X,__X_____,
  __XX___X,___X____,
  __X____X,____X___,
  __X____X,_____X__,
  _X_____X,____X_X_,
  XX_____X,___X____,
  X______X,__X_____,
  ________,_X______,
  _______X,X_______,
  _____XXX,________,
  ___XXX__,________,
  XXX_____,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_5C4F[ 26] = { /* code 5C4F */
  __XXXXXX,XXXXXXX_,
  __X_____,______X_,
  __X_____,______X_,
  __XXXXXX,XXXXXXX_,
  __X__XX_,___XX___,
  __X___XX,__XX____,
  __X_XXXX,XXXXXXX_,
  __X___X_,___X____,
  __X___X_,___X____,
  __XXXXXX,XXXXXXXX,
  _XX___X_,___X____,
  _X___XX_,___X____,
  X___XX__,___X____};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_5DE5[ 26] = { /* code 5DE5 */
  _XXXXXXX,XXXXXXX_,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  XXXXXXXX,XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_5DE6[ 28] = { /* code 5DE6 */
  ______X_,________,
  ______X_,________,
  _____X__,________,
  _XXXXXXX,XXXXXXXX,
  _____X__,________,
  _____X__,________,
  ____X___,________,
  ____XXXX,XXXXXXX_,
  ___X____,_X______,
  ___X____,_X______,
  __X_____,_X______,
  _XX_____,_X______,
  _X______,_X______,
  X__XXXXX,XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_5E55[ 30] = { /* code 5E55 */
  _____X__,__X_____,
  XXXXXXXX,XXXXXXX_,
  _____X__,__X_____,
  __XXXXXX,XXXXX___,
  __X_____,____X___,
  __XXXXXX,XXXXX___,
  __X_____,____X___,
  __XXXXXX,XXXXX___,
  ______X_,________,
  _XXXXXXX,XXXXXX__,
  __XX___X,__X_____,
  XXXXXXXX,XXXXX___,
  ___X___X,___X_XX_,
  ___X___X,_XXX____,
  _______X,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_5EA6[ 28] = { /* code 5EA6 */
  ________,X_______,
  ________,_X______,
  __XXXXXX,XXXXXXXX,
  __X_____,________,
  __X___X_,____X___,
  __XXXXXX,XXXXXXXX,
  __X___X_,____X___,
  __X___XX,XXXXX___,
  __X_____,________,
  __X_XXXX,XXXXXX__,
  __X__X__,___XX___,
  _X____XX,XXX_____,
  _X____XX,XXXX____,
  X__XXX__,____XXXX};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_5F0F[ 30] = { /* code 5F0F */
  ________,_X_XX___,
  ________,_X__XX__,
  ________,_X___X__,
  XXXXXXXX,XXXXXXXX,
  ________,_X______,
  ________,_X______,
  _XXXXXXX,_X______,
  ____X___,_X______,
  ____X___,__X_____,
  ____X___,__X_____,
  ____X___,__X_____,
  ____X_XX,X_XX___X,
  __XXXX__,___X___X,
  XX______,___XX_XX,
  ________,____XXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_6253[ 28] = { /* code 6253 */
  ___X____,________,
  ___X___X,XXXXXXXX,
  ___X____,____X___,
  XXXXXX__,____X___,
  ___X____,____X___,
  ___X____,____X___,
  ___X_XX_,____X___,
  __XXX___,____X___,
  XX_X____,____X___,
  ___X____,____X___,
  ___X____,____X___,
  ___X____,____X___,
  ___X____,____X___,
  XXXX____,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_6267[ 28] = { /* code 6267 */
  __X_____,X_______,
  __X_____,X_______,
  __X_____,X_______,
  XXXXXXXX,XXXXX___,
  __X_____,X___X___,
  __X_____,X___X___,
  __X__XX_,X___X___,
  __XXX__X,X___X___,
  XXX____X,XX__X___,
  __X____X,__X_X___,
  __X___XX,____X__X,
  __X___X_,____X__X,
  __X__XX_,____X_XX,
  XXX_XX__,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_6269[ 28] = { /* code 6269 */
  __X_____,_X______,
  __X_____,__X_____,
  __X___XX,XXXXXXX_,
  XXXXX_X_,________,
  __X___X_,________,
  __X___X_,________,
  __X_X_X_,________,
  _XXX__X_,________,
  X_X___X_,________,
  __X___X_,________,
  __X__XX_,________,
  __X__X__,________,
  __X_XX__,________,
  XXX_X___,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_62E9[ 30] = { /* code 62E9 */
  __X_____,________,
  __X___XX,XXXXXXX_,
  __X____X,_____XX_,
  XXXXX___,X___XX__,
  __X_____,_XXX____,
  __X____X,XXXXX___,
  __X__XXX,__X__XXX,
  __X_X___,__X_____,
  _XXX__XX,XXXXXXX_,
  X_X_____,__X_____,
  __X_____,__X_____,
  __X__XXX,XXXXXXXX,
  __X_____,__X_____,
  __X_____,__X_____,
  XXX_____,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_6362[ 28] = { /* code 6362 */
  __X_____,X_______,
  __X____X,XXXXX___,
  XXXXX_X_,___X____,
  __X__X__,__X_____,
  __X__XXX,XXXXXX__,
  __X___X_,_X___X__,
  __XXX_X_,_X___X__,
  _XX___X_,_X___X__,
  X_X___X_,_X___X__,
  __X_XXXX,XXXXXXX_,
  __X_____,XX______,
  __X_____,X_X_____,
  __X___XX,___XX___,
  XXX_XX__,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_636E[ 30] = { /* code 636E */
  __X_____,________,
  __X___XX,XXXXXXX_,
  __X___X_,______X_,
  XXXXX_X_,______X_,
  __X___XX,XXXXXXX_,
  __X___X_,___X__X_,
  __X___X_,___X____,
  __X_X_XX,XXXXXXXX,
  _XXX__X_,___X____,
  X_X___X_,___X____,
  __X___XX,XXXXXXX_,
  __X__XXX,______X_,
  __X__X_X,______X_,
  __X__X_X,XXXXXXX_,
  XXX_X__X,______X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_6392[ 30] = { /* code 6392 */
  __X_____,X__X____,
  __X_____,X__X____,
  __X_____,X__X____,
  XXXXXXXX,X__XXXXX,
  __X_____,X__X____,
  __X_____,X__X____,
  __X_X___,X__X____,
  __XX_XXX,X__XXXX_,
  _XX_____,X__X____,
  X_X_____,X__X____,
  __X_____,X__X____,
  __X_XXXX,X__XXXXX,
  __X_____,X__X____,
  __X_____,X__X____,
  XXX_____,X__X____};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_64CD[ 30] = { /* code 64CD */
  __X_____,________,
  __X___XX,XXXXXX__,
  __X___X_,_____X__,
  XXXXX_XX,XXXXXX__,
  __X_____,________,
  __X__XXX,X__XXXX_,
  __X__X__,X__X__X_,
  __XXXX__,X__X__X_,
  _XX__XXX,X__XXXX_,
  X_X_____,_X______,
  __X__XXX,XXXXXXXX,
  __X_____,XXX_____,
  __X____X,_X_X____,
  __X___X_,_X__XX__,
  XXX_XX__,_X____XX};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_6570[ 30] = { /* code 6570 */
  ____X___,__X_____,
  _X__X__X,__X_____,
  __X_X_X_,__X_____,
  ____X___,_XXXXXX_,
  XXXXXXXX,_X___X__,
  ___XXX__,XX___X__,
  _XX_XXX_,XX___X__,
  X___X_X_,__X_X___,
  ___X____,__X_X___,
  XXXXXXX_,__X_X___,
  _XX___X_,__XX____,
  _XX__X__,__XX____,
  ___XX___,_XX_X___,
  __XX_XXX,XX___X__,
  XX_____X,X_____X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_6574[ 28] = { /* code 6574 */
  ____X___,___X____,
  XXXXXXXX,__X_____,
  ____X___,__XXXXXX,
  _XXXXXXX,_XX___X_,
  _X__X__X,X_X___X_,
  _XXXXXXX,___X_X__,
  ___XXX__,____XX__,
  _XX_XXXX,___XXXX_,
  XX__X___,XXX___XX,
  _XXXXXXX,XXXXXXX_,
  ________,X_______,
  ___X____,XXXXXX__,
  ___X____,X_______,
  XXXXXXXX,XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_65E0[ 26] = { /* code 65E0 */
  _XXXXXXX,XXXXXX__,
  _______X,________,
  _______X,________,
  _______X,________,
  ______X_,________,
  XXXXXXXX,XXXXXXX_,
  ______X_,________,
  _____X__,X_______,
  _____X__,X_______,
  ____X___,X_____X_,
  ___X____,X_____X_,
  _XX_____,X_____X_,
  XX______,XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_673A[ 28] = { /* code 673A */
  ___X____,________,
  ___X___X,XXXXX___,
  ___X___X,____X___,
  XXXXXX_X,____X___,
  ___X___X,____X___,
  __XX___X,____X___,
  __XXX__X,____X___,
  __XX_X_X,____X___,
  _X_X___X,____X___,
  XX_X___X,____X___,
  X__X___X,____X__X,
  ___X__X_,____X__X,
  ___X__X_,____X__X,
  ___X_X__,____XXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_6821[ 32] = { /* code 6821 */
  ________,_X______,
  __X_____,__X_____,
  __X_____,__X_____,
  __X___XX,XXXXXXX_,
  XXXXX___,________,
  __X_____,X__X____,
  __XX___X,____X___,
  _XXXX_X_,_____X__,
  _XX_XX_X,____X_X_,
  _XX____X,X__XX___,
  X_X_____,X__X____,
  X_X_____,XXXX____,
  __X_____,_XX_____,
  __X_____,XXX_____,
  __X___XX,___XX___,
  __X_XX__,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_68C0[ 30] = { /* code 68C0 */
  __X_____,_X______,
  __X_____,XXX_____,
  __X_____,X__X____,
  XXXXXX_X,___XX___,
  __X___X_,____XX__,
  __X__X__,_____XX_,
  _XXX__XX,XXXX____,
  _XX_X___,________,
  X_X__X__,X___X___,
  X_X__X__,X__X____,
  X_X___X_,_X_X____,
  __X___X_,_X_X____,
  __X_____,__X_____,
  __X_XXXX,XXXXXX__,
  __X_____,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_6A21[ 30] = { /* code 6A21 */
  __X____X,___X____,
  __X____X,___X____,
  __X__XXX,XXXXXXX_,
  __X____X,___X____,
  XXXXX__X,___X____,
  __X___XX,XXXXXX__,
  _XX___X_,_____X__,
  _XXX__XX,XXXXXX__,
  _XX_X_X_,_____X__,
  X_X___XX,XXXXXX__,
  X_X_____,_X______,
  __X__XXX,XXXXXXX_,
  __X_____,XXX_____,
  __X____X,X__X____,
  __X_XXX_,____XXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_6A2A[ 30] = { /* code 6A2A */
  ___X____,X___X___,
  ___X____,X___X___,
  ___X__XX,XXXXXXX_,
  XXXXXX__,X___X___,
  ___X____,X___X___,
  __XX__XX,XXXXXXXX,
  __XX____,__X_____,
  __XXX__X,XXXXXXX_,
  _XXX_X_X,__X___X_,
  XX_X___X,XXXXXXX_,
  X__X___X,__X___X_,
  ___X___X,XXXXXXX_,
  ___X____,_X_XX___,
  ___X___X,X___XXX_,
  ___X__XX,______XX};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_6B21[ 28] = { /* code 6B21 */
  _______X,________,
  _X_____X,________,
  __X___XX,XXXXXXX_,
  __XX__X_,______X_,
  ___X_X__,_X___XX_,
  _____X__,_X___X__,
  ___X____,_X______,
  ___X____,_XX_____,
  __X_____,X_X_____,
  __X_____,X__X____,
  _X_____X,___X____,
  X_____X_,____X___,
  X___XX__,_____XX_,
  ___XX___,______XX};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_6D4B[ 30] = { /* code 6D4B */
  X_______,_____X__,
  _X__XXXX,X__X_X__,
  __X_X___,X__X_X__,
  ____X_X_,X__X_X__,
  X___X_X_,X__X_X__,
  _X__X_X_,X__X_X__,
  __X_X_X_,X__X_X__,
  ____X_X_,X__X_X__,
  ____X_X_,X__X_X__,
  __X_X_X_,X__X_X__,
  __X___X_,___X_X__,
  _X___XX_,_____X__,
  _X__XX_X,_____X__,
  X__XX___,X____X__,
  X_XX____,_X_XXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_6D88[ 26] = { /* code 6D88 */
  X___X___,_X___X__,
  _X___X__,_X__X___,
  __X__XX_,_X_X____,
  ______X_,_X______,
  X_______,_X______,
  _X__XXXX,XXXXXX__,
  ____X___,_____X__,
  _X__XXXX,XXXXXX__,
  _X__X___,_____X__,
  _X__XXXX,XXXXXX__,
  X___X___,_____X__,
  X___X___,_____X__,
  X___X___,_XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_6DF1[ 30] = { /* code 6DF1 */
  XX______,________,
  _XX_XXXX,XXXXXX__,
  __XXX___,_____X__,
  _______X,X_XX____,
  X_____XX,___XX___,
  _X__XX__,_X___X__,
  __X_____,_X______,
  ____XXXX,XXXXXX__,
  __X_____,XXX_____,
  __X____X,_XX_____,
  _X____XX,_X_X____,
  _X___XX_,_X__X___,
  _X__XX__,_X___XX_,
  X___X___,_X______,
  X_______,_X______};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_73AF[ 30] = { /* code 73AF */
  XXXXX_XX,XXXXXX__,
  __X_____,_X______,
  __X_____,_X______,
  __X_____,XX______,
  __X_____,X_______,
  XXXXX__X,XX_X____,
  __X____X,_X__X___,
  __X___XX,_X__X___,
  __X__XX_,_X___X__,
  __XXXX__,_X___XX_,
  _XX_X___,_X____X_,
  X_______,_X______,
  ________,_X______,
  ________,_X______,
  ________,_X______};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_7535[ 28] = { /* code 7535 */
  ______X_,________,
  ______X_,________,
  XXXXXXXX,XXXXX___,
  X_____X_,____X___,
  X_____X_,____X___,
  X_____X_,____X___,
  XXXXXXXX,XXXXX___,
  X_____X_,____X___,
  X_____X_,____X___,
  X_____X_,____X___,
  XXXXXXXX,XXXXX___,
  X_____X_,_____X__,
  ______X_,_____X__,
  ______XX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_786E[ 28] = { /* code 786E */
  ________,_X______,
  _XXXXX__,XXXXX___,
  ___X___X,___XX___,
  ___X__X_,___X____,
  __X__X_X,XXXXXXX_,
  __XXXX_X,__X___X_,
  _XX__X_X,__X___X_,
  _XX__X_X,XXXXXXX_,
  X_X__X_X,__X___X_,
  __X__X_X,__X___X_,
  __X__X_X,XXXXXXX_,
  __XXXXXX,__X___X_,
  __X___X_,__X___X_,
  _____X__,__X_XXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_7AD6[ 28] = { /* code 7AD6 */
  ____X___,________,
  _X__X_XX,XXXXXX__,
  _X__X__X,____XX__,
  _X__X__X,X__XX___,
  _X__X___,XXX_____,
  _X__X__X,XXXX____,
  _X__XXX_,____XXX_,
  _______X,X_______,
  __XXXXXX,XXXXXX__,
  ____X___,___X____,
  ____X___,__X_____,
  _____X__,__X_____,
  _____X__,_X______,
  XXXXXXXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_7C97[ 30] = { /* code 7C97 */
  ___X____,________,
  X__X__XX,XXXXXX__,
  X__X_X_X,_____X__,
  _X_X_X_X,_____X__,
  _X_XX__X,_____X__,
  ___X___X,XXXXXX__,
  XXXXXX_X,_____X__,
  ___X___X,_____X__,
  __XXX__X,_____X__,
  _XXXXX_X,XXXXXX__,
  XX_X__XX,_____X__,
  X__X___X,_____X__,
  ___X___X,_____X__,
  ___X_XXX,XXXXXXX_,
  ___X____,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_7EBF[ 28] = { /* code 7EBF */
  ___X____,_X_XXX__,
  __X_____,_X______,
  __X_X___,_XXXXXX_,
  _X_X_XXX,XXX_____,
  XX_X____,_X______,
  XXX_____,_X______,
  __X_____,_XXXXXXX,
  _X___XXX,XXX_____,
  XXXXX___,_XX_____,
  XX______,_XX___X_,
  ________,__X_XX__,
  __XXXX__,__XX___X,
  XX______,XXXXX__X,
  _____XXX,____XXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_7EC6[ 28] = { /* code 7EC6 */
  ___X____,________,
  __X___XX,XXXXXXX_,
  __X___X_,__X___X_,
  _X__X_X_,__X___X_,
  XX_X__X_,__X___X_,
  XXXX__X_,__X___X_,
  __X___XX,XXXXXXX_,
  _X____X_,__X___X_,
  XXXXX_X_,__X___X_,
  ______X_,__X___X_,
  ______X_,__X___X_,
  __XXX_X_,__X___X_,
  XX____XX,XXXXXXX_,
  ______X_,______X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_7F6E[ 26] = { /* code 7F6E */
  _XXXXXXX,XXXXX___,
  _X___X__,_X__X___,
  _XXXXXXX,XXXXX___,
  _______X,________,
  XXXXXXXX,XXXXXX__,
  _______X,________,
  __XXXXXX,XXXXX___,
  __X_____,____X___,
  __XXXXXX,XXXXX___,
  __X_____,____X___,
  __XXXXXX,XXXXX___,
  __X_____,____X___,
  XXXXXXXX,XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_80CC[ 30] = { /* code 80CC */
  _____X__,_X______,
  _____X__,_X___XX_,
  XXXXXX__,_XXXX___,
  _____X__,_X_____X,
  __XXXX__,_X_____X,
  XX___X__,_XXXXXX_,
  ________,________,
  __XXXXXX,XXXXXX__,
  __X_____,_____X__,
  __XXXXXX,XXXXXX__,
  __X_____,_____X__,
  __XXXXXX,XXXXXX__,
  __X_____,_____X__,
  __X_____,_____X__,
  __X_____,XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_8272[ 30] = { /* code 8272 */
  _____X__,________,
  ____XX__,________,
  ___XXXXX,XXX_____,
  __XX____,_XX_____,
  _XX_____,XX______,
  XXXXXXXX,XXXXX___,
  __X____X,____X___,
  __X____X,____X___,
  __X____X,____X___,
  __XXXXXX,XXXXX___,
  __X_____,____X___,
  __X_____,________,
  __X_____,______X_,
  __X_____,______X_,
  ___XXXXX,XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_884C[ 30] = { /* code 884C */
  ____X___,________,
  ___X___X,XXXXXXX_,
  __X_____,________,
  _X______,________,
  X____X__,________,
  ____X___,________,
  ___X__XX,XXXXXXXX,
  ___X____,____X___,
  __XX____,____X___,
  _X_X____,____X___,
  ___X____,____X___,
  ___X____,____X___,
  ___X____,____X___,
  ___X____,____X___,
  ___X____,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_8BA4[ 30] = { /* code 8BA4 */
  _X______,_X______,
  __X_____,_X______,
  __XX____,_X______,
  ___X____,_X______,
  ________,_X______,
  XXX_____,_X______,
  __X_____,_X______,
  __X_____,_XX_____,
  __X_____,X_X_____,
  __X__X__,X_X_____,
  __X_XX_X,X__X____,
  __XXX__X,___X____,
  __XX__X_,____X___,
  __X__XX_,____XX__,
  ____XX__,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_8BBE[ 28] = { /* code 8BBE */
  _X____XX,XXXX____,
  __X___X_,___X____,
  ___X__X_,___X____,
  _____X__,___X____,
  XXX_XX__,___XXXX_,
  __X_____,________,
  __X__XXX,XXXXX___,
  __X___X_,____X___,
  __X___XX,___X____,
  __X____X,__XX____,
  __X_X___,XXX_____,
  __XXX__X,XXX_____,
  _XX__XXX,___XX___,
  ___XX___,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_8BD5[ 30] = { /* code 8BD5 */
  _X______,___X_X__,
  __X_____,___X__X_,
  __XX____,___X____,
  _____XXX,XXXXXXXX,
  ________,___X____,
  XXX_____,___X____,
  __X_____,___X____,
  __X__XXX,XX_X____,
  __X____X,___X____,
  __X____X,___X____,
  __X_X__X,____X___,
  __X_X__X,____X__X,
  __XX___X,XXX_X__X,
  __X_XXXX,_____X_X,
  _X______,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_8C03[ 28] = { /* code 8C03 */
  _X______,________,
  __X__XXX,XXXXXXX_,
  __XX_X__,______X_,
  ___X_X__,__X___X_,
  _____X_X,XXXXX_X_,
  XXX__X__,__X___X_,
  __X__X_X,XXXXX_X_,
  __X__X__,______X_,
  __X__X__,XXXX__X_,
  __X_XX__,X__X__X_,
  __XX_X__,XXXX__X_,
  _X__X___,X_____X_,
  ____X___,______X_,
  ___X____,__XXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_8DDD[ 26] = { /* code 8DDD */
  _XXXXX__,XXXXXXXX,
  _X___X__,X_______,
  _X___X__,X_______,
  _X___X__,X_______,
  _XXXXX__,XXXXXXX_,
  _X_X____,X_____X_,
  ___X____,X_____X_,
  _X_XXXX_,X_____X_,
  _X_X____,XXXXXXX_,
  _X_X____,X_____X_,
  _X_X____,X_______,
  _X_XXXX_,X_______,
  XXX_____,XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_8F6C[ 32] = { /* code 8F6C */
  ___X____,__X_____,
  ___X____,__X_____,
  __X_____,_X______,
  __XXXX_X,XXXXXX__,
  _XX_____,_X______,
  _X_X____,X_______,
  _X_X__XX,XXXXXXX_,
  _X_X____,X_______,
  X__X___X,________,
  XXXXXX_X,XXXXXX__,
  ___X____,____XX__,
  ___XXXXX,___XX___,
  XXXX____,XX_X____,
  ___X____,_XX_____,
  ___X____,__XX____,
  ___X____,____X___};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_8F93[ 30] = { /* code 8F93 */
  ___X____,_XX_____,
  __X_____,X_XX____,
  XXXXXX__,X__X____,
  __X____X,____X___,
  _X____XX,XXXXXXX_,
  _X_X_XX_,______XX,
  X__X__XX,XX____X_,
  XXXXX_X_,_X__X_X_,
  ___X__X_,_X__X_X_,
  ___X__XX,XX__X_X_,
  ___XXXX_,_X__X_X_,
  XXXX__XX,XX__X_X_,
  ___X__X_,_X____X_,
  ___X__X_,_X____X_,
  ___X__XX,XX__XXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_8FD4[ 30] = { /* code 8FD4 */
  _X______,____XXX_,
  __X___XX,XXXX____,
  __XX__X_,________,
  ___X__X_,________,
  ______XX,XXXXXXX_,
  XXX___X_,______X_,
  __X___XX,X____X__,
  __X___X_,XX___X__,
  __X___X_,__XXX___,
  __X__X__,___XX___,
  __X__X__,_XX_XX__,
  __X_XX_X,XX___XX_,
  _XX_X_XX,______X_,
  XX_X____,________,
  X___XXXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_9009[ 26] = { /* code 9009 */
  _X____X_,__X_____,
  __X___X_,__X_____,
  __XX_XXX,XXXXXX__,
  ___X_X__,__X_____,
  ________,__X_____,
  XXX_XXXX,XXXXXXX_,
  __X____X,___X____,
  __X____X,___X__X_,
  __X___XX,___X__X_,
  __X__XX_,___X__X_,
  __X_XX__,___XXX__,
  XX_X____,________,
  X___XXXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_901F[ 28] = { /* code 901F */
  _X______,_X______,
  __X_____,_X______,
  __XXXXXX,XXXXXXX_,
  ___X____,_X______,
  _____XXX,XXXXXX__,
  XXX__X__,_X___X__,
  __X__X__,_X___X__,
  __X__XXX,XXXXXX__,
  __X__X__,XX___X__,
  __X____X,XXXX____,
  __X__XX_,_X__XX__,
  __X_XX__,_X___XX_,
  _XXX____,________,
  X__XXXXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_9488[ 30] = { /* code 9488 */
  __X_____,__X_____,
  __X_____,__X_____,
  _XXXXX__,__X_____,
  _X______,__X_____,
  XX______,__X_____,
  XXXXX_XX,XXXXXXX_,
  __X_____,__X_____,
  __X_____,__X_____,
  XXXXXX__,__X_____,
  __X_____,__X_____,
  __X_____,__X_____,
  __X__X__,__X_____,
  __X_X___,__X_____,
  __XX____,__X_____,
  __X_____,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_94BB[ 30] = { /* code 94BB */
  __X_____,__X_____,
  _X______,__X_____,
  _XXXXX__,__X_____,
  X_______,__XXXXXX,
  X_______,__X_____,
  XXXXXX__,__X_____,
  __X_____,__X_____,
  __X_____,__X_____,
  XXXXXX_X,XXXXXXX_,
  __X____X,______X_,
  __X____X,______X_,
  __X____X,______X_,
  __X_XX_X,______X_,
  __XXX__X,XXXXXXX_,
  __X____X,______X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_95F4[ 30] = { /* code 95F4 */
  _X______,________,
  __X__XXX,XXXXXX__,
  ___X____,_____X__,
  X_______,_____X__,
  X___XXXX,XX___X__,
  X___X___,_X___X__,
  X___X___,_X___X__,
  X___XXXX,XX___X__,
  X___X___,_X___X__,
  X___X___,_X___X__,
  X___X___,_X___X__,
  X___XXXX,XX___X__,
  X___X___,_____X__,
  X_______,_____X__,
  X_______,_XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_964D[ 30] = { /* code 964D */
  _______X,________,
  XXXX__XX,________,
  X__X_XXX,XXXXX___,
  X__X_XX_,___XX___,
  X_X_X__X,XXX_____,
  X_X____X,XXX_____,
  X_X_XXX_,___XXX__,
  X__X____,_X______,
  X__X_XXX,XXXXX___,
  X__X____,_X______,
  X__X__X_,_X______,
  XXX__X__,_X______,
  X____XXX,XXXXXX__,
  X_______,_X______,
  X_______,_X______};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont12_989C[ 30] = { /* code 989C */
  ___X____,________,
  ____X___,XXXXXXXX,
  _XXXXXXX,___X____,
  __X___X_,___X____,
  __XX_XX_,_XXXXXX_,
  ___X_X__,_X____X_,
  _XXXXXXX,_X_X__X_,
  _X____X_,_X_X__X_,
  _X__XX__,_X_X__X_,
  _XXX___X,_X_X__X_,
  _X___XX_,_X_X__X_,
  _X_XX___,XXXX__X_,
  _XX___XX,__X_XX__,
  XX__XX__,_X___XX_,
  X_XX____,X______X};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_Fontfont12_CharInfo[178] = {
   {   1,   1,   0,  17,   5, acGUI_Fontfont12_0020 } /* code 0020, SPACE */
  ,{   2,  12,   2,   5,   5, acGUI_Fontfont12_0021 } /* code 0021, EXCLAMATION MARK */
  ,{   3,   4,   2,   5,   7, acGUI_Fontfont12_0022 } /* code 0022, QUOTATION MARK */
  ,{  10,  11,   0,   5,  10, acGUI_Fontfont12_0023 } /* code 0023, NUMBER SIGN */
  ,{   7,  15,   1,   4,   9, acGUI_Fontfont12_0024 } /* code 0024, DOLLAR SIGN */
  ,{  12,  12,   1,   5,  14, acGUI_Fontfont12_0025 } /* code 0025, PERCENT SIGN */
  ,{  13,  12,   1,   5,  14, acGUI_Fontfont12_0026 } /* code 0026, AMPERSAND */
  ,{   1,   4,   1,   5,   4, acGUI_Fontfont12_0027 } /* code 0027, APOSTROPHE */
  ,{   4,  15,   1,   5,   5, acGUI_Fontfont12_0028 } /* code 0028, LEFT PARENTHESIS */
  ,{   4,  15,   0,   5,   5, acGUI_Fontfont12_0029 } /* code 0029, RIGHT PARENTHESIS */
  ,{   7,   6,   0,   5,   7, acGUI_Fontfont12_002A } /* code 002A, ASTERISK */
  ,{   7,   7,   2,   8,  12, acGUI_Fontfont12_002B } /* code 002B, PLUS SIGN */
  ,{   2,   4,   1,  15,   4, acGUI_Fontfont12_002C } /* code 002C, COMMA */
  ,{   5,   1,   1,  12,   7, acGUI_Fontfont12_002D } /* code 002D, HYPHEN-MINUS */
  ,{   2,   2,   1,  15,   4, acGUI_Fontfont12_002E } /* code 002E, FULL STOP */
  ,{   7,  14,   0,   5,   7, acGUI_Fontfont12_002F } /* code 002F, SOLIDUS */
  ,{   8,  12,   1,   5,   9, acGUI_Fontfont12_0030 } /* code 0030, DIGIT ZERO */
  ,{   4,  12,   2,   5,   9, acGUI_Fontfont12_0031 } /* code 0031, DIGIT ONE */
  ,{   7,  12,   1,   5,   9, acGUI_Fontfont12_0032 } /* code 0032, DIGIT TWO */
  ,{   8,  12,   1,   5,   9, acGUI_Fontfont12_0033 } /* code 0033, DIGIT THREE */
  ,{  10,  12,   0,   5,   9, acGUI_Fontfont12_0034 } /* code 0034, DIGIT FOUR */
  ,{   7,  12,   2,   5,   9, acGUI_Fontfont12_0035 } /* code 0035, DIGIT FIVE */
  ,{   8,  12,   1,   5,   9, acGUI_Fontfont12_0036 } /* code 0036, DIGIT SIX */
  ,{   7,  12,   1,   5,   9, acGUI_Fontfont12_0037 } /* code 0037, DIGIT SEVEN */
  ,{   8,  12,   1,   5,   9, acGUI_Fontfont12_0038 } /* code 0038, DIGIT EIGHT */
  ,{   8,  12,   1,   5,   9, acGUI_Fontfont12_0039 } /* code 0039, DIGIT NINE */
  ,{   2,   9,   1,   8,   4, acGUI_Fontfont12_003A } /* code 003A, COLON */
  ,{   2,  11,   1,   8,   4, acGUI_Fontfont12_003B } /* code 003B, SEMICOLON */
  ,{   7,   7,   2,   9,  12, acGUI_Fontfont12_003C } /* code 003C, LESS-THAN SIGN */
  ,{   8,   4,   2,  10,  12, acGUI_Fontfont12_003D } /* code 003D, EQUALS SIGN */
  ,{   7,   7,   3,   9,  12, acGUI_Fontfont12_003E } /* code 003E, GREATER-THAN SIGN */
  ,{   7,  12,   1,   5,   8, acGUI_Fontfont12_003F } /* code 003F, QUESTION MARK */
  ,{  14,  14,   1,   5,  17, acGUI_Fontfont12_0040 } /* code 0040, COMMERCIAL AT */
  ,{  11,  12,   0,   5,  11, acGUI_Fontfont12_0041 } /* code 0041, LATIN CAPITAL LETTER A */
  ,{   8,  12,   2,   5,  10, acGUI_Fontfont12_0042 } /* code 0042, LATIN CAPITAL LETTER B */
  ,{   9,  12,   1,   5,  11, acGUI_Fontfont12_0043 } /* code 0043, LATIN CAPITAL LETTER C */
  ,{  10,  12,   2,   5,  12, acGUI_Fontfont12_0044 } /* code 0044, LATIN CAPITAL LETTER D */
  ,{   7,  12,   2,   5,   9, acGUI_Fontfont12_0045 } /* code 0045, LATIN CAPITAL LETTER E */
  ,{   6,  12,   2,   5,   9, acGUI_Fontfont12_0046 } /* code 0046, LATIN CAPITAL LETTER F */
  ,{  10,  12,   1,   5,  12, acGUI_Fontfont12_0047 } /* code 0047, LATIN CAPITAL LETTER G */
  ,{   9,  12,   2,   5,  12, acGUI_Fontfont12_0048 } /* code 0048, LATIN CAPITAL LETTER H */
  ,{   2,  12,   2,   5,   5, acGUI_Fontfont12_0049 } /* code 0049, LATIN CAPITAL LETTER I */
  ,{   5,  12,   0,   5,   6, acGUI_Fontfont12_004A } /* code 004A, LATIN CAPITAL LETTER J */
  ,{   8,  12,   2,   5,  10, acGUI_Fontfont12_004B } /* code 004B, LATIN CAPITAL LETTER K */
  ,{   6,  12,   2,   5,   8, acGUI_Fontfont12_004C } /* code 004C, LATIN CAPITAL LETTER L */
  ,{  12,  12,   2,   5,  16, acGUI_Fontfont12_004D } /* code 004D, LATIN CAPITAL LETTER M */
  ,{  10,  12,   2,   5,  13, acGUI_Fontfont12_004E } /* code 004E, LATIN CAPITAL LETTER N */
  ,{  12,  12,   1,   5,  13, acGUI_Fontfont12_004F } /* code 004F, LATIN CAPITAL LETTER O */
  ,{   8,  12,   2,   5,  10, acGUI_Fontfont12_0050 } /* code 0050, LATIN CAPITAL LETTER P */
  ,{  13,  14,   1,   5,  13, acGUI_Fontfont12_0051 } /* code 0051, LATIN CAPITAL LETTER Q */
  ,{   8,  12,   2,   5,  10, acGUI_Fontfont12_0052 } /* code 0052, LATIN CAPITAL LETTER R */
  ,{   8,  12,   1,   5,   9, acGUI_Fontfont12_0053 } /* code 0053, LATIN CAPITAL LETTER S */
  ,{   8,  12,   1,   5,   9, acGUI_Fontfont12_0054 } /* code 0054, LATIN CAPITAL LETTER T */
  ,{  10,  12,   1,   5,  12, acGUI_Fontfont12_0055 } /* code 0055, LATIN CAPITAL LETTER U */
  ,{  11,  12,   0,   5,  11, acGUI_Fontfont12_0056 } /* code 0056, LATIN CAPITAL LETTER V */
  ,{  16,  12,   0,   5,  16, acGUI_Fontfont12_0057 } /* code 0057, LATIN CAPITAL LETTER W */
  ,{  10,  12,   0,   5,  10, acGUI_Fontfont12_0058 } /* code 0058, LATIN CAPITAL LETTER X */
  ,{  10,  12,   0,   5,  10, acGUI_Fontfont12_0059 } /* code 0059, LATIN CAPITAL LETTER Y */
  ,{  10,  12,   0,   5,  10, acGUI_Fontfont12_005A } /* code 005A, LATIN CAPITAL LETTER Z */
  ,{   3,  15,   2,   5,   5, acGUI_Fontfont12_005B } /* code 005B, LEFT SQUARE BRACKET */
  ,{   7,  14,   0,   5,   7, acGUI_Fontfont12_005C } /* code 005C, REVERSE SOLIDUS */
  ,{   3,  15,   0,   5,   5, acGUI_Fontfont12_005D } /* code 005D, RIGHT SQUARE BRACKET */
  ,{   8,   7,   2,   5,  12, acGUI_Fontfont12_005E } /* code 005E, CIRCUMFLEX ACCENT */
  ,{   7,   1,   0,  20,   7, acGUI_Fontfont12_005F } /* code 005F, LOW LINE */
  ,{   3,   3,   1,   4,   5, acGUI_Fontfont12_0060 } /* code 0060, GRAVE ACCENT */
  ,{   7,   9,   1,   8,   9, acGUI_Fontfont12_0061 } /* code 0061, LATIN SMALL LETTER A */
  ,{   9,  13,   1,   4,  10, acGUI_Fontfont12_0062 } /* code 0062, LATIN SMALL LETTER B */
  ,{   6,   9,   1,   8,   8, acGUI_Fontfont12_0063 } /* code 0063, LATIN SMALL LETTER C */
  ,{   8,  13,   1,   4,  10, acGUI_Fontfont12_0064 } /* code 0064, LATIN SMALL LETTER D */
  ,{   8,   9,   1,   8,   9, acGUI_Fontfont12_0065 } /* code 0065, LATIN SMALL LETTER E */
  ,{   5,  13,   1,   4,   6, acGUI_Fontfont12_0066 } /* code 0066, LATIN SMALL LETTER F */
  ,{   8,  13,   1,   8,  10, acGUI_Fontfont12_0067 } /* code 0067, LATIN SMALL LETTER G */
  ,{   8,  13,   1,   4,  10, acGUI_Fontfont12_0068 } /* code 0068, LATIN SMALL LETTER H */
  ,{   2,  13,   1,   4,   4, acGUI_Fontfont12_0069 } /* code 0069, LATIN SMALL LETTER I */
  ,{   5,  17,  -2,   4,   4, acGUI_Fontfont12_006A } /* code 006A, LATIN SMALL LETTER J */
  ,{   8,  13,   1,   4,   9, acGUI_Fontfont12_006B } /* code 006B, LATIN SMALL LETTER K */
  ,{   2,  13,   1,   4,   4, acGUI_Fontfont12_006C } /* code 006C, LATIN SMALL LETTER L */
  ,{  13,   9,   1,   8,  15, acGUI_Fontfont12_006D } /* code 006D, LATIN SMALL LETTER M */
  ,{   8,   9,   1,   8,  10, acGUI_Fontfont12_006E } /* code 006E, LATIN SMALL LETTER N */
  ,{   9,   9,   1,   8,  10, acGUI_Fontfont12_006F } /* code 006F, LATIN SMALL LETTER O */
  ,{   9,  13,   1,   8,  10, acGUI_Fontfont12_0070 } /* code 0070, LATIN SMALL LETTER P */
  ,{   8,  13,   1,   8,  10, acGUI_Fontfont12_0071 } /* code 0071, LATIN SMALL LETTER Q */
  ,{   5,   9,   1,   8,   6, acGUI_Fontfont12_0072 } /* code 0072, LATIN SMALL LETTER R */
  ,{   6,   9,   1,   8,   7, acGUI_Fontfont12_0073 } /* code 0073, LATIN SMALL LETTER S */
  ,{   5,  12,   1,   5,   6, acGUI_Fontfont12_0074 } /* code 0074, LATIN SMALL LETTER T */
  ,{   8,   9,   1,   8,  10, acGUI_Fontfont12_0075 } /* code 0075, LATIN SMALL LETTER U */
  ,{   8,   9,   0,   8,   8, acGUI_Fontfont12_0076 } /* code 0076, LATIN SMALL LETTER V */
  ,{  13,   9,   0,   8,  13, acGUI_Fontfont12_0077 } /* code 0077, LATIN SMALL LETTER W */
  ,{   8,   9,   0,   8,   8, acGUI_Fontfont12_0078 } /* code 0078, LATIN SMALL LETTER X */
  ,{   8,  13,   0,   8,   8, acGUI_Fontfont12_0079 } /* code 0079, LATIN SMALL LETTER Y */
  ,{   8,   9,   0,   8,   8, acGUI_Fontfont12_007A } /* code 007A, LATIN SMALL LETTER Z */
  ,{   3,  15,   1,   5,   5, acGUI_Fontfont12_007B } /* code 007B, LEFT CURLY BRACKET */
  ,{   1,  17,   1,   4,   4, acGUI_Fontfont12_007C } /* code 007C, VERTICAL LINE */
  ,{   3,  15,   1,   5,   5, acGUI_Fontfont12_007D } /* code 007D, RIGHT CURLY BRACKET */
  ,{   8,   2,   2,  11,  12, acGUI_Fontfont12_007E } /* code 007E, TILDE */
  ,{   1,   1,   0,  17,   5, acGUI_Fontfont12_007F } /* code 007F, <control> */
  ,{  16,  13,   0,   5,  16, acGUI_Fontfont12_4E0A } /* code 4E0A */
  ,{  16,  14,   0,   5,  16, acGUI_Fontfont12_4E0B } /* code 4E0B */
  ,{  16,  14,   0,   4,  16, acGUI_Fontfont12_4E3B } /* code 4E3B */
  ,{  15,  15,   0,   4,  16, acGUI_Fontfont12_4ECE } /* code 4ECE */
  ,{  16,  14,   0,   4,  16, acGUI_Fontfont12_4EF6 } /* code 4EF6 */
  ,{  16,  15,   0,   4,  16, acGUI_Fontfont12_4F20 } /* code 4F20 */
  ,{  16,  15,   0,   4,  16, acGUI_Fontfont12_4F4D } /* code 4F4D */
  ,{  16,  15,   0,   4,  16, acGUI_Fontfont12_4F5C } /* code 4F5C */
  ,{  15,  15,   0,   4,  16, acGUI_Fontfont12_5076 } /* code 5076 */
  ,{  15,  14,   1,   4,  16, acGUI_Fontfont12_5149 } /* code 5149 */
  ,{  15,  14,   1,   5,  16, acGUI_Fontfont12_5165 } /* code 5165 */
  ,{  16,  15,   0,   4,  16, acGUI_Fontfont12_51C6 } /* code 51C6 */
  ,{  16,  15,   0,   4,  16, acGUI_Fontfont12_51CF } /* code 51CF */
  ,{  15,  15,   0,   4,  16, acGUI_Fontfont12_5207 } /* code 5207 */
  ,{  15,  15,   0,   4,  16, acGUI_Fontfont12_52A0 } /* code 52A0 */
  ,{  14,  14,   1,   4,  16, acGUI_Fontfont12_52A8 } /* code 52A8 */
  ,{  16,  15,   0,   4,  16, acGUI_Fontfont12_5347 } /* code 5347 */
  ,{  15,  15,   0,   4,  16, acGUI_Fontfont12_53C2 } /* code 53C2 */
  ,{  15,  13,   1,   5,  16, acGUI_Fontfont12_53D6 } /* code 53D6 */
  ,{  15,  15,   0,   4,  16, acGUI_Fontfont12_53F3 } /* code 53F3 */
  ,{  14,  14,   1,   5,  16, acGUI_Fontfont12_56DE } /* code 56DE */
  ,{  16,  14,   0,   4,  16, acGUI_Fontfont12_5757 } /* code 5757 */
  ,{  15,  15,   0,   4,  16, acGUI_Fontfont12_589E } /* code 589E */
  ,{  15,  15,   0,   4,  16, acGUI_Fontfont12_5927 } /* code 5927 */
  ,{  14,  15,   1,   4,  16, acGUI_Fontfont12_5934 } /* code 5934 */
  ,{  15,  15,   0,   4,  16, acGUI_Fontfont12_5947 } /* code 5947 */
  ,{  15,  14,   0,   4,  16, acGUI_Fontfont12_5B54 } /* code 5B54 */
  ,{  16,  15,   0,   4,  16, acGUI_Fontfont12_5B9A } /* code 5B9A */
  ,{  16,  14,   0,   4,  16, acGUI_Fontfont12_5C0F } /* code 5C0F */
  ,{  15,  14,   1,   4,  16, acGUI_Fontfont12_5C11 } /* code 5C11 */
  ,{  16,  13,   0,   5,  16, acGUI_Fontfont12_5C4F } /* code 5C4F */
  ,{  16,  13,   0,   5,  16, acGUI_Fontfont12_5DE5 } /* code 5DE5 */
  ,{  16,  14,   0,   4,  16, acGUI_Fontfont12_5DE6 } /* code 5DE6 */
  ,{  15,  15,   0,   4,  16, acGUI_Fontfont12_5E55 } /* code 5E55 */
  ,{  16,  14,   0,   4,  16, acGUI_Fontfont12_5EA6 } /* code 5EA6 */
  ,{  16,  15,   0,   4,  16, acGUI_Fontfont12_5F0F } /* code 5F0F */
  ,{  16,  14,   0,   4,  16, acGUI_Fontfont12_6253 } /* code 6253 */
  ,{  16,  14,   0,   4,  16, acGUI_Fontfont12_6267 } /* code 6267 */
  ,{  15,  14,   1,   4,  16, acGUI_Fontfont12_6269 } /* code 6269 */
  ,{  16,  15,   0,   4,  16, acGUI_Fontfont12_62E9 } /* code 62E9 */
  ,{  15,  14,   0,   4,  16, acGUI_Fontfont12_6362 } /* code 6362 */
  ,{  16,  15,   0,   4,  16, acGUI_Fontfont12_636E } /* code 636E */
  ,{  16,  15,   0,   4,  16, acGUI_Fontfont12_6392 } /* code 6392 */
  ,{  16,  15,   0,   4,  16, acGUI_Fontfont12_64CD } /* code 64CD */
  ,{  15,  15,   0,   4,  16, acGUI_Fontfont12_6570 } /* code 6570 */
  ,{  16,  14,   0,   4,  16, acGUI_Fontfont12_6574 } /* code 6574 */
  ,{  15,  13,   0,   5,  16, acGUI_Fontfont12_65E0 } /* code 65E0 */
  ,{  16,  14,   0,   4,  16, acGUI_Fontfont12_673A } /* code 673A */
  ,{  15,  16,   1,   3,  16, acGUI_Fontfont12_6821 } /* code 6821 */
  ,{  15,  15,   1,   4,  16, acGUI_Fontfont12_68C0 } /* code 68C0 */
  ,{  15,  15,   1,   4,  16, acGUI_Fontfont12_6A21 } /* code 6A21 */
  ,{  16,  15,   0,   4,  16, acGUI_Fontfont12_6A2A } /* code 6A2A */
  ,{  16,  14,   0,   4,  16, acGUI_Fontfont12_6B21 } /* code 6B21 */
  ,{  14,  15,   1,   4,  16, acGUI_Fontfont12_6D4B } /* code 6D4B */
  ,{  14,  13,   1,   5,  16, acGUI_Fontfont12_6D88 } /* code 6D88 */
  ,{  15,  15,   1,   4,  16, acGUI_Fontfont12_6DF1 } /* code 6DF1 */
  ,{  15,  15,   1,   5,  16, acGUI_Fontfont12_73AF } /* code 73AF */
  ,{  14,  14,   1,   4,  16, acGUI_Fontfont12_7535 } /* code 7535 */
  ,{  15,  14,   0,   4,  16, acGUI_Fontfont12_786E } /* code 786E */
  ,{  15,  14,   0,   4,  16, acGUI_Fontfont12_7AD6 } /* code 7AD6 */
  ,{  15,  15,   0,   4,  16, acGUI_Fontfont12_7C97 } /* code 7C97 */
  ,{  16,  14,   0,   4,  16, acGUI_Fontfont12_7EBF } /* code 7EBF */
  ,{  15,  14,   0,   4,  16, acGUI_Fontfont12_7EC6 } /* code 7EC6 */
  ,{  14,  13,   1,   5,  16, acGUI_Fontfont12_7F6E } /* code 7F6E */
  ,{  16,  15,   0,   4,  16, acGUI_Fontfont12_80CC } /* code 80CC */
  ,{  15,  15,   0,   3,  16, acGUI_Fontfont12_8272 } /* code 8272 */
  ,{  16,  15,   0,   4,  16, acGUI_Fontfont12_884C } /* code 884C */
  ,{  15,  15,   1,   4,  16, acGUI_Fontfont12_8BA4 } /* code 8BA4 */
  ,{  15,  14,   1,   5,  16, acGUI_Fontfont12_8BBE } /* code 8BBE */
  ,{  16,  15,   0,   4,  16, acGUI_Fontfont12_8BD5 } /* code 8BD5 */
  ,{  15,  14,   0,   4,  16, acGUI_Fontfont12_8C03 } /* code 8C03 */
  ,{  16,  13,   0,   5,  16, acGUI_Fontfont12_8DDD } /* code 8DDD */
  ,{  15,  16,   1,   3,  16, acGUI_Fontfont12_8F6C } /* code 8F6C */
  ,{  16,  15,   0,   4,  16, acGUI_Fontfont12_8F93 } /* code 8F93 */
  ,{  16,  15,   0,   4,  16, acGUI_Fontfont12_8FD4 } /* code 8FD4 */
  ,{  15,  13,   0,   5,  16, acGUI_Fontfont12_9009 } /* code 9009 */
  ,{  15,  14,   0,   4,  16, acGUI_Fontfont12_901F } /* code 901F */
  ,{  15,  15,   1,   4,  16, acGUI_Fontfont12_9488 } /* code 9488 */
  ,{  16,  15,   0,   4,  16, acGUI_Fontfont12_94BB } /* code 94BB */
  ,{  14,  15,   1,   4,  16, acGUI_Fontfont12_95F4 } /* code 95F4 */
  ,{  14,  15,   1,   4,  16, acGUI_Fontfont12_964D } /* code 964D */
  ,{  16,  15,   0,   4,  16, acGUI_Fontfont12_989C } /* code 989C */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop81 = {
   0x989C /* first character */
  ,0x989C /* last character  */
  ,&GUI_Fontfont12_CharInfo[177] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop80 = {
   0x964D /* first character */
  ,0x964D /* last character  */
  ,&GUI_Fontfont12_CharInfo[176] /* address of first character */
  ,&GUI_Fontfont12_Prop81 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop79 = {
   0x95F4 /* first character */
  ,0x95F4 /* last character  */
  ,&GUI_Fontfont12_CharInfo[175] /* address of first character */
  ,&GUI_Fontfont12_Prop80 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop78 = {
   0x94BB /* first character */
  ,0x94BB /* last character  */
  ,&GUI_Fontfont12_CharInfo[174] /* address of first character */
  ,&GUI_Fontfont12_Prop79 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop77 = {
   0x9488 /* first character */
  ,0x9488 /* last character  */
  ,&GUI_Fontfont12_CharInfo[173] /* address of first character */
  ,&GUI_Fontfont12_Prop78 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop76 = {
   0x901F /* first character */
  ,0x901F /* last character  */
  ,&GUI_Fontfont12_CharInfo[172] /* address of first character */
  ,&GUI_Fontfont12_Prop77 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop75 = {
   0x9009 /* first character */
  ,0x9009 /* last character  */
  ,&GUI_Fontfont12_CharInfo[171] /* address of first character */
  ,&GUI_Fontfont12_Prop76 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop74 = {
   0x8FD4 /* first character */
  ,0x8FD4 /* last character  */
  ,&GUI_Fontfont12_CharInfo[170] /* address of first character */
  ,&GUI_Fontfont12_Prop75 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop73 = {
   0x8F93 /* first character */
  ,0x8F93 /* last character  */
  ,&GUI_Fontfont12_CharInfo[169] /* address of first character */
  ,&GUI_Fontfont12_Prop74 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop72 = {
   0x8F6C /* first character */
  ,0x8F6C /* last character  */
  ,&GUI_Fontfont12_CharInfo[168] /* address of first character */
  ,&GUI_Fontfont12_Prop73 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop71 = {
   0x8DDD /* first character */
  ,0x8DDD /* last character  */
  ,&GUI_Fontfont12_CharInfo[167] /* address of first character */
  ,&GUI_Fontfont12_Prop72 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop70 = {
   0x8C03 /* first character */
  ,0x8C03 /* last character  */
  ,&GUI_Fontfont12_CharInfo[166] /* address of first character */
  ,&GUI_Fontfont12_Prop71 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop69 = {
   0x8BD5 /* first character */
  ,0x8BD5 /* last character  */
  ,&GUI_Fontfont12_CharInfo[165] /* address of first character */
  ,&GUI_Fontfont12_Prop70 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop68 = {
   0x8BBE /* first character */
  ,0x8BBE /* last character  */
  ,&GUI_Fontfont12_CharInfo[164] /* address of first character */
  ,&GUI_Fontfont12_Prop69 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop67 = {
   0x8BA4 /* first character */
  ,0x8BA4 /* last character  */
  ,&GUI_Fontfont12_CharInfo[163] /* address of first character */
  ,&GUI_Fontfont12_Prop68 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop66 = {
   0x884C /* first character */
  ,0x884C /* last character  */
  ,&GUI_Fontfont12_CharInfo[162] /* address of first character */
  ,&GUI_Fontfont12_Prop67 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop65 = {
   0x8272 /* first character */
  ,0x8272 /* last character  */
  ,&GUI_Fontfont12_CharInfo[161] /* address of first character */
  ,&GUI_Fontfont12_Prop66 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop64 = {
   0x80CC /* first character */
  ,0x80CC /* last character  */
  ,&GUI_Fontfont12_CharInfo[160] /* address of first character */
  ,&GUI_Fontfont12_Prop65 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop63 = {
   0x7F6E /* first character */
  ,0x7F6E /* last character  */
  ,&GUI_Fontfont12_CharInfo[159] /* address of first character */
  ,&GUI_Fontfont12_Prop64 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop62 = {
   0x7EC6 /* first character */
  ,0x7EC6 /* last character  */
  ,&GUI_Fontfont12_CharInfo[158] /* address of first character */
  ,&GUI_Fontfont12_Prop63 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop61 = {
   0x7EBF /* first character */
  ,0x7EBF /* last character  */
  ,&GUI_Fontfont12_CharInfo[157] /* address of first character */
  ,&GUI_Fontfont12_Prop62 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop60 = {
   0x7C97 /* first character */
  ,0x7C97 /* last character  */
  ,&GUI_Fontfont12_CharInfo[156] /* address of first character */
  ,&GUI_Fontfont12_Prop61 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop59 = {
   0x7AD6 /* first character */
  ,0x7AD6 /* last character  */
  ,&GUI_Fontfont12_CharInfo[155] /* address of first character */
  ,&GUI_Fontfont12_Prop60 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop58 = {
   0x786E /* first character */
  ,0x786E /* last character  */
  ,&GUI_Fontfont12_CharInfo[154] /* address of first character */
  ,&GUI_Fontfont12_Prop59 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop57 = {
   0x7535 /* first character */
  ,0x7535 /* last character  */
  ,&GUI_Fontfont12_CharInfo[153] /* address of first character */
  ,&GUI_Fontfont12_Prop58 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop56 = {
   0x73AF /* first character */
  ,0x73AF /* last character  */
  ,&GUI_Fontfont12_CharInfo[152] /* address of first character */
  ,&GUI_Fontfont12_Prop57 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop55 = {
   0x6DF1 /* first character */
  ,0x6DF1 /* last character  */
  ,&GUI_Fontfont12_CharInfo[151] /* address of first character */
  ,&GUI_Fontfont12_Prop56 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop54 = {
   0x6D88 /* first character */
  ,0x6D88 /* last character  */
  ,&GUI_Fontfont12_CharInfo[150] /* address of first character */
  ,&GUI_Fontfont12_Prop55 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop53 = {
   0x6D4B /* first character */
  ,0x6D4B /* last character  */
  ,&GUI_Fontfont12_CharInfo[149] /* address of first character */
  ,&GUI_Fontfont12_Prop54 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop52 = {
   0x6B21 /* first character */
  ,0x6B21 /* last character  */
  ,&GUI_Fontfont12_CharInfo[148] /* address of first character */
  ,&GUI_Fontfont12_Prop53 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop51 = {
   0x6A2A /* first character */
  ,0x6A2A /* last character  */
  ,&GUI_Fontfont12_CharInfo[147] /* address of first character */
  ,&GUI_Fontfont12_Prop52 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop50 = {
   0x6A21 /* first character */
  ,0x6A21 /* last character  */
  ,&GUI_Fontfont12_CharInfo[146] /* address of first character */
  ,&GUI_Fontfont12_Prop51 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop49 = {
   0x68C0 /* first character */
  ,0x68C0 /* last character  */
  ,&GUI_Fontfont12_CharInfo[145] /* address of first character */
  ,&GUI_Fontfont12_Prop50 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop48 = {
   0x6821 /* first character */
  ,0x6821 /* last character  */
  ,&GUI_Fontfont12_CharInfo[144] /* address of first character */
  ,&GUI_Fontfont12_Prop49 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop47 = {
   0x673A /* first character */
  ,0x673A /* last character  */
  ,&GUI_Fontfont12_CharInfo[143] /* address of first character */
  ,&GUI_Fontfont12_Prop48 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop46 = {
   0x65E0 /* first character */
  ,0x65E0 /* last character  */
  ,&GUI_Fontfont12_CharInfo[142] /* address of first character */
  ,&GUI_Fontfont12_Prop47 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop45 = {
   0x6574 /* first character */
  ,0x6574 /* last character  */
  ,&GUI_Fontfont12_CharInfo[141] /* address of first character */
  ,&GUI_Fontfont12_Prop46 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop44 = {
   0x6570 /* first character */
  ,0x6570 /* last character  */
  ,&GUI_Fontfont12_CharInfo[140] /* address of first character */
  ,&GUI_Fontfont12_Prop45 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop43 = {
   0x64CD /* first character */
  ,0x64CD /* last character  */
  ,&GUI_Fontfont12_CharInfo[139] /* address of first character */
  ,&GUI_Fontfont12_Prop44 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop42 = {
   0x6392 /* first character */
  ,0x6392 /* last character  */
  ,&GUI_Fontfont12_CharInfo[138] /* address of first character */
  ,&GUI_Fontfont12_Prop43 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop41 = {
   0x636E /* first character */
  ,0x636E /* last character  */
  ,&GUI_Fontfont12_CharInfo[137] /* address of first character */
  ,&GUI_Fontfont12_Prop42 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop40 = {
   0x6362 /* first character */
  ,0x6362 /* last character  */
  ,&GUI_Fontfont12_CharInfo[136] /* address of first character */
  ,&GUI_Fontfont12_Prop41 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop39 = {
   0x62E9 /* first character */
  ,0x62E9 /* last character  */
  ,&GUI_Fontfont12_CharInfo[135] /* address of first character */
  ,&GUI_Fontfont12_Prop40 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop38 = {
   0x6269 /* first character */
  ,0x6269 /* last character  */
  ,&GUI_Fontfont12_CharInfo[134] /* address of first character */
  ,&GUI_Fontfont12_Prop39 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop37 = {
   0x6267 /* first character */
  ,0x6267 /* last character  */
  ,&GUI_Fontfont12_CharInfo[133] /* address of first character */
  ,&GUI_Fontfont12_Prop38 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop36 = {
   0x6253 /* first character */
  ,0x6253 /* last character  */
  ,&GUI_Fontfont12_CharInfo[132] /* address of first character */
  ,&GUI_Fontfont12_Prop37 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop35 = {
   0x5F0F /* first character */
  ,0x5F0F /* last character  */
  ,&GUI_Fontfont12_CharInfo[131] /* address of first character */
  ,&GUI_Fontfont12_Prop36 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop34 = {
   0x5EA6 /* first character */
  ,0x5EA6 /* last character  */
  ,&GUI_Fontfont12_CharInfo[130] /* address of first character */
  ,&GUI_Fontfont12_Prop35 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop33 = {
   0x5E55 /* first character */
  ,0x5E55 /* last character  */
  ,&GUI_Fontfont12_CharInfo[129] /* address of first character */
  ,&GUI_Fontfont12_Prop34 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop32 = {
   0x5DE5 /* first character */
  ,0x5DE6 /* last character  */
  ,&GUI_Fontfont12_CharInfo[127] /* address of first character */
  ,&GUI_Fontfont12_Prop33 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop31 = {
   0x5C4F /* first character */
  ,0x5C4F /* last character  */
  ,&GUI_Fontfont12_CharInfo[126] /* address of first character */
  ,&GUI_Fontfont12_Prop32 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop30 = {
   0x5C11 /* first character */
  ,0x5C11 /* last character  */
  ,&GUI_Fontfont12_CharInfo[125] /* address of first character */
  ,&GUI_Fontfont12_Prop31 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop29 = {
   0x5C0F /* first character */
  ,0x5C0F /* last character  */
  ,&GUI_Fontfont12_CharInfo[124] /* address of first character */
  ,&GUI_Fontfont12_Prop30 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop28 = {
   0x5B9A /* first character */
  ,0x5B9A /* last character  */
  ,&GUI_Fontfont12_CharInfo[123] /* address of first character */
  ,&GUI_Fontfont12_Prop29 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop27 = {
   0x5B54 /* first character */
  ,0x5B54 /* last character  */
  ,&GUI_Fontfont12_CharInfo[122] /* address of first character */
  ,&GUI_Fontfont12_Prop28 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop26 = {
   0x5947 /* first character */
  ,0x5947 /* last character  */
  ,&GUI_Fontfont12_CharInfo[121] /* address of first character */
  ,&GUI_Fontfont12_Prop27 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop25 = {
   0x5934 /* first character */
  ,0x5934 /* last character  */
  ,&GUI_Fontfont12_CharInfo[120] /* address of first character */
  ,&GUI_Fontfont12_Prop26 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop24 = {
   0x5927 /* first character */
  ,0x5927 /* last character  */
  ,&GUI_Fontfont12_CharInfo[119] /* address of first character */
  ,&GUI_Fontfont12_Prop25 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop23 = {
   0x589E /* first character */
  ,0x589E /* last character  */
  ,&GUI_Fontfont12_CharInfo[118] /* address of first character */
  ,&GUI_Fontfont12_Prop24 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop22 = {
   0x5757 /* first character */
  ,0x5757 /* last character  */
  ,&GUI_Fontfont12_CharInfo[117] /* address of first character */
  ,&GUI_Fontfont12_Prop23 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop21 = {
   0x56DE /* first character */
  ,0x56DE /* last character  */
  ,&GUI_Fontfont12_CharInfo[116] /* address of first character */
  ,&GUI_Fontfont12_Prop22 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop20 = {
   0x53F3 /* first character */
  ,0x53F3 /* last character  */
  ,&GUI_Fontfont12_CharInfo[115] /* address of first character */
  ,&GUI_Fontfont12_Prop21 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop19 = {
   0x53D6 /* first character */
  ,0x53D6 /* last character  */
  ,&GUI_Fontfont12_CharInfo[114] /* address of first character */
  ,&GUI_Fontfont12_Prop20 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop18 = {
   0x53C2 /* first character */
  ,0x53C2 /* last character  */
  ,&GUI_Fontfont12_CharInfo[113] /* address of first character */
  ,&GUI_Fontfont12_Prop19 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop17 = {
   0x5347 /* first character */
  ,0x5347 /* last character  */
  ,&GUI_Fontfont12_CharInfo[112] /* address of first character */
  ,&GUI_Fontfont12_Prop18 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop16 = {
   0x52A8 /* first character */
  ,0x52A8 /* last character  */
  ,&GUI_Fontfont12_CharInfo[111] /* address of first character */
  ,&GUI_Fontfont12_Prop17 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop15 = {
   0x52A0 /* first character */
  ,0x52A0 /* last character  */
  ,&GUI_Fontfont12_CharInfo[110] /* address of first character */
  ,&GUI_Fontfont12_Prop16 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop14 = {
   0x5207 /* first character */
  ,0x5207 /* last character  */
  ,&GUI_Fontfont12_CharInfo[109] /* address of first character */
  ,&GUI_Fontfont12_Prop15 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop13 = {
   0x51CF /* first character */
  ,0x51CF /* last character  */
  ,&GUI_Fontfont12_CharInfo[108] /* address of first character */
  ,&GUI_Fontfont12_Prop14 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop12 = {
   0x51C6 /* first character */
  ,0x51C6 /* last character  */
  ,&GUI_Fontfont12_CharInfo[107] /* address of first character */
  ,&GUI_Fontfont12_Prop13 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop11 = {
   0x5165 /* first character */
  ,0x5165 /* last character  */
  ,&GUI_Fontfont12_CharInfo[106] /* address of first character */
  ,&GUI_Fontfont12_Prop12 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop10 = {
   0x5149 /* first character */
  ,0x5149 /* last character  */
  ,&GUI_Fontfont12_CharInfo[105] /* address of first character */
  ,&GUI_Fontfont12_Prop11 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop9 = {
   0x5076 /* first character */
  ,0x5076 /* last character  */
  ,&GUI_Fontfont12_CharInfo[104] /* address of first character */
  ,&GUI_Fontfont12_Prop10 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop8 = {
   0x4F5C /* first character */
  ,0x4F5C /* last character  */
  ,&GUI_Fontfont12_CharInfo[103] /* address of first character */
  ,&GUI_Fontfont12_Prop9 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop7 = {
   0x4F4D /* first character */
  ,0x4F4D /* last character  */
  ,&GUI_Fontfont12_CharInfo[102] /* address of first character */
  ,&GUI_Fontfont12_Prop8 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop6 = {
   0x4F20 /* first character */
  ,0x4F20 /* last character  */
  ,&GUI_Fontfont12_CharInfo[101] /* address of first character */
  ,&GUI_Fontfont12_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop5 = {
   0x4EF6 /* first character */
  ,0x4EF6 /* last character  */
  ,&GUI_Fontfont12_CharInfo[100] /* address of first character */
  ,&GUI_Fontfont12_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop4 = {
   0x4ECE /* first character */
  ,0x4ECE /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 99] /* address of first character */
  ,&GUI_Fontfont12_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop3 = {
   0x4E3B /* first character */
  ,0x4E3B /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 98] /* address of first character */
  ,&GUI_Fontfont12_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop2 = {
   0x4E0A /* first character */
  ,0x4E0B /* last character  */
  ,&GUI_Fontfont12_CharInfo[ 96] /* address of first character */
  ,&GUI_Fontfont12_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont12_Prop1 = {
   0x0020 /* first character */
  ,0x007F /* last character  */
  ,&GUI_Fontfont12_CharInfo[  0] /* address of first character */
  ,&GUI_Fontfont12_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontfont12 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,21 /* height of font  */
  ,21 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontfont12_Prop1}
  ,17 /* Baseline */
  ,9 /* Height of lowercase characters */
  ,12 /* Height of capital characters */
};

